# Builds cgn/guide.json for the Cologne Christmas 2026 guide from researched content + creator DB export.
import json, re, collections, urllib.parse
D = '/home/claude/cityguide/cgn'
api = json.load(open(f'{D}/api.json'))
tips = json.load(open(f'{D}/tips.json'))['tips']
costs = json.load(open(f'{D}/costs.json'))
key = lambda n: re.sub(r'[^a-z0-9]', '', n.lower())[:14]
maps = lambda q: 'https://www.google.com/maps/search/?api=1&query=' + urllib.parse.quote(q + ' Köln')
book = lambda q: 'https://www.booking.com/searchresults.html?ss=' + urllib.parse.quote(q + ' Köln') + '&aid=YOUR_AID_HERE'

# creators + sources from the DB export (only videos that yielded facts)
srcs = {s['id']: s for s in api['sources']}
used, cnt = {}, collections.Counter()
for v in api['facts'].values():
    for f in v:
        used.setdefault(f['source_id'], f['creator']); cnt[f['creator']] += 1
creators = {}
for sid, name in used.items():
    creators.setdefault(key(name), {'name': name, 'url': srcs.get(sid, {}).get('url') or f'https://www.youtube.com/watch?v={sid[3:]}'})
sources = sorted([{'creator': used[sid], 'creator_url': creators[key(used[sid])]['url'], 'title': s['title'], 'url': s['url'], 'date': (s.get('published_at') or '')[:7]}
                  for sid, s in srcs.items() if sid in used], key=lambda x: x['creator'].lower())
NC, NV = len(creators), len(sources)

G = {
 'city': 'Cologne', 'slug': 'cologne', 'country': 'Germany', 'edition': 'Christmas 2026 edition', 'updated': '2026-09-29',
 'status': "Draft for Barry's approval", 'audience': 'Families and solo travellers',
 'tagline': 'The Wiley Fox guide to Cologne for families and solo travellers',
 'cover_blurb': f'What {NC} travel creators actually say about Cologne, checked against the 2025 police figures - seven Christmas markets in one walkable centre, where to stay, what to eat, and the handful of places police watch most closely.',
 'banner_text': 'Official travel advice for 200+ countries, community reports, one-tap SOS, and QR wristbands so lost children and lost bags find their way back.',
 'safety': {
  'wf_rating': 3, 'wf_label': 'Moderate',
  'wf_summary': "Cologne is a big, busy city with more recorded crime than most German cities its size. Police recorded 11,362 offences per 100,000 residents in 2025 (Cologne and Leverkusen together), down 2.4% on 2024, and in the Eurostat comparison below it sits mid-table among Germany's big cities - well above Munich and Nuremberg, close to Hamburg, Berlin and Düsseldorf. The trend is going the right way: pickpocketing fell by 31% in 2025, street robbery by 21% and robbery overall by 13%. The crime that matters most to visitors is concentrated in the city centre - about 41% of all pickpocketing happens in the central police district that covers the cathedral, the Altstadt, Neumarkt and the Ringe - and police run CCTV at seven hotspots, including the cathedral and station, Breslauer Platz, Ebertplatz and Neumarkt. This rating is for the city as a whole, not street by street: German police do not publish street-level crime data.",
  'creator_feeling': 4, 'creator_feeling_label': 'Feels safe and friendly - the crowds are the issue',
  'creator_summary': "Creators found Cologne relaxed, friendly and easy to walk. A family with a baby and a toddler found it very clean and safe (Where Is Briggs), a senior solo traveller felt safe in the historic and tourist areas (SeniorSoloTravel), and a solo woman ate alone on a Monday night and walked back to her hostel without a second thought (Rachel Wells). NiteshOnTheGo felt noticeably safer than in Paris. Nobody reported being pickpocketed. The recurring complaint is crowds: the cathedral market and Heinzels are shoulder to shoulder on weekend evenings, and Schildergasse was too crowded to move on a December Saturday.",
  'data_note': "Figures are from the Cologne police's PKS 2025 annual report, which covers Cologne and Leverkusen together, so the headline rate is for both cities. No street-level data is published; the smallest unit is the police district, and the central district (PI 1: Altstadt-Nord, Altstadt-Süd, Neustadt-Nord, Neustadt-Süd) recorded 32,100 offences in 2025, down 2%. In that district street crime fell 16% and pickpocketing 37%, but violent crime rose 7.5% (1,785 cases) and assaults 5%. Across the police area, sexual offences rose 7% and recorded rapes 21% (417). Rates are per resident, so the millions of commuters, shoppers and tourists in the centre push them up. Police CCTV locations are the ones police themselves describe as crime hotspots with a wide range of offences.",
  'data_months': ['2025-12', '2025-01'],
 },
 'official_crime': [
  {'number': '-31%', 'label': 'Pickpocketing in 2025 (5,548 cases)', 'desc': 'The biggest fall of any offence type. About 41% of cases were in the city-centre district around the cathedral, Altstadt and Neumarkt (Cologne police, PKS 2025).'},
  {'number': '11,362', 'label': 'Recorded offences per 100,000 residents in 2025', 'desc': 'Cologne and Leverkusen police area, down 2.4% on 2024. Police compare it with Dortmund, Düsseldorf, Duisburg and Essen.'},
  {'number': '274', 'label': "Offences in Cologne on New Year's Eve 2025/26", 'desc': 'Down from 369 the year before, with 13 pickpocketing and 4 sexual offences recorded across the police area (Cologne police, 8 January 2026).'},
 ],
 'crime_source': {'name': 'Polizeipräsidium Köln, PKS 2025 Auswertebericht', 'citation': "Police-area statistics for Cologne and Leverkusen in 2025, with district figures for central Cologne, plus Cologne police statements on the Christmas markets (December 2024) and New Year's Eve 2025/26, the police CCTV-location list and the NRW weapon-ban-zone rules. No street-level data is published, and rates are per resident, not adjusted for visitors."},
 'credit_fallback': 'Source: Polizeipräsidium Köln / Stadt Köln',
 'app_ctas': [
  {'where': 'before_booking', 'text': "Germany doesn't publish street-level crime data, so before you book, check your hotel's street against the map in this guide and any community reports on Wiley Fox - and if it's by the Hauptbahnhof, ask which side of the station it's on.", 'url': 'https://www.thewileyfox.com'},
  {'where': 'families', 'text': 'Clip a Wiley Fox QR wristband on each child. If you get separated in the market crowd, anyone who scans it can contact you straight away - no app needed on their side.', 'url': 'https://www.thewileyfox.com'},
  {'where': 'night', 'text': 'Walking back after the markets close? Save your hotel on Wiley Fox, stay on the lit main streets through the Altstadt and keep SOS one tap away - especially on weekend nights near the Ringe.', 'url': 'https://www.thewileyfox.com'},
  {'where': 'community', 'text': 'Found a cash-only stall, a broken cash machine or a street that felt wrong? Drop a community report on the map - it helps the next family.', 'url': 'https://www.thewileyfox.com'},
 ],
 'stats': [
  {'number': '16 Nov - 23 Dec', 'label': 'Cathedral Christmas market 2026', 'desc': 'Closed on 22 November. Heinzels on the Heumarkt runs on to 10 January 2027 (organisers, Sept 2026).'},
  {'number': '€12', 'label': 'New cathedral sightseeing ticket', 'desc': 'Since 1 July 2026; children up to 13 free, and praying or lighting a candle stays free (Kölner Dom chapter).'},
  {'number': str(NC), 'label': f'Creators · {NV} videos', 'desc': 'Paraphrased and credited, cross-checked with police figures.'},
 ],
 'overview': [
  "Cologne is built for a short break. You step out of the Hauptbahnhof and the cathedral is right in front of you; the Christmas markets, the Altstadt brewhouses, the Rhine and the Chocolate Museum are all within about half an hour's walk. The centre sits on the west bank inside a semicircle of boulevards called the Ringe; across the Hohenzollern Bridge is Deutz, with the classic view back to the cathedral. Creators suggest two to three days, and several said 48 hours felt too short.",
  "At Christmas the city runs several big markets at once, each with its own theme and its own mug: the cathedral market under a giant tree, Heinzels Wintermärchen across two Altstadt squares with an ice rink, the angels' market at Neumarkt, a St Nicholas village at Rudolfplatz and a maritime market by the Chocolate Museum. For families there is a lot to do - a Christmas post office, carousels, Ferris wheels, skating and curling - and most of it is in one walkable loop of about 1.5 km.",
  "For solo travellers Cologne feels friendly and easy, and creators felt safe. The police figures are more mixed: crime is higher than in Munich or Nuremberg, and it is concentrated in the same central squares visitors use, around the cathedral and station, Neumarkt and the Ringe at weekends. The good news is that pickpocketing and street robbery both fell sharply in 2025. This guide shows where to take care, using the latest police report.",
 ],
 'facts': {
  'Currency': 'Euro (EUR) - cards are widely taken, but some market stalls are cash only and others card only, so carry both',
  'Language': 'German - most people in the centre speak good English',
  'Time zone': 'Central European Time (UTC+1) - one hour ahead of the UK',
  'Plug': 'Type C and F, 230V - UK plugs need an adaptor',
  'Emergency': '110 police · 112 fire & ambulance · 116 117 out-of-hours doctor',
  'Entry': 'UK passport must be under 10 years old on arrival and valid 3+ months after you leave the Schengen area; visa-free for up to 90 days in any 180 (gov.uk, Sept 2026)',
  'Tipping': 'About 5-10%, or round up - tell the server the total you want to pay',
  'Best time': 'Mid-November to 23 December for the markets (weekdays are far calmer); May, September and October are cheaper and quieter',
 },
 'stay': [
  {'area': 'Around the cathedral & Hauptbahnhof', 'for': ['First-timers', 'Christmas markets', 'Arriving by train'], 'why': "Unbeatable for a short trip: the station, the cathedral market and the Altstadt are on your doorstep, and trains to Düsseldorf, Bonn and Aachen leave from here. Creators stayed at the Eden Hotel beside the market (handy for breaks with children), Urban Loft and the Marriott. The catch: police list the cathedral and station area as a crime hotspot with CCTV, and it is very busy late at night, so pick a hotel on the cathedral side rather than behind the station at Breslauer Platz.", 'creators': ['thekaracsonyif', 'worthytravels', 'thelittlebaske', 'wikipeaks']},
  {'area': 'Altstadt (Alter Markt & Heumarkt)', 'for': ['Christmas markets', 'Brewhouses', 'Couples'], 'why': "The old town between the cathedral and the Rhine: cobbled squares, the brewhouses and Heinzels Wintermärchen right outside. She Run the World's budget hotel overlooked one of the main markets and she calls the Altstadt the most central base for all of them. Expect noise from bars and market crowds until late, and busy streets at weekends.", 'creators': ['sheruntheworld', 'walshystravels', 'cityzen']},
  {'area': 'Deutz (east bank)', 'for': ['Families', 'Views', 'Quieter nights'], 'why': "Across the Hohenzollern Bridge, a few minutes' walk or one stop from the cathedral. The Hyatt Regency's best rooms look straight across at the cathedral, and Hylo Abroad's boys loved its pool. Quieter at night than the Altstadt, and next to the KölnTriangle viewpoint. Check the trade-fair calendar: big Messe events push prices up.", 'creators': ['hyloabroadtany', 'wikipeaks']},
  {'area': 'Belgian Quarter (Belgisches Viertel)', 'for': ['Solo travellers', 'Food & cafés'], 'why': "Stylish streets of boutiques, espresso bars and galleries just inside the Ringe, a short walk from Nikolausdorf, Heavenue and the Stadtgarten market. City Zen warns of noise until about 2am. It borders the Ringe and Zülpicher Straße nightlife strip, which is a weapon ban zone on weekend nights, so choose a quiet side street.", 'creators': ['cityzen', 'alicelucastrav', 'travellerjames']},
  {'area': 'Südstadt & Rheinauhafen', 'for': ['Families', 'Longer stays'], 'why': "Leafy and residential, popular with young families, with bakeries, bookshops and the Rhine promenade. You're close to the harbour market and the Chocolate Museum and about 20-30 minutes' walk from the cathedral, or a short tram ride. Walshy's Travels liked the supervised adventure playground in Friedenspark.", 'creators': ['cityzen', 'walshystravels']},
  {'area': 'Budget: stay in Düsseldorf', 'for': ['Budget', 'Two cities'], 'why': "Travelling Pandas found Cologne hotels and flights about double the price in December, so they based themselves in Düsseldorf - about 30 minutes by train, €26 return in 2025 - and did both cities' markets. Worth pricing if Cologne is full.", 'creators': ['travellingpand', 'maxandsidney']},
 ],
 'caution': [
  {'area': 'Cathedral forecourt (Domplatte) & Hauptbahnhof', 'when': 'Evenings, weekends and market season', 'note': "Police list the cathedral and station area as a crime hotspot with a wide range of offences, and it has police CCTV. It is also where most visitors arrive, so it is packed with people and luggage - ideal conditions for pickpockets. The whole city-centre district recorded 2,276 pickpocketing cases in 2025, 41% of the city total, although that was down 37%. Keep phones in inner pockets, bags zipped in front, and don't leave luggage unattended while you check a map.", 'creators': []},
  {'area': 'Breslauer Platz (behind the station) & Ebertplatz', 'when': 'Late evening and night', 'note': "Both are on the police list of crime hotspots with CCTV. Breslauer Platz is the station's back entrance and long-distance bus stop; Ebertplatz is a sunken square on the northern Ringe about 15 minutes' walk from the cathedral. Neither is somewhere travellers need to linger - use the cathedral-side exit of the station, and take a taxi or the tram rather than cutting through at night.", 'creators': []},
  {'area': 'The Ringe & Zülpicher Straße', 'when': 'Friday and Saturday nights, and 11 November', 'note': "Cologne's nightlife strip. The Ringe are a police CCTV hotspot, and the Ringe and Zülpicher Straße are weapon ban zones from 20:00 to 06:00 at weekends, before public holidays and on carnival days: knives of any blade length are banned. On 11 November, the start of carnival, tens of thousands party here and the city fences off the Zülpicher area. Fine to walk through early in the evening; late at night, get a taxi back.", 'creators': ['maxandsidney']},
  {'area': 'Neumarkt', 'when': 'Evenings', 'note': "A big transport hub and the home of the Markt der Engel. Police include Neumarkt in their CCTV crime hotspots, and creators found the angels' market very crowded after 5pm. Enjoy the market, but keep valuables close, agree a meeting point, and don't wait around the underground station entrances late at night.", 'creators': ['travellingpand', 'travelingexpat']},
  {'area': 'Cathedral market & Heinzels in the evening', 'when': 'Weekend evenings after 5pm', 'note': "Creators describe the cathedral market as 'could barely move' at night and Heinzels as 'Disneyland busy' after dark - hard going with a pushchair or small children. The little Advent market next to the cathedral market has wood chips underfoot, which are hard for pushchairs. Go at opening time or on a weekday afternoon.", 'creators': ['travellingpand', 'brickeyvlog', 'thekaracsonyif', 'mathersonthema', 'thelittlebaske']},
  {'area': 'Schildergasse & Hohe Straße', 'when': 'Saturdays in December', 'note': "The two main shopping streets link the cathedral with Neumarkt. Creators quote 13,000-15,000 shoppers an hour, and one found Schildergasse too crowded to move on a December Saturday. Crowds like this are where pickpockets work - police warn of thieves who bump into you, spill something on you or ask for directions while an accomplice steals.", 'creators': ['erensayar', 'prowalktours', 'travelranked', 'islandhoppertv']},
 ],
 'scams': [
  {'title': 'The bump, the spill and the map', 'text': 'Police say pickpockets on Christmas markets work in pairs: one jostles you, "accidentally" spills something on your coat or asks for directions, while the other takes your wallet or phone. In December 2024 Cologne police arrested several suspected pickpockets at the cathedral market and on the Alter Markt, trying jacket pockets and backpacks.', 'creators': []},
  {'title': 'Lost your card?', 'text': "Ring the German card-blocking line on +49 116 116, or your bank's own number, straight away, then report the theft to police. Keep cards, cash and your ID in different closed inner pockets, as police advise.", 'creators': []},
  {'title': 'Deposits on everything', 'text': 'Not a scam, but it catches people out: Glühwein comes with a mug deposit (€3-4 in 2025), and each market has its own mug. Return it at a drinks stall of the same market for your money, or keep it as a souvenir.', 'creators': ['travellingpand', 'adventuresofma', 'seekingparadis']},
  {'title': 'Expensive speciality food', 'text': "Pascha TV spent about €70 on six speciality dishes at the Heumarkt and says most weren't worth it. The classics - Reibekuchen, bratwurst, Handbrot - are better value.", 'creators': ['paschatv']},
 ],
 'transport': [
  {'title': 'From the airport', 'text': "The S-Bahn (S19) runs from Cologne Bonn Airport to the Hauptbahnhof in about 15 minutes, roughly every 20 minutes, and the station comes out opposite the cathedral. Creators found it easy but one reported delays both ways. Check the current fare in the KVB app: fares rose on 1 June 2026.", 'creators': ['robonholiday', 'sheruntheworld', 'urbanpigeon', 'iplanholidays']},
  {'title': 'By train', 'text': "Brussels to Cologne takes about 1h50 direct, and Düsseldorf is 20-30 minutes away. Eat See TV's train was cancelled and a 3.5-hour journey took about six hours with three changes, so leave slack. Official taxis wait outside the cathedral-side exit.", 'creators': ['sheruntheworld', 'islandhoppertv', 'eatseetv', 'urbanpigeon', 'chadandclaire']},
  {'title': 'Walking the markets', 'text': "The cathedral, Heinzels (Alter Markt and Heumarkt), Markt der Engel and Nikolausdorf form a loop of about 1.5 km on pedestrian streets. The harbour market is about 2.5 km from the cathedral along an exposed, windy stretch of the Rhine, and the Stadtgarten is about 2 km - take the tram for those. Cobbles everywhere, so wear comfortable shoes.", 'creators': ['thelittlebaske', 'worthytravels', 'adventuresofma']},
  {'title': 'Trams, U-Bahn and tickets', 'text': "KVB runs the trams and underground. From 1 June 2026 a single in Cologne is €4.00 (children 6-14 €1.80, under 6 free), and a 24-hour ticket is €9.60 for one or €19.20 for up to five people - usually the better deal for a family. Buy in the KVB app or at machines. Older videos quoting €2.90 are out of date.", 'creators': ['thelittlebaske', 'robonholiday']},
  {'title': 'Christmas Market Express', 'text': "A hop-on hop-off road train links the cathedral, the Alter Markt, the Chocolate Museum and Neumarkt, about every 15 minutes. It was €15 for adults and €7 for children under 12 in 2025; 2026 dates and prices aren't out yet. Creator reviews are mixed - one found it unreliable and slow - and walking is often quicker.", 'creators': ['worthytravels', 'travellingpand', 'adventuresofma', 'thelittlebaske']},
  {'title': 'Driving', 'text': "Car parks near the cathedral fill quickly at weekends in the market season. The station is right by the cathedral, so the train is the easy option.", 'creators': ['worthytravels', 'anayandanayrai']},
 ],
 'costs': costs,
 'top_intro': "Ranked by how often creators recommend them. Most are within a 15-minute walk of the cathedral; in December, see the sights by daylight and save the markets for the evening.",
 'top': [
  {'name': 'Cologne Cathedral (Kölner Dom)', 'area': 'Domplatte', 'why': "Germany's most visited landmark and a UNESCO site, right outside the station. Inside: the Shrine of the Three Kings and huge stained-glass windows; creators found it darker and moodier than expected. Since 1 July 2026 sightseeing inside needs a ticket; prayer entry stays free via the north portal. The 533-step south tower has no lift and closes on 11 Nov, 24, 25 and 31 Dec. Only small bags - no wheeled cases, and nowhere to leave them.", 'family': True, 'price': '€12 (children to 13 free) · tower €8 (2026)', 'url': 'https://www.koelner-dom.de', 'creators': ['tripxtreme', 'jillutravel', 'robonholiday', 'mytravelbf', 'triptipswithch', 'sophienadeau', 'walshystravels', 'alicelucastrav', 'ivandeguzman']},
  {'name': 'Hohenzollern Bridge', 'area': 'Altstadt to Deutz', 'why': "Walk across the railway bridge past hundreds of thousands of love locks to the Deutz bank for the classic view back to the cathedral - best at sunset or after dark, when it's lit. About 10 minutes each way.", 'family': True, 'price': 'Free', 'url': maps('Hohenzollernbrücke'), 'creators': ['travelingexpat', 'chadandclaire', 'triptipswithch', 'thetravelguard', 'walshystravels', 'alicelucastrav', 'eatseetv']},
  {'name': 'Chocolate Museum (Schokoladenmuseum)', 'area': 'Rheinauhafen', 'why': "A working chocolate production line, a chocolate fountain with wafers, and a café over the Rhine. Small children love it and it's a good rainy-day option, though several creators found it a bit steep. Buy online to skip the queue. The harbour Christmas market is right outside.", 'family': True, 'price': 'Adult €17.50-19 · child €10-11.50 · under 6 free (2026)', 'url': 'https://www.schokoladenmuseum.de', 'creators': ['tabieats', 'asenseoftravel', 'ourstorytotell', 'whereisbriggs', 'walshystravels', 'wyattandreyka', 'travelingexpat']},
  {'name': 'KölnTriangle viewing deck', 'area': 'Deutz', 'why': "A 29th-floor open deck about 100 m up, with the best-known view of the cathedral and the bridge and trains coming in and out. Quick and cheap - but Walshy's Travels found it closed for staff sickness, so check before crossing.", 'family': True, 'price': '€5 (children to 12 free, 2026)', 'url': 'https://www.koelntriangle.de', 'creators': ['triptipswithch', 'robonholiday', 'erensayar', 'tabieats', 'alicelucastrav']},
  {'name': 'Altstadt, Alter Markt & the Rathaus', 'area': 'Altstadt', 'why': "Colourful cobbled squares below Great St Martin church. The Rathaus is Germany's oldest town hall still in use, and its carillon plays at 9:00, 12:00, 15:00 and 18:00 (ViaTravelers) while a wooden figure sticks out its tongue on the hour. Away from the cathedral the lanes get quieter and more local.", 'family': True, 'price': 'Free', 'url': maps('Alter Markt'), 'creators': ['asenseoftravel', 'viatravelers', 'wyattandreyka', 'planestrainsev', 'guidetoeurope']},
  {'name': 'Rhine promenade & a river cruise', 'area': 'Altstadt', 'why': "The riverside walk runs from the cathedral past the Altstadt to the Rheinauhafen's crane houses. One-hour cruises leave from the Altstadt; Rob on Holiday paid about €15 and says you don't see many landmarks, so go for the drink and the view.", 'family': True, 'price': 'Cruise about €15 (2026 creator)', 'url': maps('Rheinufer Altstadt'), 'creators': ['jillutravel', 'robonholiday', 'tripxtreme', 'guidetoeurope']},
  {'name': 'Rhine cable car (Rheinseilbahn)', 'area': 'Zoo to Rheinpark', 'why': "Europe's first cable car across a river, with views back to the Old Town. In winter it runs only on the four Advent weekends in 2026 (28-29 Nov, 5-6, 12-13, 19-20 Dec), 10:00-18:00. Doors lock from the outside, and cabins take up to four.", 'family': True, 'price': '€5.50 one way / €9.50 return (2026)', 'url': 'https://www.koelner-seilbahn.de', 'creators': ['erensayar', 'tripxtreme', 'guidetoeurope', 'iplanholidays']},
  {'name': 'Cologne Zoo', 'area': 'Riehl', 'why': "One of Germany's oldest zoos (1860), with an aquarium, elephants, big cats and an ape island - a good family half-day, right next to the cable car.", 'family': True, 'price': 'Paid - check the zoo site', 'url': 'https://www.koelnerzoo.de', 'creators': ['tripxtreme', 'jillutravel', 'alicelucastrav', 'guidetoeurope']},
  {'name': 'Museum Ludwig', 'area': 'Next to the cathedral', 'why': "Twentieth-century art including Picasso and Warhol, a very short walk from the cathedral market - a warm hour between markets.", 'family': False, 'price': 'Paid', 'url': 'https://www.museum-ludwig.de', 'creators': ['worthytravels', 'alicelucastrav']},
  {'name': 'Roman-Germanic Museum (interim site)', 'area': 'Belgisches Haus, near Neumarkt', 'why': "Creators remember the Roman museum beside the cathedral, but its main building is closed for renovation. It is showing its collection in the Belgisches Haus on Cäcilienstraße, near Neumarkt, and the Dionysus mosaic cannot be visited until further notice.", 'family': True, 'price': '€6 adult (2026)', 'url': 'https://roemisch-germanisches-museum.de', 'creators': ['chadandclaire', 'ourstorytotell']},
  {'name': 'Farina Fragrance Museum', 'area': 'Altstadt', 'why': "The house that created the original eau de Cologne in 1709, with a shop where you can try the original scent.", 'family': False, 'price': 'Paid tours', 'url': 'https://www.farina.org', 'creators': ['wyattandreyka']},
  {'name': "St Ursula's Golden Chamber", 'area': 'Altstadt-Nord', 'why': "A free church hiding a chamber lined with bones in patterns - a strange, memorable 20 minutes, and not for sensitive children.", 'family': False, 'price': 'Church free · chamber about €2-3', 'url': maps('St. Ursula Kirche'), 'creators': ['travelingexpat']},
 ],
 'eat_label': 'Kölsch, Reibekuchen and Halve Hahn',
 'eat_intro': "Cologne eats in brewhouses: long wooden tables, gruff waiters called Köbes, and small glasses of Kölsch that keep coming until you put your beer mat on top. Every place is credited to the creator who recommended it, and prices carry the year.",
 'eat': [
  {'name': 'Früh am Dom', 'area': 'By the cathedral', 'type': 'Brewhouse', 'price': '€€', 'family': True, 'why': "The classic: packed, loud, a minute from the cathedral, with famously brusque Köbes. Try Halve Hahn (a rye roll with Gouda - no chicken involved), Mettbrötchen or Himmel un Ääd. Creators came for the atmosphere as much as the food.", 'creators': ['drunktopus', 'walshystravels', 'eatseetv', 'wherearewe', 'mytravelbf', 'triptipswithch'], 'url': maps('Früh am Dom')},
  {'name': 'Gaffel am Dom', 'area': 'By the station', 'type': 'Brewhouse', 'price': '€€', 'family': True, 'why': "The closest brewhouse to the station, open from 10am, so people arrive with luggage. Walshy's Travels rated its food the best of the three big brewhouses; Deana and Phil had the Rheinischer Sauerbraten with raisins and almonds. Book - seating is shared.", 'creators': ['walshystravels', 'drunktopus', 'deanaandphil'], 'url': maps('Gaffel am Dom')},
  {'name': 'Peters Brauhaus', 'area': 'Altstadt', 'type': 'Brewhouse', 'price': '€€', 'family': True, 'why': "Noisy, traditional and a bit more local, with communal benches. Pork knuckle, Himmel un Ääd and very hot mustard. MY Travel BF had slow service and a lukewarm €18 main (2025) and suggests going for the Kölsch.", 'creators': ['walshystravels', 'grownupgapyear', 'emekaiwueze', 'wikipeaks', 'mytravelbf'], 'url': maps('Peters Brauhaus')},
  {'name': 'Brauhaus Sion', 'area': 'Altstadt', 'type': 'Brewhouse', 'price': '€€', 'family': True, 'why': "A historic brewhouse with a modern feel and mostly table seating - easier with children than the standing bars. Halve Hahn, Sauerbraten and a metre of sausage.", 'creators': ['drunktopus', 'tabieats'], 'url': maps('Brauhaus Sion')},
  {'name': 'Brauhaus Schreckenskammer', 'area': 'Near St Ursula', 'type': 'Brewhouse', 'price': '€€', 'family': True, 'why': "A small, old brewery-tavern away from the crowds. Traveling Expats praised the schnitzel with Béarnaise and the friendly staff.", 'creators': ['travelingexpat'], 'url': maps('Brauhaus Schreckenskammer')},
  {'name': 'Bei Oma Kleinmann', 'area': 'Kwartier Latäng', 'type': 'Schnitzel house', 'price': '€€', 'family': True, 'why': "Famous for schnitzel since 1949. Very busy even on a Thursday, opening at 5pm with a 7pm table limit - book or arrive early.", 'creators': ['travelingexpat', 'wikipeaks'], 'url': maps('Bei Oma Kleinmann')},
  {'name': 'Reibekuchen from a takeaway window', 'area': 'Altstadt', 'type': 'Street food', 'price': '€', 'family': True, 'why': "Cologne's potato pancakes with apple sauce. Creators queued 15 minutes at an old-town stall rated 4.9 on Google: five for €5 plus €0.50 for garlic sauce (2025), and a large portion was €5.50. At the markets, three at the cathedral market were €6.", 'creators': ['grownupgapyear', 'travelingexpat', 'tabieats', 'deanaandphil', 'mytravelbf'], 'url': maps('Reibekuchen Altstadt')},
  {'name': 'Max Stark', 'area': 'Kunibertsviertel', 'type': 'Local pub', 'price': '€€', 'family': False, 'why': "Reibekuchen with smoked salmon and sour cream - only on Tuesdays from 5pm, and you need a reservation.", 'creators': ['emekaiwueze'], 'url': maps('Max Stark')},
  {'name': 'Bäckerei Zimmermann', 'area': 'Centre', 'type': 'Bakery', 'price': '€', 'family': True, 'why': "Open since 1875 and popular for its cinnamon roll with cream-cheese topping.", 'creators': ['wherearewe'], 'url': maps('Bäckerei Zimmermann')},
  {'name': 'Merzenich', 'area': 'Shopping streets', 'type': 'Bakery', 'price': '€', 'family': True, 'why': "Very busy bakery chain. Creators' seasonal hit was a nougat pretzel covered in almonds.", 'creators': ['wyattandreyka', 'grownupgapyear'], 'url': maps('Merzenich Bäckerei')},
  {'name': 'Chocolate Museum café', 'area': 'Rheinauhafen', 'type': 'Café', 'price': '€€', 'family': True, 'why': "A latte with a cup of molten chocolate on the side, overlooking the Rhine.", 'creators': ['travellerjames'], 'url': maps('Schokoladenmuseum')},
  {'name': 'Sticky Fingers', 'area': 'Deutz riverside', 'type': 'Burgers', 'price': '€€', 'family': True, 'why': "Riverside burgers and fries on the Deutz bank - an easy family meal after the bridge walk.", 'creators': ['robonholiday'], 'url': maps('Sticky Fingers Deutz')},
 ],
 'grown_ups': "For a grown-ups' evening, do a brewhouse crawl: Früh, Gaffel, Sion and Peters are all within a few minutes of each other. Put your beer mat on the glass to stop the refills, and clink on the thick base, not the rim. Drunktopus found Papa Joes Bierschänke a quirky Wild-West beer salon; he suggests skipping the standing-room crush at the busiest bars. The Belgian Quarter and Ehrenfeld are where locals drink - bars, galleries and live music - but the Ringe and Zülpicher Straße get rowdy late on weekends.",
 'hotels': [
  {'name': 'Excelsior Hotel Ernst', 'area': 'Opposite the cathedral', 'for': 'Luxury', 'band': '€€€€', 'why': 'Five-star grand hotel in the shadow of the cathedral spires, a minute from the market and station.', 'url': book('Excelsior Hotel Ernst'), 'source': 'wikipeaks'},
  {'name': 'Eden Hotel Früh am Dom', 'area': 'By the cathedral market', 'for': 'Families at the markets', 'band': '€€€', 'why': "The Karacsonyi Family stayed right beside the market and the cathedral and found it handy for breaks with the children between market visits (2025).", 'url': book('Eden Hotel Früh am Dom'), 'source': 'thekaracsonyif'},
  {'name': 'Hyatt Regency Cologne', 'area': 'Deutz', 'for': 'Families & views', 'band': '€€€€', 'why': "East-bank hotel whose best rooms look across to the cathedral. Hylo Abroad's boys loved the pool and the Nutella machine at breakfast (2025).", 'url': book('Hyatt Regency Köln'), 'source': 'hyloabroadtany'},
  {'name': 'Best Western Plus Hotel Cologne City', 'area': 'Near the Hauptbahnhof', 'for': 'Families', 'band': '€€', 'why': 'Larger rooms than usual, a huge breakfast and Lego in the restaurant for toddlers (Where Is Briggs, 2024).', 'url': book('Best Western Plus Hotel Cologne City'), 'source': 'whereisbriggs'},
  {'name': 'Motel One Köln-Altstadt', 'area': 'Altstadt edge', 'for': 'Solo & budget', 'band': '€€', 'why': "Modern and clean with a good bar, about 10 minutes' walk from the Old Town; Walshy's Travels paid €88 a night (2026).", 'url': book('Motel One Köln-Altstadt'), 'source': 'walshystravels'},
  {'name': '25hours Hotel The Circle', 'area': 'Friesenplatz (Ringe)', 'for': 'Couples & design', 'band': '€€€', 'why': "Design hotel in a converted post-war rotunda, walkable to several markets; Flora and Note liked the separate blankets and free minibar (2025). It's on the Ringe, so expect weekend nightlife outside.", 'url': book('25hours Hotel The Circle'), 'source': 'floraandnote'},
 ],
 'itinerary': {
  '1day': [
   ['09:30', 'Cathedral first', 'Go in as it opens at 10:00 (ticketed since July 2026) or climb the tower before the tour groups.'],
   ['11:00', 'Cathedral market at opening', 'The calmest it will be all day - then the little Advent market next door.'],
   ['12:30', 'Brewhouse lunch', 'Halve Hahn and a Kölsch at Früh or Gaffel am Dom.'],
   ['14:00', 'Altstadt & Heinzels', 'Down to Alter Markt and Heumarkt: the Christmas post office, the ice rink and Reibekuchen.'],
   ['15:30', 'Hohenzollern Bridge', 'Cross to Deutz for the view back as the light goes (sunset is about 16:30 in December).'],
   ['17:00', 'Markt der Engel & Nikolausdorf', 'The angels at Neumarkt, then the St Nicholas village at Rudolfplatz - lovely lit up, but busy after 5pm.'],
   ['19:00', 'Dinner', 'Brauhaus Sion or Peters Brauhaus, then back along the lit main streets.'],
  ],
  '3day': [
   ['Day 1 · Cathedral & Altstadt', 'Cathedral and tower in the morning, the cathedral market at opening.', 'Brewhouse lunch, Rathaus carillon and Heinzels by daylight.', 'The Hohenzollern Bridge at dusk and dinner at Früh.'],
   ['Day 2 · Families & the Rhine', 'Chocolate Museum (book ahead), then the harbour market next door.', 'The Rhine promenade or a one-hour cruise.', "Markt der Engel and Nikolausdorf - Nikolausdorf's craft room and boot mugs are the children's favourite."],
   ['Day 3 · Views & neighbourhoods', "KölnTriangle for the view, then the zoo - or the cable car on an Advent weekend.", 'Belgian Quarter cafés and the Stadtgarten market.', 'Skating at Heinzels on the Heumarkt, or a day trip to Düsseldorf or Bonn instead.'],
  ],
 },
 'tips': [
  {'title': 'Sights by day, markets by night', 'text': "In December it's dark by about 4:30pm. Do the cathedral, bridge and museums first and save the markets for when the lights come on - but not too late on a weekend."},
  {'title': 'Go early in the season, and midweek', 'text': 'Creators who went in the first week, or on a Tuesday or Wednesday at opening time, had far more space. Weekend evenings are shoulder to shoulder.'},
  {'title': 'Wear grippy shoes', 'text': "Cobbles everywhere and wet December pavements. Comfortable, waterproof shoes matter more than smart ones, and a pushchair with big wheels helps."},
  {'title': 'Two or three days', 'text': 'One day covers the cathedral and a couple of markets; two or three lets you see them all without rushing and add the Chocolate Museum or a day trip.'},
  {'title': 'Plan for Christmas itself', 'text': 'Most markets close on 23 December, and shops close on 25, 26 and 27 December and 1 January. Heinzels on the Heumarkt and the harbour market stay open into January, but Heinzels rests on 24 and 25 December.'},
  {'title': 'Leave the car - and the penknife', 'text': "Car parks fill fast on market weekends, and knives are banned in the Ringe and Zülpicher Straße zones on weekend nights. The train drops you right at the cathedral."},
 ],
 'tips_intro': "Every tip here was checked against an official or trusted source (KVB, Deutsche Bahn, Kölner Dom, Stadt Köln, Polizei NRW, gov.uk and others) on the date shown. Rules and prices change, so tap the link to double-check before you travel.",
 'christmas': {
  'intro': "Cologne is one of the best places in Europe for Christmas markets because so many are close together: the cathedral market, Heinzels Wintermärchen, the Markt der Engel, Nikolausdorf and the harbour market are all walkable, each with its own theme and collectable mug. In 2026 most run from 16 November to 23 December. They are very popular - creators found them packed on weekend evenings - and police send plain-clothes officers after pickpockets. Pickpocketing across Cologne fell by 31% in 2025, but the city centre is still where most of it happens.",
  'markets': [
   {'name': 'Weihnachtsmarkt am Kölner Dom', 'area': 'Roncalliplatz, beside the cathedral', 'when': '16 Nov - 23 Dec 2026 · Sun-Wed 11:00-21:00, Thu-Fri to 22:00, Sat 10:00-22:00 · closed 22 Nov', 'why': "The famous one: over 140 red-roofed stalls under a canopy of lights, a giant Christmas tree against the cathedral, and more than 100 free stage events. Creators loved the setting and the ham rolls with sauerkraut, Reibekuchen and fresh pretzels, but several found it the most touristy and commercial, with higher prices. A mistletoe photo for charity was €2. Enter from the south side for the best view of tree and cathedral and a quieter way in.", 'family': True, 'price': 'Free entry · Glühwein about €5 + €4 mug deposit (2025)', 'crowds': "The busiest market, beside the station. Packed on a Thursday at 3pm and 'could barely move' on weekend evenings; already busy 30 minutes after opening on a Saturday. Go at 11am on a weekday.", 'creators': ['travellingpand', 'walkwithmetim', 'trailblazinpep', 'adventuresofma', 'specialspicetr', 'thelittlebaske', 'dwtravel', 'travelingexpat', 'portalspasspor'], 'url': 'https://www.koelnerweihnachtsmarkt.com'},
   {'name': 'Heinzels Wintermärchen', 'area': 'Alter Markt & Heumarkt, Altstadt', 'when': 'Alter Markt 23 Nov - 23 Dec 2026 · Heumarkt 23 Nov 2026 - 10 Jan 2027 (rest days 24-25 Dec) · daily 11:00-22:00', 'why': "Many creators' favourite, especially for food and families. It is themed on Cologne's legendary gnomes, the Heinzelmännchen, across two squares joined by a market street. The Alter Markt half is crafts, gifts and a Christmas pyramid. The Heumarkt half has an ice rink around the equestrian statue, curling lanes (book ahead - around €28 a group in 2023), a Ferris wheel, a carousel and a two-storey bar over the ice. Children can post a letter at the Christmas post office and get a reply. Try Flammlachs, Handbrot (€8 in 2025) and the raclette baguette.", 'family': True, 'price': 'Free entry · skating about €10 + skate deposit (2023)', 'crowds': "Calm at lunchtime on a weekday; 'Disneyland busy' in the evening and very hard with a pushchair. Toilets are hard to find in the evening crowd. Skate by day.", 'creators': ['thelittlebaske', 'thekaracsonyif', 'adventuresofma', 'sheruntheworld', 'travellingpand', 'worthytravels', 'missmina', 'walkwithmetim', 'paschatv', 'brickeyvlog', 'sophienadeau'], 'url': 'https://www.heinzels-wintermaerchen.de'},
   {'name': 'Markt der Engel', 'area': 'Neumarkt', 'when': '16 Nov - 23 Dec 2026 · Sun-Thu 11:00-21:00, Fri-Sat to 22:00 (Glühwein stalls an hour later) · closed 22 Nov', 'why': "The angels' market, one of Cologne's oldest, under a canopy of star lights with white chalet-style stalls. 'Angels' walk through and give children gold dust to blow away with a wish, and there is a carousel. Several creators called it the prettiest market. Try the cathedral-shaped waffle with cherries and cream (€7.50-8.50). A Käthe Wohlfahrt stall sells wooden crafts.", 'family': True, 'price': 'Free entry · waffle €7.50-8.50 (2022-25)', 'crowds': "Calmer mid-afternoon; very busy after 5pm and on Saturdays. Neumarkt is also a police CCTV hotspot, so keep valuables close.", 'creators': ['davemani', 'prowalktours', 'travellingpand', 'walkwithmetim', 'travelingexpat', 'missmina', 'raisingwildflo', 'dwtravel', 'worthytravels'], 'url': 'https://www.markt-der-engel.de'},
   {'name': 'Nikolausdorf (St Nicholas Village)', 'area': 'Rudolfplatz, by the Hahnentor gate', 'when': '16 Nov - 23 Dec 2026 · Sun-Thu 11:00-21:00, Fri-Sat to 22:00 · closed 22 Nov', 'why': "The children's pick: a storybook village of half-timbered stalls in front of a medieval city gate, with St Nicholas singing and handing out treats, a children's craft workshop, a carousel, a letter-writing house and Kinderpunsch in collectable boot-shaped mugs (they sell out early in the season). The organiser lists modern toilets and a baby-changing table.", 'family': True, 'price': 'Free entry · Kinderpunsch €4.50 + €3 mug (2025)', 'crowds': "Smaller and more relaxed than the centre. It's about 20 minutes' walk from the Altstadt, on the Ringe - lively late on weekend nights.", 'creators': ['eatseetv', 'hyloabroadtany', 'floraandnote', 'worthytravels', 'raisingwildflo', 'thelittlebaske', 'sophienadeau', 'prowalktours'], 'url': 'https://nikolausdorf.com'},
   {'name': 'Hafen-Weihnachtsmarkt (harbour market)', 'area': 'By the Chocolate Museum, Rheinauhafen', 'when': '13 Nov 2026 - 3 Jan 2027 · daily 11:00-21:00, Fri-Sat to 22:00', 'why': "A maritime-themed market in white tents on the waterfront, with a pirate-ship Glühwein bar, a small play area and a covered Ferris wheel over the Rhine (€9 per person in 2025). Families liked the ship and the hot chocolate; others found it smaller, less decorated and further out, and one creator would skip it. Pair it with the Chocolate Museum - but the museum closes at 6pm.", 'family': True, 'price': 'Free entry · Ferris wheel about €9 (2025)', 'crowds': "The least crowded of the big markets. It's about 2.5 km from the cathedral along an exposed, windy stretch of river - take the tram in bad weather.", 'creators': ['trailblazinpep', 'travelingexpat', 'hyloabroadtany', 'adventuresofma', 'travellingpand', 'thelittlebaske', 'portalspasspor'], 'url': 'https://www.schokoladenmuseum.de/news/hafenweihnachtsmarkt-am-schokoladenmuseum/'},
   {'name': 'Stadtgarten Christmas market', 'area': 'Stadtgarten, by the Belgian Quarter', 'when': '2026 dates not yet published · weekdays from 16:00, weekends from 12:00 in 2025', 'why': "A relaxed, local-feeling market in the city's oldest park, with about 90 rotating stalls, handmade jewellery and notebooks, a wider choice of drinks and lots of children. Reasonable prices. It's about 2 km from the cathedral through residential streets.", 'family': True, 'price': 'Free entry · bottle deposit €3 (2022)', 'crowds': 'Quieter and more local than the centre.', 'creators': ['thelittlebaske', 'viatravelers', 'sophienadeau', 'missmina'], 'url': 'https://www.weihnachtsmarkt-stadtgarten.de'},
   {'name': 'Heavenue', 'area': 'Friesenplatz', 'when': '16 Nov - 23 Dec 2026 · Mon-Thu 14:00-22:00, Fri to 23:00, Sat 12:00-23:00, Sun 12:00-22:00', 'why': "Cologne's queer-friendly Christmas market: neon, disco balls, flamingos, rainbow mugs and party music. Hylo Abroad's kids loved it; Traveling Expats recommend it after the traditional markets.", 'family': True, 'price': 'Free entry', 'crowds': 'Lively in the evening; it sits on the Ringe nightlife strip.', 'creators': ['hyloabroadtany', 'travelingexpat', 'worthytravels'], 'url': 'https://www.heavenue.de'},
   {'name': 'Smaller neighbourhood markets', 'area': 'Eigelstein, Chlodwigplatz, Ehrenfeld and next to the cathedral', 'when': 'Check locally', 'why': "A tiny market by the Eigelstein city gate has live music and its own mug; a small Advent market next to the cathedral market has a huge pyramid bar and cheaper bratwurst (€4.50 against €6 in 2024) but wood chips that defeat pushchairs. Worthy Travels says Ehrenfeld's small market is only worth it if you're determined to see them all.", 'family': True, 'price': 'Free entry', 'crowds': 'Generally quiet.', 'creators': ['sophienadeau', 'trailblazinpep', 'mathersonthema', 'worthytravels'], 'url': maps('Weihnachtsmarkt')},
  ],
  'sights': [
   {'name': "Letters to Santa at Heinzels", 'area': 'Heinzels Wintermärchen', 'when': 'During market hours', 'why': "Children can write a wish list at the Christmas post office and get a reply. Heinzels also has candy-cane moulding and a blacksmith who forges a horseshoe with your name (€20 for 10 letters in 2025).", 'family': True, 'price': 'Free to write · horseshoe €20 (2025)', 'crowds': 'Go in the daytime.', 'creators': ['adventuresofma', 'thekaracsonyif'], 'url': 'https://www.heinzels-wintermaerchen.de'},
   {'name': 'Skating and curling on the Heumarkt', 'area': 'Heinzels Wintermärchen', 'when': '23 Nov 2026 - 10 Jan 2027, daily 11:00-21:45 (from 31 Dec to 20:45); closed 24-25 Dec', 'why': "An open-air rink with long straights that loops around the equestrian statue under gnomes on ski lifts. Curling lanes book up for evenings, so reserve online. Fresh ice is slippery - Flora and Note found out.", 'family': True, 'price': 'Skating about €10 + deposit (2023) · curling about €28 a group (2023)', 'crowds': 'Skate in the daytime; evenings are packed.', 'creators': ['walkwithmetim', 'adventuresofma', 'sophienadeau', 'floraandnote', 'missmina'], 'url': 'https://www.heinzels-wintermaerchen.de/eislaufen/'},
   {'name': 'The cable car on Advent weekends', 'area': 'Zoo to Rheinpark', 'when': '28-29 Nov, 5-6, 12-13, 19-20 Dec 2026, 10:00-18:00', 'why': "The Rhine cable car reopens only on the four Advent weekends, with views of the lit-up city on the way back.", 'family': True, 'price': '€5.50 one way / €9.50 return (2026)', 'crowds': 'Queues at weekends.', 'creators': ['erensayar'], 'url': 'https://www.koelner-seilbahn.de'},
   {'name': 'The cathedral at night from Deutz', 'area': 'Hohenzollern Bridge', 'when': 'After dark', 'why': "Walk over the love-lock bridge to the Deutz bank for the lit-up cathedral across the Rhine - the photo every creator takes.", 'family': True, 'price': 'Free', 'crowds': 'The bridge closes to pedestrians on New Year\'s Eve evening.', 'creators': ['chadandclaire', 'travelingexpat', 'thetravelguard'], 'url': maps('Hohenzollernbrücke')},
   {'name': 'The cathedral at Christmas', 'area': 'Domplatte', 'when': 'Sightseeing Mon-Sat 10:00-17:45, Sun 13:30-16:30', 'why': "Sightseeing needs a ticket since July 2026 and stops during services, which change over Christmas - check the service calendar before planning a visit on 24-26 December. The tower is closed on 24, 25 and 31 December. NiteshOnTheGo found the cathedral almost empty at 9am on 24 December.", 'family': True, 'price': '€12 (children to 13 free)', 'crowds': 'Very busy on December afternoons.', 'creators': ['niteshonthego', 'seniorsolotrav'], 'url': 'https://www.koelner-dom.de'},
  ],
  'safety': [
   {'title': 'Crowds and timing', 'text': "The cathedral market and Heinzels are shoulder to shoulder on weekend evenings after 5pm. Tuesday or Wednesday at opening time is calmest, and the first week of the season is quieter. Enter the cathedral market from the south side and use the side nooks to get out of the crush.", 'creators': ['thelittlebaske', 'specialspicetr', 'travelingexpat', 'travellingpand']},
   {'title': 'Pickpockets: fewer, but still here', 'text': "Pickpocketing across Cologne fell 31% in 2025, but 41% of cases are in the city centre. In December 2024 plain-clothes officers caught several suspected pickpockets at the cathedral market and on the Alter Markt, going for jacket pockets and backpacks. Police advice: valuables split between closed inner pockets, only the cash you need, bags closed and in front.", 'creators': ['worthytravels']},
   {'title': 'Cash, deposits and coins', 'text': "Carry euros and a card: some stalls are cash only, others card only. Mug deposits were €3-4 in 2025. Market toilets cost about 50 cents to €1 and some need coins; department stores and cafés are the free fallback. Market cash machines charge high fees and can run out at weekends.", 'creators': ['thelittlebaske', 'worthytravels', 'anayandanayrai', 'adventuresofma']},
   {'title': 'Pushchairs and small children', 'text': "The cathedral market and Heinzels are hard work with a pushchair in the evening, and the Advent market has wood chips underfoot. Go by day with small children. Nikolausdorf and the harbour market are the easiest for families.", 'creators': ['mathersonthema', 'thekaracsonyif', 'raisingwildflo']},
   {'title': 'Have a lost-child plan', 'text': "Before you go in, agree a meeting point everyone can find - the big Christmas tree at the cathedral market, or the equestrian statue in the middle of the Heumarkt rink. A Wiley Fox QR wristband on each child means anyone who finds them can reach you straight away.", 'creators': []},
   {'title': 'After the markets close', 'text': "The markets shut at 21:00-22:00. The walk back through the Altstadt is well lit and busy. On Friday and Saturday nights the Ringe, Zülpicher Straße and Neumarkt get rowdy, and police treat Breslauer Platz and Ebertplatz as hotspots - use the cathedral-side station exit and take a taxi if you're staying out that way.", 'creators': []},
   {'title': "New Year's Eve", 'text': "In 2025/26 bangers were banned inside the Ringe, no fireworks at all were allowed near the cathedral, and the Hohenzollern Bridge and cathedral area closed from 18:30. Police recorded 274 offences in Cologne that night, down from 369. Plans for 2026/27 aren't out yet - check stadt-koeln.de in December.", 'creators': []},
  ],
  'plan': "In 2026 the cathedral market, Markt der Engel and Nikolausdorf run 16 November to 23 December (closed Sunday 22 November); Heinzels opens a week later on 23 November and its Heumarkt half runs to 10 January 2027; the harbour market runs 13 November to 3 January. Nothing much is open on 24-26 December. Book hotels early - creators found December prices about double, and Düsseldorf is a 30-minute train away if Cologne is full. Buy Chocolate Museum tickets online, and book curling at Heinzels well ahead.",
 },
 'map_intro': "Germany doesn't publish street-level crime data, so this map shows the markets and sights in this guide and the places Cologne police themselves list as crime hotspots with CCTV.",
 'map_pins': [
  {'n': 'Weihnachtsmarkt am Kölner Dom', 'lat': 50.9408, 'lng': 6.9580, 'kind': 'market', 'note': 'Roncalliplatz, 16 Nov - 23 Dec 2026. Meet at the big tree.'},
  {'n': 'Heinzels Wintermärchen (Alter Markt)', 'lat': 50.9383, 'lng': 6.9597, 'kind': 'market', 'note': 'Crafts and gifts, 23 Nov - 23 Dec 2026.'},
  {'n': 'Heinzels Wintermärchen (Heumarkt, ice rink)', 'lat': 50.9362, 'lng': 6.9610, 'kind': 'market', 'note': 'Ice rink, curling and Ferris wheel, 23 Nov 2026 - 10 Jan 2027.'},
  {'n': 'Markt der Engel (Neumarkt)', 'lat': 50.9357, 'lng': 6.9468, 'kind': 'market', 'note': 'Angels and star lights, 16 Nov - 23 Dec 2026. Neumarkt is a police CCTV hotspot.'},
  {'n': 'Nikolausdorf (Rudolfplatz)', 'lat': 50.9371, 'lng': 6.9385, 'kind': 'market', 'note': "The children's favourite, by the Hahnentor gate."},
  {'n': 'Hafen-Weihnachtsmarkt', 'lat': 50.9322, 'lng': 6.9642, 'kind': 'market', 'note': 'Harbour market by the Chocolate Museum, 13 Nov 2026 - 3 Jan 2027.'},
  {'n': 'Stadtgarten market', 'lat': 50.9434, 'lng': 6.9312, 'kind': 'market', 'note': 'Local park market; 2026 dates not yet published.'},
  {'n': 'Heavenue (Friesenplatz)', 'lat': 50.9403, 'lng': 6.9391, 'kind': 'market', 'note': 'Queer-friendly party market, 16 Nov - 23 Dec 2026.'},
  {'n': 'Cologne Cathedral', 'lat': 50.9413, 'lng': 6.9583, 'kind': 'sight', 'note': '€12 sightseeing ticket since July 2026.'},
  {'n': 'Hohenzollern Bridge', 'lat': 50.9413, 'lng': 6.9656, 'kind': 'sight', 'note': 'Walk over for the classic cathedral view.'},
  {'n': 'KölnTriangle', 'lat': 50.9412, 'lng': 6.9727, 'kind': 'sight', 'note': 'Viewing deck, €5.'},
  {'n': 'Cologne Zoo & cable car', 'lat': 50.9589, 'lng': 6.9734, 'kind': 'sight', 'note': 'Cable car on Advent weekends only.'},
  {'n': 'Dom / Hauptbahnhof', 'lat': 50.9427, 'lng': 6.9587, 'kind': 'caution', 'note': 'Police CCTV crime hotspot. Busy, pickpockets - use the cathedral-side exit.'},
  {'n': 'Breslauer Platz', 'lat': 50.9444, 'lng': 6.9612, 'kind': 'caution', 'note': "Station back entrance. Police CCTV crime hotspot - don't linger at night."},
  {'n': 'Ebertplatz', 'lat': 50.9491, 'lng': 6.9575, 'kind': 'caution', 'note': 'Police CCTV crime hotspot on the northern Ringe.'},
  {'n': 'Ringe & Zülpicher Straße', 'lat': 50.9328, 'lng': 6.9392, 'kind': 'caution', 'note': 'Nightlife strip; weapon ban zone 20:00-06:00 at weekends.'},
 ],
 'map': {'center': [6.953, 50.9385], 'zoom': 13.4},
 'creators': creators,
 'sources': sources,
}
# sanity: every creator key referenced exists
refs = set()
def walk(x):
    if isinstance(x, dict):
        for k, v in x.items():
            if k == 'creators' and isinstance(v, list): refs.update(v)
            elif k == 'source' and isinstance(v, str) and v.islower(): refs.add(v)
            else: walk(v)
    elif isinstance(x, list): [walk(i) for i in x]
walk({k: v for k, v in G.items() if k != 'creators'})
missing = sorted(r for r in refs if r not in creators)
print('creators', NC, 'videos', NV, 'missing keys:', missing)
json.dump(G, open(f'{D}/guide.json', 'w'), ensure_ascii=False, indent=1)
json.dump({'tips': tips}, open(f'{D}/tips.json', 'w'), ensure_ascii=False, indent=1)
