# Builds muc/guide.json for the Munich Christmas 2026 guide from researched content + creator DB export.
import json, re, collections, urllib.parse
D = '/home/claude/cityguide/muc'
api = json.load(open(f'{D}/api.json'))
_t = json.load(open(f'{D}/tips.json')); tips = _t['tips'] if isinstance(_t, dict) else _t
costs = json.load(open(f'{D}/costs.json'))
key = lambda n: re.sub(r'[^a-z0-9]', '', n.lower())[:14]
maps = lambda q: 'https://www.google.com/maps/search/?api=1&query=' + urllib.parse.quote(q + ' München')
book = lambda q: 'https://www.booking.com/searchresults.html?ss=' + urllib.parse.quote(q + ' München') + '&aid=YOUR_AID_HERE'

# creators + sources from the DB export (only videos that yielded facts)
srcs = {s['id']: s for s in api['sources']}
used, cnt = {}, collections.Counter()
for v in api['facts'].values():
    for f in v:
        used.setdefault(f['source_id'], f['creator']); cnt[f['creator']] += 1
creators = {}
for sid, name in used.items():
    creators.setdefault(key(name), {'name': name, 'url': srcs.get(sid, {}).get('url') or f'https://www.youtube.com/watch?v={sid[3:]}'})
sources = sorted([{'creator': used[sid], 'creator_url': creators[key(used[sid])]['url'], 'title': s['title'], 'url': s['url'], 'date': (s.get('published_at') or '')[:7]}
                  for sid, s in srcs.items() if sid in used], key=lambda x: x['creator'].lower())
NC, NV = len(creators), len(sources)

G = {
 'city': 'Munich', 'slug': 'munich', 'country': 'Germany', 'edition': 'Christmas 2026 edition', 'updated': '2026-09-30',
 'status': "Draft for Barry's approval", 'audience': 'Families and solo travellers',
 'tagline': 'The Wiley Fox guide to Munich for families and solo travellers',
 'cover_blurb': f'What {NC} travel creators actually say about Munich, checked against the 2025 police figures - a dozen Christmas markets from Marienplatz to the medieval market, where to stay, what to eat, and the few places police watch.',
 'banner_text': 'Official travel advice for 200+ countries, community reports, one-tap SOS, and QR wristbands so lost children and lost bags find their way back.',
 'safety': {
  'wf_rating': 4, 'wf_label': 'Low',
  'wf_summary': "Munich has the lowest recorded crime of Germany's big cities. Police recorded 5,798 offences per 100,000 residents in the city in 2025, down 2.7%, against 13,233 in Berlin and 10,567 in Hamburg on the police's own comparison, and the Eurostat table below puts it lowest of eight big German cities for theft and robbery. Pickpocketing fell 11% in 2025 and street robbery by more than half. Two things went the other way: violent crime reached a ten-year high (up 2%), and recorded rapes rose 23%, though police say three in four involved people who knew each other. The areas police focus on are the Hauptbahnhof and the streets south of it, the Alter Botanischer Garten and Stachus. This rating is for the city as a whole, not street by street: German police do not publish street-level crime data.",
  'creator_feeling': 4, 'creator_feeling_label': 'Safe and calm - but very crowded at Marienplatz',
  'creator_summary': "Creators consistently call Munich one of the safest big cities they have visited. Rok Goes Around says pickpocketing is much rarer than in other large European cities, Happy to Wander says you won't be in danger even near the station, and Oriana Findlay, visiting alone, found even the Hofbräuhaus female friendly. The U-Bahn and S-Bahn were described as clean and safe. The complaints are crowds - Chris and Sara said a Saturday at the Marienplatz market made Oktoberfest look like a walk in the park - fast cyclists, cold weather, and prices. A local (German Insider) and Stefano Ferro both describe the Hauptbahnhof area as the scruffiest and noisiest part of the city.",
  'data_note': "Figures are from the Munich police's Sicherheitsreport 2025 (published March 2026). The headline rate is for the City of Munich; all other counts cover the whole police area (city plus Landkreis München, about 1.86 million people). No street-level data is published. From 2025 the report uses Census 2022 population figures, so older rates are not directly comparable. Pickpocketing: 1,489 cases (down 10.6%, and less than half the 2016 level), with 340 on public transport (slightly up). Street robbery: 143 (down 59%). Violent crime: 5,133 (up 2%). Recorded offences in the Alter Botanischer Garten by the station fell 66% to 436 after alcohol, cannabis and knife bans from January 2025. Police say the Hauptbahnhof, a building site until well into the 2030s with about 450,000 people a day, still sees begging, street drinking and litter, but much less than a year earlier. Rates are per resident, so visitors and commuters push them up.",
  'data_months': ['2025-12', '2025-01'],
 },
 'official_crime': [
  {'number': '5,798', 'label': 'Recorded offences per 100,000 residents in 2025', 'desc': "City of Munich, down 2.7% on 2024. Police say Munich keeps 'the top spot' for safety among comparable big cities (Sicherheitsreport 2025)."},
  {'number': '-11%', 'label': 'Pickpocketing in 2025 (1,489 cases)', 'desc': 'Less than half the 2016 level. Street robbery fell 59% to 143 cases (Munich police area).'},
  {'number': '-66%', 'label': 'Offences in the Alter Botanischer Garten', 'desc': 'The park beside the Hauptbahnhof, after alcohol, cannabis and knife bans from January 2025: 436 offences, down from 1,284.'},
 ],
 'crime_source': {'name': 'Polizeipräsidium München, Sicherheitsreport 2025', 'citation': "City and police-area statistics for 2025 (published 20 March 2026), Munich police statements on the Christmas markets (November 2025), the City of Munich's knife-ban and alcohol-ban rules for the station area, and the city's New Year's Eve firework rules for 2025/26. No street-level data is published, and rates are per resident, not adjusted for visitors."},
 'credit_fallback': 'Source: Polizeipräsidium München / Stadt München',
 'app_ctas': [
  {'where': 'before_booking', 'text': "Germany doesn't publish street-level crime data, so before you book, check your hotel's street against the map in this guide and any community reports on Wiley Fox. Near the Hauptbahnhof, the north side (towards Karlstraße) is quieter than the streets south of the station.", 'url': 'https://www.thewileyfox.com'},
  {'where': 'families', 'text': 'Clip a Wiley Fox QR wristband on each child. If you get separated in the Marienplatz crowd, anyone who scans it can contact you straight away - no app needed on their side.', 'url': 'https://www.thewileyfox.com'},
  {'where': 'night', 'text': 'Walking back after the markets close? Save your hotel on Wiley Fox, stick to the lit main streets and keep SOS one tap away.', 'url': 'https://www.thewileyfox.com'},
  {'where': 'community', 'text': 'Found a cash-only stall, a closed tower or a street that felt wrong? Drop a community report on the map - it helps the next family.', 'url': 'https://www.thewileyfox.com'},
 ],
 'stats': [
  {'number': '20 Nov-24 Dec', 'label': 'Marienplatz Christkindlmarkt 2026', 'desc': 'Mon-Sat 10:00-21:00, Sun to 20:00, 24 Dec to 14:00; closed Sun 22 Nov (organiser, Sept 2026).'},
  {'number': '80%', 'label': 'Marienplatz stalls taking cards', 'desc': "The organiser's figure, some with a €1-10 minimum. Creators still found many stalls cash only, so carry both."},
  {'number': str(NC), 'label': f'Creators · {NV} videos', 'desc': 'Paraphrased and credited, cross-checked with police figures.'},
 ],
 'overview': [
  "Munich is a big city with a compact, walkable centre. From the Hauptbahnhof it's a 15-minute walk through the pedestrian zone past Karlsplatz (Stachus) to Marienplatz, the main square, with the Frauenkirche, the Viktualienmarkt food market and the Residenz palace all close by. The Englischer Garten, one of the world's biggest city parks, starts just north of the old town. Creators suggest two to three days, plus a day trip if you can.",
  "At Christmas the whole old town becomes one long market, from Karlsplatz to Marienplatz and the Rindermarkt, and there are a dozen more around it: a medieval market, a fairy-tale village in the Residenz courtyard for small children, a woodland market by the Chinese Tower, the pink LGBTQ+ market and the Tollwood winter festival on the Oktoberfest grounds. For families there are puppet shows, curling, an ice rink at Karlsplatz and the Deutsches Museum for wet days.",
  "For solo travellers Munich is the easiest big city in Germany: police figures are the lowest of the big cities and creators felt safe everywhere, including alone at night. The things to plan for are crowds at Marienplatz (worst on Saturdays and at the noon Glockenspiel), real cold, early darkness, and the scruffier streets around the Hauptbahnhof, where many of the cheaper hotels are.",
 ],
 'facts': {
  'Currency': "Euro (EUR) - most Marienplatz stalls now take cards, but many smaller stalls, bakeries and toilets want cash",
  'Language': 'German - English is widely spoken in the centre',
  'Time zone': 'Central European Time (UTC+1) - one hour ahead of the UK',
  'Plug': 'Type C and F, 230V - UK plugs need an adaptor',
  'Emergency': '110 police · 112 fire & ambulance · 116 117 out-of-hours doctor',
  'Entry': 'UK passport must be under 10 years old on arrival and valid 3+ months after you leave the Schengen area; visa-free for up to 90 days in any 180 (gov.uk, Sept 2026)',
  'Tipping': 'About 5-10%, or round up - tell the server the total you want to pay',
  'Best time': 'Late November to 23 December for the markets (weekday daytimes are calmest); spring and early autumn outside Oktoberfest for sightseeing',
 },
 'stay': [
  {'area': 'Altstadt (around Marienplatz)', 'for': ['First-timers', 'Christmas markets'], 'why': "The best base for a short trip: everything in the old town is 10-15 minutes' walk, and the Christmas market is on your doorstep. It's also the most expensive area - Travel Tips Group quotes about €150-200 a night for three stars and €250-300 for four (2025) - and it is packed around Marienplatz on December weekends.", 'creators': ['traveltipsgrou', 'happytowandert', 'misstourist', 'stefanoferro']},
  {'area': 'Near the Hauptbahnhof (Ludwigsvorstadt)', 'for': ['Budget', 'Arriving by train', 'Day trips'], 'why': "The cheapest hotels in the centre, 10 minutes' walk from the old town, with the airport S-Bahn and day-trip trains on the doorstep. Creators are split: Happy to Wander says you won't be in danger, while Stefano Ferro calls it the dodgiest, noisiest part of town and a local wouldn't live there with children. Police focus on the southern Bahnhofsviertel and the Alter Botanischer Garten, so choose a hotel on the north side or on the main road.", 'creators': ['happytowandert', 'stefanoferro', 'germaninsider', 'traveltipsgrou', 'ourtravelplace']},
  {'area': 'Lehel', 'for': ['Families', 'Quiet nights'], 'why': "Quiet, pretty and residential, between the old town and the Englischer Garten, and walkable to the Residenz and Marienplatz. Stefano Ferro recommends it for families; the catch is price and not much nightlife.", 'creators': ['stefanoferro', 'happytowandert']},
  {'area': 'Haidhausen', 'for': ['Families', 'Local feel'], 'why': "Across the Isar, quieter with a villagey feel, cafés and its own local Christmas market. A few minutes by S-Bahn from Marienplatz. Happy to Wander calls it a favourite and MissTourist says there's plenty for families.", 'creators': ['happytowandert', 'misstourist', 'seniortravelwo', 'nearfromhomesl']},
  {'area': 'Schwabing & Maxvorstadt', 'for': ['Solo travellers', 'Museums', 'Couples'], 'why': "The university and museum quarter north of the centre, running into leafy Schwabing by the Englischer Garten. Slightly cheaper, lively with cafés and student bars, and on the U3/U6 for the Schwabing and Chinese Tower markets.", 'creators': ['traveltipsgrou', 'rokgoesaround', 'seniortravelwo', 'misstourist']},
  {'area': 'Glockenbachviertel & Gärtnerplatz', 'for': ['Solo travellers', 'Nightlife'], 'why': "Trendy, LGBTQ+ friendly and lively at night, close to Pink Christmas and the Viktualienmarkt. A little cheaper than the Altstadt, but further from the S-Bahn and noisy at weekends.", 'creators': ['happytowandert', 'cityzen', 'stefanoferro']},
 ],
 'caution': [
  {'area': 'Hauptbahnhof & the southern Bahnhofsviertel', 'when': 'Evenings and night', 'note': "Munich's main station is a building site until well into the 2030s, with about 450,000 people passing through a day. Police say begging, street drinking, rough sleeping and litter are much less common than a year earlier, and their focus has moved to the streets south of the station (between Bayerstraße, Landwehrstraße and Sonnenstraße) and Nußbaumpark, where they now have camera towers. Drinking alcohol on the street around the station is banned. Creators found it scruffy rather than dangerous. Keep an eye on bags in the concourse, and use the main roads at night.", 'creators': ['stefanoferro', 'germaninsider', 'happytowandert']},
  {'area': 'Alter Botanischer Garten', 'when': 'After dark', 'note': "The small park between the station and Stachus was Munich's biggest trouble spot: 1,284 offences in 2024. After alcohol, cannabis, weapon and knife bans, better lighting and cameras from January 2025, offences fell 66% to 436. It's still not a shortcut to take late at night - walk round via Karlsplatz. Kai Travel found a lot of litter around the fountain.", 'creators': ['kaitravel']},
  {'area': 'Karlsplatz (Stachus)', 'when': 'Late evening', 'note': "The big square at the start of the pedestrian zone, home to the Eiszauber ice rink at Christmas. Police had complaints about loud groups of young people in 2024 and 2025 and now have a mobile camera tower as well as the fixed camera. Busy and well lit - just keep valuables close.", 'creators': ['greeceandbeyon', 'nearfromhomesl']},
  {'area': 'Marienplatz at the Glockenspiel and on Saturdays', 'when': '11:00 and 12:00 daily, and Saturday afternoons and evenings', 'note': "The square fills with a wall of phones for the Glockenspiel, and on December Saturdays the market is shoulder to shoulder. Police warn of pickpockets in crowds and queues, and have uniformed and plain-clothes patrols and cameras at Marienplatz and the pedestrian zone. Go early on a weekday, and step out to the Rindermarkt or Viktualienmarkt for space.", 'creators': ['woltersworld', 'chrisandsara', 'lifewithrachel', 'ourtravelplace', 'nearfromhomesl']},
  {'area': 'Bike lanes everywhere', 'when': 'Always', 'note': "The most common warning from creators. Munich's cyclists are fast and bike lanes blend into the pavement, often in a slightly different colour. Look both ways before stepping off the kerb and keep children out of the red lanes.", 'creators': ['woltersworld', 'amyzhong']},
  {'area': 'The Eisbach in the Englischer Garten', 'when': 'Any time', 'note': "Watch the river surfers from the bridge, but the water is fast and cold. Eva Meloche's group struggled to get out after swimming; keep children well back from the edge.", 'creators': ['evameloche', 'mytravelbf']},
 ],
 'scams': [
  {'title': 'Plain-clothes ticket inspectors', 'text': "Not a scam: MVV inspectors ride in normal clothes and show ID on board. Tickets must be validated (stamped) as well as bought, or you pay €60. Apps validate automatically.", 'creators': ['happytowandert', 'rokgoesaround', 'woltersworld']},
  {'title': 'Pickpockets in the crowd', 'text': "Munich police warn that thefts happen 'again and again' in Christmas-market crowds. Keep valuables in inner pockets, bags closed and in front, and be careful in queues; ring 110 if you see something.", 'creators': ['deanaandphil']},
  {'title': 'Deposits on everything', 'text': "Mugs carry a Pfand, usually €5 in 2025, and plates €1. The medieval market charges €10-15 for its clay goblets, so a €8 drink costs €23 up front - you get it back when you return it.", 'creators': ['chrisandsara', 'eastwestwander', 'woltersworld']},
  {'title': 'Taxis from the airport', 'text': "About Munich says taxi scams are almost non-existent, but €100 or more from the airport is normal. The S-Bahn (S1/S8) with an Airport-City-Day-Ticket is far cheaper.", 'creators': ['aboutmunich']},
 ],
 'transport': [
  {'title': 'From the airport', 'text': "The S1 and S8 run alternately, about every 10 minutes between them, taking around 40 minutes to the Hauptbahnhof (a bit less to Marienplatz on the S8). The Airport-City-Day-Ticket is €17.50 for one or €32.60 for a group of up to five (2026) and covers the rest of the day in the city. Don't board the occasional regional train to Regensburg. The Lufthansa Express bus is €13.", 'creators': ['aboutmunich', 'robonholiday']},
  {'title': 'Tickets and fines', 'text': "A Zone M single is €4.20, a day ticket €10.10 and a group day ticket for up to five €19.70 (2026); day tickets run to 6am the next morning. Stamp paper tickets before you travel - there are no barriers, inspectors wear normal clothes, and the fine is €60. MVV Swipe in the MVGO app works out the cheapest fare for you. Zone M day tickets rise to €10.80 on 1 January 2027.", 'creators': ['robonholiday', 'happytowandert', 'aboutmunich', 'anishakg']},
  {'title': 'Walking the markets', 'text': "The main market runs through the pedestrian zone from Karlsplatz to Marienplatz and the Rindermarkt; the Residenz and medieval markets are 5-10 minutes north. Take the U3/U6 to Universität for the Chinese Tower or Münchner Freiheit for Schwabing, and U4/U5 to Theresienwiese for Tollwood.", 'creators': ['happytowandert', 'nearfromhomesl', 'lifewithrachel']},
  {'title': 'Night travel', 'text': "Public transport runs roughly 4am to 1am, with U-Bahn trains all night on Fridays, Saturdays and before holidays and night trams from about 1:30am (Rok Goes Around, 2023).", 'creators': ['rokgoesaround']},
  {'title': 'Day trips by train', 'text': "The Bayern-Ticket (€34 for one, €44 for two, up to five people plus children) covers regional trains across Bavaria for a day. Nuremberg's market is about an hour by ICE, Salzburg about 1h30-1h40. For Neuschwanstein, book the timed castle tour online (€21 + €2.50 fee): in winter the Marienbrücke viewpoint is often closed, paths are icy and it's dark by about 4:20pm.", 'creators': ['robonholiday', 'woltersworld', 'travelsofsarah', 'meghanelise']},
 ],
 'costs': costs,
 'top_intro': "Ranked by how often creators recommend them. Most are within a 15-minute walk of Marienplatz; in December, see the sights by daylight and save the markets for the evening.",
 'top': [
  {'name': 'Marienplatz & the Glockenspiel', 'area': 'Altstadt', 'why': "The main square under the neo-Gothic Neues Rathaus. Its Glockenspiel plays at 11:00 and 12:00 in winter - some creators call it underwhelming, but children love it. The Rathaus tower has a lift to a viewing platform, and the courtyard is free.", 'family': True, 'price': 'Free', 'url': maps('Marienplatz'), 'creators': ['robonholiday', 'adventuresofma', 'woltersworld', 'mytravelbf', 'whereisbriggs', 'amyzhong', 'chiphammontree']},
  {'name': "St Peter's tower (Alter Peter)", 'area': 'Altstadt', 'why': "306 steps up a narrow two-way stair for the best view of the Christmas market and, on clear days, the Alps. The Little Basket suggests going just before sunset. A squeeze with small children. Closes at 14:00 on 24 and 31 December.", 'family': True, 'price': '€5 · 6-18 €2 · under 6 free (2026)', 'url': 'https://www.alterpeter.de', 'creators': ['heresgood', 'thelittlebaske', 'adventuresofak', 'johleneorton', 'maxandsidney', 'rokgoesaround']},
  {'name': 'Viktualienmarkt', 'area': 'Altstadt', 'why': "Munich's food market since 1807, with about 140 stalls, a beer garden and extra Christmas chalets in December. Much calmer than Marienplatz; a Leberkäse or Krustenbraten roll is €3-5, and there are free water fountains. Closed Sundays and holidays.", 'family': True, 'price': 'Free to browse', 'url': maps('Viktualienmarkt'), 'creators': ['heresgood', 'sophienadeau', 'fatihanlatyor', 'locavoreeats', 'mytravelbf', 'asenseoftravel', 'chrisandsara']},
  {'name': 'Englischer Garten & the Eisbach surfers', 'area': 'Englischer Garten', 'why': "A huge city park with river surfers riding a standing wave by the Haus der Kunst - the wave was reopened in May 2026 - and the Chinese Tower, which hosts a woodland Christmas market. In winter most beer gardens are shut.", 'family': True, 'price': 'Free', 'url': maps('Eisbachwelle'), 'creators': ['mytravelbf', 'bayernreisetip', 'orianafindlay', 'kaitravel', 'vacayin1day', 'adventuresofma']},
  {'name': 'Residenz', 'area': 'Altstadt', 'why': "The Bavarian royal palace: 130 rooms and the Antiquarium hall, with a free audio guide; allow 2-3 hours. Big bags go in the free cloakroom. The queue at the main desk can be long at weekends - Valeska bought the same ticket at the Cuvilliés Theatre instead. Closed 24, 25 and 31 Dec and 1 Jan.", 'family': True, 'price': '€10 · with treasury €15 · under 18 free (2026)', 'url': 'https://www.residenz-muenchen.de', 'creators': ['robonholiday', 'jmbanquicio', 'rokgoesaround', 'valeska', 'ourtravelplace', 'johleneorton']},
  {'name': 'Frauenkirche', 'area': 'Altstadt', 'why': "The twin-domed cathedral, free to enter and fairly plain inside. The south tower has 89 steps and then a lift, the easiest high viewpoint in the old town.", 'family': True, 'price': 'Church free · tower from €7.50 (2026)', 'url': maps('Frauenkirche'), 'creators': ['robonholiday', 'noahanderson', 'rokgoesaround']},
  {'name': 'Deutsches Museum', 'area': 'Museum island, Isarvorstadt', 'why': "One of the world's biggest science and technology museums, full of interactive exhibits - the best wet-day option for families. Closed 24-25 Dec and 31 Dec-1 Jan.", 'family': True, 'price': '€16 · 6-17 €9 · family €33 (2026)', 'url': 'https://www.deutsches-museum.de', 'creators': ['amyzhong', 'alicelucastrav']},
  {'name': 'Schloss Nymphenburg', 'area': 'Neuhausen-Nymphenburg', 'why': "The summer palace and its huge free park, 15-20 minutes on tram 17 from the Hauptbahnhof. Allow half a day.", 'family': True, 'price': 'Palace about €10 · gardens free (2025)', 'url': maps('Schloss Nymphenburg'), 'creators': ['robonholiday', 'ourtravelplace', 'asenseoftravel', 'rokgoesaround']},
  {'name': 'Hofbräuhaus', 'area': 'Altstadt', 'why': "The famous beer hall: touristy, loud and chaotic, with a painted ceiling, brass band and litre glasses. Over 1,000 seats, so you'll usually find a place on the communal benches. Oriana Findlay found it fine alone; don't try to take a stein home.", 'family': False, 'price': 'Litre of beer about €10 (2025)', 'url': maps('Hofbräuhaus'), 'creators': ['mytravelbf', 'hikinukiworldt', 'orianafindlay', 'naickkim', 'woltersworld', 'mathersonthema']},
  {'name': 'Tierpark Hellabrunn', 'area': 'Thalkirchen', 'why': "Munich's zoo, by the Isar, with plenty for children and restaurants on site - worth it on a dry winter day if you wrap up.", 'family': True, 'price': '€24 · child €10 (from 1 Oct 2026)', 'url': 'https://www.hellabrunn.de', 'creators': ['germaninsider']},
 ],
 'eat_label': 'Weisswurst, Schmalznudel and a Mass',
 'eat_intro': "Munich eats big: pork knuckle and dumplings in beer halls, Weisswurst before noon, and fried dough for breakfast. Every place is credited to the creator who recommended it, and prices carry the year.",
 'eat': [
  {'name': 'Café Frischhut', 'area': 'By the Viktualienmarkt', 'type': 'Schmalznudel café', 'price': '€', 'family': True, 'why': "Tiny café that only fries Schmalznudel - warm, crisp sugared dough, €3.20 each (2025). Cash only; the queue was out of the door on a Monday late morning.", 'creators': ['mytravelbf', 'chrisandsara', 'holoholotravel', 'locavoreeats', 'adventuresofma'], 'url': maps('Café Frischhut')},
  {'name': 'Viktualienmarkt stalls', 'area': 'Altstadt', 'type': 'Market food', 'price': '€', 'family': True, 'why': "Weisswurst with sweet mustard and a pretzel (before noon - peel the skin), Leberkäse rolls and soup in winter, €3-5 a snack (2025).", 'creators': ['asenseoftravel', 'chrisandsara', 'dwtravel', 'orianafindlay'], 'url': maps('Viktualienmarkt')},
  {'name': 'Schneider Bräuhaus', 'area': 'Altstadt', 'type': 'Beer hall', 'price': '€€', 'family': True, 'why': "Classic wheat-beer hall for a Weisswurst breakfast; Mathers On The Map preferred it to the Hofbräuhaus with their children.", 'creators': ['locavoreeats', 'mathersonthema'], 'url': maps('Schneider Bräuhaus')},
  {'name': 'Augustiner Klosterwirt', 'area': 'By the Frauenkirche', 'type': 'Bavarian', 'price': '€€', 'family': True, 'why': "Lively inn opposite the Frauenkirche: a pork knuckle big enough for two or three, and Schweinebraten with dumplings. Expect a queue.", 'creators': ['adventuresofma', 'hikinukiworldt'], 'url': maps('Augustiner Klosterwirt')},
  {'name': 'Andechser am Markt', 'area': 'Viktualienmarkt', 'type': 'Bavarian', 'price': '€€', 'family': True, 'why': "Very busy and loud with a wait for a table, but huge portions and a praised schnitzel (2026).", 'creators': ['hikinukiworldt'], 'url': maps('Andechser am Markt')},
  {'name': 'Wirtshaus in der Au', 'area': 'Au', 'type': 'Bavarian', 'price': '€€', 'family': True, 'why': "Across the Isar, known for its dumplings and roast duck. Popular - book ahead.", 'creators': ['ourtravelplace', 'locavoreeats'], 'url': maps('Wirtshaus in der Au')},
  {'name': 'Atzinger', 'area': 'Maxvorstadt', 'type': 'Student inn', 'price': '€', 'family': True, 'why': "Less touristy local inn; a schnitzel lunch was €10 in 2025, and lunch deals are common across Munich.", 'creators': ['naickkim'], 'url': maps('Atzinger')},
  {'name': 'Augustiner-Keller', 'area': 'Near the Hauptbahnhof', 'type': 'Beer cellar', 'price': '€€', 'family': True, 'why': "Huge beer hall and garden; Haxe and a litre of beer came to €26.50 in 2025.", 'creators': ['kaitravel'], 'url': maps('Augustiner-Keller')},
  {'name': 'Café Kaiserschmarrn', 'area': 'Altstadt', 'type': 'Café', 'price': '€€', 'family': True, 'why': "Kaiserschmarrn - torn, sugared pancake - to share, some of it served in cosy cable-car-style huts.", 'creators': ['johleneorton', 'theurbanjungle'], 'url': maps('Café Kaiserschmarrn')},
  {'name': 'Dallmayr', 'area': 'By Marienplatz', 'type': 'Delicatessen', 'price': '€€€', 'family': False, 'why': "Munich's grand food hall. Johlene Orton's Christmas set lunch in the café-bistro was €35 (2025).", 'creators': ['orianafindlay', 'johleneorton'], 'url': maps('Dallmayr')},
  {'name': 'Hofbräukeller', 'area': 'Haidhausen (Wiener Platz)', 'type': 'Beer hall', 'price': '€€', 'family': True, 'why': "Far more local than the Hofbräuhaus; Near From Home's favourite, with pork Haxe and dumplings.", 'creators': ['nearfromhomesl', 'theurbanjungle'], 'url': maps('Hofbräukeller')},
  {'name': 'Bodhi', 'area': 'Near Theresienwiese', 'type': 'Vegan Bavarian', 'price': '€€', 'family': True, 'why': "Relaxed vegan restaurant with vegan Käsespätzle and schnitzel - handy before Tollwood.", 'creators': ['theurbanjungle'], 'url': maps('Bodhi vegan')},
 ],
 'grown_ups': "For a grown-ups' night: a Mass (a full litre) at the Hofbräuhaus for the spectacle, then somewhere more local - Schneider Bräuhaus, the Augustiner halls or the Hofbräukeller across the river. Beer-hall beer is strong, so pace yourself. Glockenbach and Gärtnerplatz are the bar districts, and Pink Christmas has a DJ until 10pm. Spirits need ID: the drinking age is 16 for beer and wine and 18 for spirits.",
 'hotels': [
  {'name': 'Hotel Bayerischer Hof', 'area': 'Altstadt (Promenadeplatz)', 'for': 'Luxury', 'band': '€€€€', 'why': 'Grand old-town hotel a few minutes from Marienplatz and the markets. Not creator-reviewed: a Wiley Fox pick for location.', 'url': book('Hotel Bayerischer Hof'), 'source': ''},
  {'name': 'Andaz Munich Schwabinger Tor', 'area': 'Schwabing', 'for': 'Couples & comfort', 'band': '€€€€', 'why': "Five-star with a spa and rooftop pool; Oriana Findlay liked the café downstairs (2024). On the U6 to the centre.", 'url': book('Andaz Munich Schwabinger Tor'), 'source': 'orianafindlay'},
  {'name': 'Euro Youth Hostel', 'area': 'Near the Hauptbahnhof', 'for': 'Solo & budget', 'band': '€', 'why': "A solo creator found it felt more like a hotel: very clean, dorms and private rooms, great breakfast and location (2024).", 'url': book('Euro Youth Hostel'), 'source': 'vishakhandelwa'},
  {'name': 'Best Western Hotel Arabella Park', 'area': 'Bogenhausen', 'for': 'Families with a car', 'band': '€€', 'why': "Where Is Briggs, with little children, found clean, spacious modern rooms, a big breakfast and parking (2025). Further out, on the U4.", 'url': book('Best Western Hotel Arabella Park'), 'source': 'whereisbriggs'},
 ],
 'itinerary': {
  '1day': [
   ['09:00', 'Viktualienmarkt breakfast', 'Weisswurst and a pretzel, or a Schmalznudel at Café Frischhut.'],
   ['10:00', 'Christkindlmarkt at opening', 'Marienplatz and the Kripperlmarkt nativity stalls before the crowds.'],
   ['11:00', 'Glockenspiel & Alter Peter', 'Watch the 11:00 show from the edge of the square, then climb the tower.'],
   ['12:30', 'Lunch', 'A Bavarian lunch deal at Augustiner Klosterwirt or the Viktualienmarkt.'],
   ['14:00', 'Residenz Christmas village', 'The fairy-tale forest and puppet shows in the palace courtyard, then the medieval market next door.'],
   ['16:00', 'Rindermarkt & Sendlinger Tor', 'The quieter end of the market as the lights come on (sunset about 16:20).'],
   ['18:30', 'Dinner', 'Pink Christmas for a drink, or dumplings at Wirtshaus in der Au.'],
  ],
  '3day': [
   ['Day 1 · Old town', 'Viktualienmarkt and the Christkindlmarkt at opening.', 'Alter Peter, the Frauenkirche and the Residenz.', 'Medieval market after dark and dinner in a beer hall.'],
   ['Day 2 · Families & museums', 'Deutsches Museum (or the zoo on a dry day).', 'Residenz Christmas village and the Eiszauber rink at Karlsplatz.', 'Tollwood on the Theresienwiese - big covered tents if it rains.'],
   ['Day 3 · Parks & neighbourhoods', 'Englischer Garten: the Eisbach surfers and the Chinese Tower market.', 'Schwabing market or Nymphenburg by tram 17.', 'Haidhausen market and dinner at the Hofbräukeller - or a day trip to Nuremberg or Salzburg instead.'],
  ],
 },
 'tips': [
  {'title': 'Sights by day, markets by night', 'text': "In December it's dark by about 4:20pm. Do the towers, museums and park first and save the markets for when the lights come on."},
  {'title': 'Pack for real cold', 'text': "Creators saw freezing rain, 44 cm of snow and feels-like temperatures of -16°C in early December. Market stalls have no heaters - layers, gloves and grippy shoes."},
  {'title': 'Book dinner', 'text': 'Restaurants were booked out even on a December Wednesday. Reserve for evenings, or make lunch your main meal - many places have cheaper lunch menus.'},
  {'title': 'Sundays and holidays', 'text': "Shops close on Sundays and on 25, 26 December and 1 January; the Viktualienmarkt is closed Sundays and holidays. The markets and museums stay open on Sundays (state museums are €1 on Sundays, most closed on Mondays)."},
  {'title': 'Plan for Christmas itself', 'text': 'Most markets end on 20-23 December. Only Marienplatz and Schwabing open on 24 December, until 14:00. The Residenz, Deutsches Museum and Neuschwanstein are closed on 24-25 December.'},
  {'title': 'Keep out of the bike lanes', 'text': "Munich's cyclists are fast and the lanes blend into the pavement. Look both ways before stepping off the kerb, especially with children."},
 ],
 'tips_intro': "Every tip here was checked against an official or trusted source (MVV, Munich police, muenchen.de, Deutsche Bahn, gov.uk and others) on the date shown. Rules and prices change, so tap the link to double-check before you travel.",
 'christmas': {
  'intro': "Munich's Christmas market season is one of Germany's biggest: the old Christkindlmarkt on Marienplatz, traced back to 1642, spreads down the pedestrian zone, and a dozen themed markets surround it - medieval, fairy-tale, woodland, pink and the Tollwood winter festival. In 2026 Marienplatz runs from 20 November to 24 December. It is very crowded at weekends, but Munich has the lowest recorded crime of Germany's big cities, and police run uniformed and plain-clothes patrols and cameras across the markets.",
  'markets': [
   {'name': 'Münchner Christkindlmarkt', 'area': 'Marienplatz and the pedestrian zone', 'when': '20 Nov - 24 Dec 2026 · Mon-Sat 10:00-21:00, Sun 10:00-20:00, 24 Dec 10:00-14:00 · closed 22 Nov', 'why': "The original: over 130 stalls in front of the Neues Rathaus under a 25-30 m tree, running on through the pedestrian streets. Stalls sell ornaments, Lebkuchen and stollen; creators liked the bratwurst, Flammlachs (flame-grilled salmon in a roll, €9 in 2024 - long queue), apple fritters and Quarkbällchen. Advent music plays from the Rathaus balcony most evenings from 17:15. Several creators found it traditional rather than special, and pricier than a few streets away.", 'family': True, 'price': 'Free entry · Glühwein €4-7.50 + €5 mug deposit (2025)', 'crowds': "The busiest market in the city - 'made Oktoberfest look like a walk in the park' on a Saturday. Fairly packed an hour after opening even on a Tuesday. Go early afternoon on a weekday; Rindermarkt and the Viktualienmarkt give breathing room.", 'creators': ['chrisandsara', 'lifewithrachel', 'sophienadeau', 'heresgood', 'boozingabroads', 'andrewkait', 'adventuresofak', 'nearfromhomesl', 'walkingaroundc', 'eastwestwander'], 'url': 'https://www.christkindlmarkt-muenchen.de'},
   {'name': 'Kripperlmarkt & Rindermarkt', 'area': 'By Alter Peter and the Rindermarkt', 'when': '20 Nov - 24 Dec 2026 (with the main market)', 'why': "A street of stalls selling Bavarian nativity scenes and figures, from affordable to very expensive, next to a 12 m Christmas windmill. The Rindermarkt stalls, a couple of minutes from Marienplatz, are built like little houses around a giant pyramid, with Kirschwein in boot-shaped mugs and a Krampus run in early December.", 'family': True, 'price': 'Free entry', 'crowds': 'Noticeably quieter than Marienplatz - a good after-work spot.', 'creators': ['chrisandsara', 'anywayyoutrave', 'sophienadeau', 'walkingaroundc', 'mathersonthema', 'fatihanlatyor'], 'url': 'https://www.christkindlmarkt-muenchen.de'},
   {'name': 'Weihnachtsdorf im Kaiserhof der Residenz', 'area': 'Residenz courtyard, off Odeonsplatz', 'when': '16 Nov - 22 Dec 2026 · daily 11:00-21:00 (22 Dec to 20:00) · closed 22 Nov', 'why': "The small-children's favourite: a Christmas village in the palace courtyard with a free fairy-tale forest, Hansel-and-Gretel scenes, animatronic displays and a corner where puppets tell Christmas stories. Good food, Käsespätzle and Kinderpunsch. Glühwein was €10 including a €5 mug deposit in 2025.", 'family': True, 'price': 'Free entry · Glühwein €5 + €5 deposit (2025)', 'crowds': "Calm and quiet by day with tables to sit at; packed at dinner time, and there can be a queue to get in at weekends.", 'creators': ['andrewkait', 'chasingcharism', 'fatihanlatyor', 'adventuresofak', 'lifewithrachel', 'mathersonthema', 'lazyleytravels', 'eastwestwander', 'thelittlebaske'], 'url': 'https://www.dasweihnachtsdorf.de'},
   {'name': 'Medieval Christmas market (Mittelaltermarkt)', 'area': 'Wittelsbacherplatz', 'when': '20 Nov - 23 Dec 2026 · daily 11:00-21:00 · closed 22 Nov', 'why': "Straw floors, torches, open fires and costumed stallholders, with blacksmiths, acrobats at weekends, roast pig, flame-grilled salmon, mead and flaming Feuerzangenbowle in clay goblets. Sophie Nadeau rated it the best food of Munich's markets. Also the most expensive: goblet deposits are €10-15.", 'family': True, 'price': 'Free entry · drink about €8 + €10-15 goblet deposit (2025), cash only', 'crowds': 'Best after dark, when it gets busy with live music.', 'creators': ['sophienadeau', 'boozingabroads', 'chrisandsara', 'eastwestwander', 'lifewithrachel', 'ciaoimciao', 'lazyleytravels', 'mathersonthema', 'adventuresofak'], 'url': 'https://www.mittelaltermarkt-muenchen.de'},
   {'name': 'Christkindlmarkt am Chinesischen Turm', 'area': 'Englischer Garten', 'when': '19 Nov - 23 Dec 2026, Wed-Sun only · 11:00/11:30-20:30', 'why': "A woodland village around the wooden Chinese Tower, with a live band, good food and Eisstockschießen (Bavarian curling) that children love - and snowball fights on the meadows if it snows. Near From Home calls it probably the most kid-friendly market.", 'family': True, 'price': 'Free entry', 'crowds': "Local and relaxed - noticeably quieter than the Residenz. A walk through the park from Universität U-Bahn.", 'creators': ['nearfromhomesl', 'sophienadeau', 'bayernreisetip', 'happytowandert', 'adventuresofak'], 'url': 'https://weihnachtsmarkt-chinaturm.de'},
   {'name': 'Pink Christmas', 'area': 'Stephansplatz, Glockenbachviertel', 'when': '20 Nov - 20 Dec 2026 · Mon-Fri 16:00-22:00, Sat-Sun 14:00-22:00', 'why': "Germany's first pink Christmas market (about 20 years old): pink lights, disco balls, rainbow mugs, a DJ and evening acts, and plenty of vegan food. Warm and welcoming, allies included. Some drinks raise money for the Munich AIDS charity.", 'family': True, 'price': 'Free entry · Glühwein €6 (2023)', 'crowds': 'Best after dark; busier later in the evening.', 'creators': ['sturmwaffel', 'fatihanlatyor', 'sophienadeau', 'happytowandert', 'travelsofsarah'], 'url': 'https://www.pink-christmas.de'},
   {'name': 'Tollwood Winter Festival', 'area': 'Theresienwiese (Oktoberfest grounds)', 'when': '24 Nov - 23 Dec 2026 · weekdays from 14:00, weekends from 11:00, to 22:30-23:30', 'why': "A fair-trade and world-food festival in big heated tents on the Oktoberfest meadow, with art installations, live music and a circus (ticketed). Locals love it; some creators found it less Christmassy and very busy. Andrew & Kait had the best-value Glühwein of the day here. Closed 24-30 Dec.", 'family': True, 'price': 'Free entry (circus ticketed)', 'crowds': "Can be 'exceptionally crowded' in the evening, with queues for tent shows; the covered tents are a lifesaver in rain.", 'creators': ['andrewkait', 'sophienadeau', 'eastwestwander', 'travelsofsarah', 'memoryseekers', 'nearfromhomesl', 'lifewithrachel'], 'url': 'https://www.tollwood.de'},
   {'name': 'Sendlinger Tor & Schwabing', 'area': 'Sendlinger Tor gate; Münchner Freiheit', 'when': 'Sendlinger Tor 20 Nov - 22 Dec 2026 · Schwabing 25 Nov - 24 Dec 2026 (24 Dec to 14:00)', 'why': "Two smaller local markets. Sendlinger Tor has about 20 stalls under the old city gate - Boozing Abroad's favourite for its local feel and cheese-filled sausage, 'just okay' for Happy to Wander. Schwabing, in its 50th year, showcases local artists and craftspeople.", 'family': True, 'price': 'Free entry', 'crowds': 'Uncrowded.', 'creators': ['boozingabroads', 'happytowandert', 'sophienadeau', 'andrewkait', 'mathersonthema'], 'url': 'https://www.schwabingerweihnachtsmarkt.de'},
   {'name': 'Haidhausen Christmas market', 'area': 'Weißenburger Platz, Haidhausen', 'when': '2026 dates not yet published (2025: 24 Nov - 23 Dec, 11:00-21:00)', 'why': "A traditional local favourite with artisan crafts in a residential square - relaxed and family-friendly.", 'family': True, 'price': 'Free entry', 'crowds': 'Quiet.', 'creators': ['nearfromhomesl'], 'url': 'http://www.haidhauser-weihnachtsmarkt.de'},
  ],
  'sights': [
   {'name': 'Eiszauber at Karlsplatz', 'area': 'Karlsplatz (Stachus)', 'when': 'Winter season - 2026 dates not yet published', 'why': "An open-air ice rink built in the summer fountain at Stachus, with Alpine-hut bars round it and skate hire. Watching the skaters with a hot drink is a good family stop.", 'family': True, 'price': 'Price not published', 'crowds': 'Busy evenings and weekends.', 'creators': ['nearfromhomesl', 'greeceandbeyon', 'walkingaroundc', 'sophienadeau'], 'url': 'https://www.muenchen.de'},
   {'name': 'The market from Alter Peter', 'area': 'Marienplatz', 'when': 'Just before sunset (about 16:20)', 'why': "Climb St Peter's tower for the lit market with the Frauenkirche behind. Narrow, cold and busy - not for small children at peak times.", 'family': False, 'price': '€5 (2026)', 'crowds': 'Two-way stair; packed at times.', 'creators': ['thelittlebaske', 'heresgood', 'adventuresofak'], 'url': 'https://www.alterpeter.de'},
   {'name': 'Krampus runs', 'area': 'Old town', 'when': 'Early December', 'why': "Alpine Krampus clubs parade in horned demon costumes through the centre - 300+ figures from Sendlinger Straße to the Rindermarkt in 2023. A spectacle, but genuinely frightening for small children, and some runs involve whips and chasing.", 'family': False, 'price': 'Free', 'crowds': 'Dense along the route; Marienplatz is the main viewing spot.', 'creators': ['bayernreisetip', 'nearfromhomesl', 'felifromgerman'], 'url': maps('Krampuslauf')},
   {'name': 'Advent music from the Rathaus balcony', 'area': 'Marienplatz', 'when': 'Evenings from 17:15 (Sun-Thu, per the organiser)', 'why': 'Brass and choirs from the town hall balcony over the market - a free, very Munich moment.', 'family': True, 'price': 'Free', 'crowds': 'The square is packed around it.', 'creators': [], 'url': 'https://www.christkindlmarkt-muenchen.de'},
  ],
  'safety': [
   {'title': 'Crowds and timing', 'text': "Marienplatz is shoulder to shoulder on Saturdays and in the evenings, and filled with phones at the 11:00 and 12:00 Glockenspiel. Early afternoon on a weekday is calmest; the Residenz is calm by day but packed at dinner time.", 'creators': ['chrisandsara', 'walkingaroundc', 'lifewithrachel', 'mathersonthema']},
   {'title': 'Pickpockets: fewer, but police still warn', 'text': "Pickpocketing fell 11% in 2025 to less than half its 2016 level, and police run uniformed and plain-clothes patrols, pickpocket squads and cameras at Marienplatz and the pedestrian zone. They still say thefts happen 'again and again' in market crowds: inner pockets, bags closed and in front, extra care in queues.", 'creators': ['deanaandphil']},
   {'title': 'No knives on the markets', 'text': "Munich police say carrying weapons and knives is banned on Christmas markets under weapons law. A permanent knife ban also covers the Alter Botanischer Garten by the station.", 'creators': []},
   {'title': 'Cash, cards and deposits', 'text': "The Marienplatz organiser says 80% of stalls take cards, some above a €1-10 minimum, but creators found many stalls cash only, and the medieval market was cash only in 2025. Mug deposits were €5 in 2025, and €10-15 at the medieval market. Toilets are at the Rathaus Prunkhof and the Marienplatz station.", 'creators': ['boozingabroads', 'eastwestwander', 'woltersworld', 'valeska']},
   {'title': 'Cold and dark', 'text': "It's dark by about 4:20pm and creators saw freezing rain and heavy snow. Stalls have no heaters and few napkins - eating while you queue keeps you warm. The Residenz village and Tollwood have seating under cover.", 'creators': ['adventuresofma', 'woltersworld', 'ciaragan', 'jmbanquicio']},
   {'title': 'Have a lost-child plan', 'text': "Before you go in, agree a meeting point everyone can find - the Fish Fountain (Fischbrunnen) on Marienplatz is the classic one. A Wiley Fox QR wristband on each child means anyone who finds them can reach you straight away.", 'creators': []},
   {'title': "New Year's Eve", 'text': "In 2025/26 fireworks were banned from 21:00 to 02:00 in the pedestrian zone from Marienplatz to Karlsplatz and at the Viktualienmarkt, and bangers were banned all day inside the Mittlerer Ring. About 6,000 people were at Marienplatz at midnight and press reports of the police balance called the night largely peaceful. 2026/27 rules are not out yet.", 'creators': []},
  ],
  'plan': "In 2026 the Marienplatz market runs 20 November to 24 December (closed Sunday 22 November; 24 December until 14:00); the Residenz village runs from 16 November to 22 December, Pink Christmas to 20 December, and most others to 23 December. Only Marienplatz and Schwabing open on Christmas Eve, and Tollwood is closed 24-30 December. Book hotels and restaurants early. Zone M day tickets rise from €10.10 to €10.80 on 1 January 2027.",
 },
 'map_intro': "Germany doesn't publish street-level crime data, so this map shows the markets and sights in this guide and the places Munich police and the city focus on around the station.",
 'map_pins': [
  {'n': 'Christkindlmarkt (Marienplatz)', 'lat': 48.1374, 'lng': 11.5755, 'kind': 'market', 'note': '20 Nov - 24 Dec 2026. Meet at the Fish Fountain.'},
  {'n': 'Kripperlmarkt & Rindermarkt', 'lat': 48.1357, 'lng': 11.5738, 'kind': 'market', 'note': 'Nativity stalls and a quieter market.'},
  {'n': 'Residenz Christmas village', 'lat': 48.1412, 'lng': 11.5790, 'kind': 'market', 'note': 'Fairy-tale forest and puppets, 16 Nov - 22 Dec.'},
  {'n': 'Medieval market (Wittelsbacherplatz)', 'lat': 48.1433, 'lng': 11.5772, 'kind': 'market', 'note': 'Best after dark; €10-15 goblet deposit.'},
  {'n': 'Chinese Tower market', 'lat': 48.1527, 'lng': 11.5921, 'kind': 'market', 'note': 'Wed-Sun only; curling for kids.'},
  {'n': 'Pink Christmas (Stephansplatz)', 'lat': 48.1311, 'lng': 11.5690, 'kind': 'market', 'note': '20 Nov - 20 Dec, from 16:00 on weekdays.'},
  {'n': 'Sendlinger Tor market', 'lat': 48.1339, 'lng': 11.5670, 'kind': 'market', 'note': 'Small and local.'},
  {'n': 'Tollwood (Theresienwiese)', 'lat': 48.1316, 'lng': 11.5494, 'kind': 'market', 'note': 'Winter festival, 24 Nov - 23 Dec.'},
  {'n': 'Schwabing market (Münchner Freiheit)', 'lat': 48.1617, 'lng': 11.5862, 'kind': 'market', 'note': '50th year; open 24 Dec to 14:00.'},
  {'n': 'Eiszauber ice rink (Karlsplatz)', 'lat': 48.1392, 'lng': 11.5661, 'kind': 'sight', 'note': 'Open-air rink at Stachus.'},
  {'n': "St Peter's tower", 'lat': 48.1365, 'lng': 11.5760, 'kind': 'sight', 'note': 'View over the market, €5.'},
  {'n': 'Viktualienmarkt', 'lat': 48.1351, 'lng': 11.5763, 'kind': 'sight', 'note': 'Food market; closed Sundays.'},
  {'n': 'Deutsches Museum', 'lat': 48.1299, 'lng': 11.5834, 'kind': 'sight', 'note': 'Best wet-day option for families.'},
  {'n': 'Eisbach wave', 'lat': 48.1435, 'lng': 11.5878, 'kind': 'sight', 'note': 'Watch the surfers from the bridge.'},
  {'n': 'Hauptbahnhof & south Bahnhofsviertel', 'lat': 48.1385, 'lng': 11.5605, 'kind': 'caution', 'note': 'Police focus area; no drinking on the street around the station.'},
  {'n': 'Alter Botanischer Garten', 'lat': 48.1425, 'lng': 11.5642, 'kind': 'caution', 'note': 'Knife and alcohol ban zone; avoid as a late-night shortcut.'},
 ],
 'map': {'center': [11.5720, 48.1395], 'zoom': 13.6},
 'creators': creators,
 'sources': sources,
}
# sanity: every creator key referenced exists
refs = set()
def walk(x):
    if isinstance(x, dict):
        for k, v in x.items():
            if k == 'creators' and isinstance(v, list): refs.update(v)
            elif k == 'source' and isinstance(v, str) and v.islower(): refs.add(v)
            else: walk(v)
    elif isinstance(x, list): [walk(i) for i in x]
walk({k: v for k, v in G.items() if k != 'creators'})
missing = sorted(r for r in refs if r not in creators)
print('creators', NC, 'videos', NV, 'missing keys:', missing)
json.dump(G, open(f'{D}/guide.json', 'w'), ensure_ascii=False, indent=1)
json.dump({'tips': tips}, open(f'{D}/tips.json', 'w'), ensure_ascii=False, indent=1)
