# Builds ber/guide.json for the Berlin Christmas 2026 guide from researched content + creator DB export.
import json, re, collections, urllib.parse
D = '/home/claude/cityguide/ber'
api = json.load(open(f'{D}/api.json'))
tips = json.load(open(f'{D}/tips.json'))['tips']
costs = json.load(open(f'{D}/costs.json'))
key = lambda n: re.sub(r'[^a-z0-9]', '', n.lower())[:14]
maps = lambda q: 'https://www.google.com/maps/search/?api=1&query=' + urllib.parse.quote(q + ' Berlin')
book = lambda q: 'https://www.booking.com/searchresults.html?ss=' + urllib.parse.quote(q + ' Berlin') + '&aid=YOUR_AID_HERE'

# creators + sources from the DB export (only videos that yielded facts)
# Two channels with a political campaigning angle are left out of the credits and not used as sources.
EXCLUDE = {'europesdecline', 'unignorierbard'}
for k in list(api['facts']):
    api['facts'][k] = [f for f in api['facts'][k] if key(f['creator']) not in EXCLUDE]
srcs = {s['id']: s for s in api['sources']}
used, cnt = {}, collections.Counter()
for v in api['facts'].values():
    for f in v:
        used.setdefault(f['source_id'], f['creator']); cnt[f['creator']] += 1
creators = {}
for sid, name in used.items():
    creators.setdefault(key(name), {'name': name, 'url': srcs.get(sid, {}).get('url') or f'https://www.youtube.com/watch?v={sid[3:]}'})
sources = sorted([{'creator': used[sid], 'creator_url': creators[key(used[sid])]['url'], 'title': s['title'], 'url': s['url'], 'date': (s.get('published_at') or '')[:7]}
                  for sid, s in srcs.items() if sid in used], key=lambda x: x['creator'].lower())
NC, NV = len(creators), len(sources)

G = {
 'city': 'Berlin', 'slug': 'berlin', 'country': 'Germany', 'edition': 'Christmas 2026 edition', 'updated': '2026-10-05',
 'status': "Draft for Barry's approval", 'audience': 'Families and solo travellers',
 'tagline': 'The Wiley Fox guide to Berlin for families and solo travellers',
 'cover_blurb': f'What {NC} travel creators actually say about Berlin, checked against the 2025 police figures - more than 60 Christmas markets across a huge city, where to stay, what to eat, and the seven places police watch most closely.',
 'banner_text': 'Official travel advice for 200+ countries, community reports, one-tap SOS, and QR wristbands so lost children and lost bags find their way back.',
 'safety': {
  'wf_rating': 3, 'wf_label': 'Moderate',
  'wf_summary': "Berlin has more recorded crime per resident than any other German city in our guides: police counted 13,642 offences per 100,000 residents in 2025, against 11,362 in the Cologne police area and 5,798 in Munich. But the trend is down. Total offences fell 6.7% to the lowest level in more than ten years (apart from 2021), theft fell 9%, pickpocketing 15% and pickpocketing on trains and stations 25%. Street robbery fell 9%. On Eurostat's like-for-like 2024 table below, Berlin sits mid-table for theft (below Cologne, Düsseldorf and Hamburg) but near the top for robbery, assault and burglary. Most of the crime visitors are likely to meet is theft in crowds, and it clusters in seven places the city has named as high-crime areas, such as Alexanderplatz, Kottbusser Tor and Görlitzer Park, where police can check people without a specific reason. Some figures went up: recorded knife attacks rose 5.5% (police say partly because of a new recording rule), sexual offences 15.7% (mostly online abuse-image cases), and home burglary 24.5%. This rating is for the city as a whole, not street by street.",
  'creator_feeling': 4, 'creator_feeling_label': 'Feels safe - but gritty in places',
  'creator_summary': "Most creators felt safe in Berlin, including women travelling alone: Travel For Phoebe felt more relaxed than in Paris, Amsterdam or London, a DW Travel presenter who has lived there for ten years says she usually feels very safe, and Mountain Trekker walked to the U-Bahn in Kreuzberg at 3am without worry. What creators complain about is grit: litter, graffiti, broken glass, grubby U-Bahn stations and open drug dealing at Görlitzer Park, Kottbusser Tor and Leopoldplatz. Several found Alexanderplatz loud and uneasy at night, and two solo women felt nervous on poorly lit side streets. Pickpockets at the Brandenburg Gate, and touts and the shell game at Checkpoint Charlie, are the most common warnings.",
  'data_note': "Figures are from the Berlin police's PKS 2025 short report (presented 11 March 2026) and cover the whole city (about 3.7 million residents). Rates are per resident, so places with many visitors and few residents look worse: the police's own area table puts the government quarter at 46,179 and Alexanderplatz at 28,817 offences per 100,000, against 12,882 for Berlin as a whole. Since 1 July 2026 seven places are 'crime-burdened places' (kbO): Alexanderplatz, Görlitzer Park/Wrangelkiez, Hermannplatz/Donaukiez, Hermannstraße/Bahnhof Neukölln, Kottbusser Tor, Rigaer Straße and Warschauer Brücke. Police say this lets them check ID and bags without suspicion; it does not mean the areas are closed. Knives are banned at Görlitzer Park, Kottbusser Tor and Leopoldplatz (since February 2025) and weapons and knives on all public transport (since July 2025), with fines up to €10,000. Recorded homicides rose to 165, but police attribute 79 to a single series of suspected killings of seriously ill patients by a doctor. In July 2026 a vehicle was driven into the crowd at the Berlin Pride (CSD) event near Potsdamer Platz, killing one person and injuring 29 (FCDO, 30 September 2026). The interactive crime atlas was switched off on 1 October 2026; only the spreadsheet remains.",
  'data_months': ['2025-12', '2025-01'],
 },
 'official_crime': [
  {'number': '-6.7%', 'label': 'Recorded offences in 2025 (502,743)', 'desc': "The lowest total in more than ten years apart from 2021. That is 13,642 offences per 100,000 residents, down 7.3% (Polizei Berlin, PKS 2025)."},
  {'number': '-15%', 'label': 'Pickpocketing in 2025 (13,621 cases)', 'desc': 'Down 14.6%. On trains and in stations it fell 24.6% to 6,192 cases. Street robbery fell 9.1% to 2,730.'},
  {'number': '7', 'label': 'Named high-crime places (kbO)', 'desc': 'From 1 July 2026, including Alexanderplatz, Kottbusser Tor and Görlitzer Park. Police can check ID and bags there without a specific reason.'},
 ],
 'crime_source': {'name': 'Polizei Berlin, PKS Berlin 2025 (short report)', 'citation': "City-wide statistics for 2025 (presented 11 March 2026), the police list of crime-burdened places (kbO) in force from 1 July 2026, the police area table 2016-2025, the knife and weapon ban ordinances, the police New Year's Eve report of 1 January 2026, Berlin court rulings on Görlitzer Park (1 June and 1 October 2026), and FCDO Germany advice (30 September 2026). Rates are per resident, not adjusted for visitors."},
 'credit_fallback': 'Source: Polizei Berlin / Senatsverwaltung für Inneres',
 'app_ctas': [
  {'where': 'before_booking', 'text': "Germany doesn't publish street-level crime data, so before you book, check your hotel's street against the map in this guide and any community reports on Wiley Fox. A hotel a few streets from Kottbusser Tor or Warschauer Brücke can feel very different from one right on top of them at 2am.", 'url': 'https://www.thewileyfox.com'},
  {'where': 'families', 'text': 'Clip a Wiley Fox QR wristband on each child. If you get separated at the Rotes Rathaus or Alexanderplatz markets, anyone who scans it can contact you straight away - no app needed on their side.', 'url': 'https://www.thewileyfox.com'},
  {'where': 'night', 'text': "Berlin is spread out and side streets can be dark. Save your hotel on Wiley Fox, stay on lit main roads and keep SOS one tap away on the way back from the markets.", 'url': 'https://www.thewileyfox.com'},
  {'where': 'community', 'text': 'Found a cash-only stall, a closed market or a street that felt wrong? Drop a community report on the map - it helps the next family.', 'url': 'https://www.thewileyfox.com'},
 ],
 'stats': [
  {'number': '23 Nov', 'label': 'Most big markets open in 2026', 'desc': 'Gendarmenmarkt, Rotes Rathaus, Alexanderplatz, Breitscheidplatz and Charlottenburg all start on Monday 23 November (visitBerlin, Oct 2026).'},
  {'number': '60+', 'label': 'Christmas markets across the city', 'desc': "Creators count 60 to 90. Each has its own organiser, dates and hours, so check the one you want."},
  {'number': str(NC), 'label': f'Creators · {NV} videos', 'desc': 'Paraphrased and credited, cross-checked with police figures.'},
 ],
 'overview': [
  "Berlin is huge and has no single centre. Creators describe it as villages grown together: the historic east around Museum Island, Unter den Linden and Alexanderplatz, the old west around the Zoo, the Ku'damm and the Kaiser Wilhelm Memorial Church, and rebuilt Potsdamer Platz in between. Distances are bigger than they look on a map, so plan by area and use the U-Bahn and S-Bahn. Creators suggest three or four days at least.",
  "At Christmas there are more than 60 markets. The big central ones - Gendarmenmarkt, the Rotes Rathaus with its ice rink and Ferris wheel, Alexanderplatz and Breitscheidplatz - open on 23 November 2026, with calmer options at Charlottenburg Palace and the Humboldt Forum, a Scandinavian market in Prenzlauer Berg and a winter slide at Potsdamer Platz. For families there are skating, carousels, a flying Santa, the zoo, and good wet-day museums.",
  "For solo travellers Berlin is open, relaxed and easy to get around in English, and creators - women included - mostly felt safe. Plan for the things that catch people out: pickpockets in crowds, plain-clothes ticket inspectors, cash-only stalls, shops shut on Sundays, early darkness (about 4pm in December) and a handful of gritty hotspots where drug dealing is open.",
 ],
 'facts': {
  'Currency': 'Euro (EUR) - cards work in many places, but many market stalls, bakeries, döner shops and toilets want cash',
  'Language': 'German - English is widely spoken, and some café staff speak only English',
  'Time zone': 'Central European Time (UTC+1) - one hour ahead of the UK',
  'Plug': 'Type C and F, 230V - UK plugs need an adaptor',
  'Emergency': '110 police · 112 fire & ambulance · 116 117 out-of-hours doctor',
  'Entry': 'UK passport must be under 10 years old on arrival and valid 3+ months after you leave the Schengen area; visa-free for up to 90 days in any 180. EES biometric checks are running, so allow extra time (gov.uk, Oct 2026)',
  'Tipping': 'About 5-10%, or round up - tell the server the total you want to pay. Card machines now often prompt for a tip',
  'Best time': 'Late November to 23 December for the markets (weekday daytimes are calmest); May to September for parks and outdoor life',
 },
 'stay': [
  {'area': 'Mitte', 'for': ['First-timers', 'Christmas markets', 'Families'], 'why': "The most recommended base: walkable to the Brandenburg Gate, Museum Island, Gendarmenmarkt and the Rotes Rathaus market, with transport everywhere. Travel Tips Group quotes three-star hotels from about €120 a night and four-star €200-250 (2025). Creators like the streets around Friedrichstraße station; the area right on Alexanderplatz is busier and scruffier at night.", 'creators': ['traveltipsgrou', 'destinationwel', 'easytravel4u', 'tripxtreme', 'islandhoppertv', 'exoticvacation', 'multicitytrips']},
  {'area': 'Prenzlauer Berg', 'for': ['Families', 'Quiet nights', 'Cafés'], 'why': "Leafy, cobbled and full of cafés, a few tram or U-Bahn stops north of Alexanderplatz. Creators pick it for families and a calmer stay; it has the Lucia Christmas market at the Kulturbrauerei and the Mauerpark Sunday flea market. Destination Well Known's favourite area.", 'creators': ['traveltipsgrou', 'tripxtreme', 'destinationwel', 'easytravel4u']},
  {'area': "Charlottenburg (Zoo & Ku'damm)", 'for': ['Families', 'Shopping', 'Calmer base'], 'why': "The elegant west, with the zoo and aquarium, Ku'damm shopping, the Breitscheidplatz market and Charlottenburg Palace. Ultimate Bucket List suggests families stay here near the zoo. Nahana paid about €60 a night for a Premier Inn here in winter 2026, 20 minutes from the centre by train.", 'creators': ['ultimatebucket', 'traveltipsgrou', 'easytravel4u', 'tripxtreme', 'nahana']},
  {'area': 'Kreuzberg', 'for': ['Solo travellers', 'Food', 'Nightlife'], 'why': "Young, alternative and the best area for food, from Mustafa's and Curry 36 on Mehringdamm to Markthalle Neun. Hostels to smart hotels. It also contains Kottbusser Tor and Görlitzer Park, both police hotspots, so pick a street in western Kreuzberg (around Mehringdamm or Bergmannstraße) if you want quieter nights.", 'creators': ['traveltipsgrou', 'loispark', 'exoticvacation', 'tripxtreme', 'multicitytrips', 'easytravel4u', 'destinationwel']},
  {'area': 'Friedrichshain', 'for': ['Solo travellers', 'Nightlife', 'Budget'], 'why': "Bars, clubs, the East Side Gallery and the RAW site. Destination Well Known says it is a bit rougher than Prenzlauer Berg and best for travellers in their twenties. Warschauer Brücke and Rigaer Straße are on the police's hotspot list - the bridge is busiest at night when the clubs empty.", 'creators': ['destinationwel', 'easytravel4u', 'tripxtreme', 'africantigress']},
  {'area': 'Near the Hauptbahnhof (Moabit)', 'for': ['Budget', 'Arriving by train'], 'why': "Modern, affordable hotels on the doorstep of the main station and the airport train. The catch: there is little around them, so you need transport for food and cafés. Mashtag Brady found rough sleepers and a police operation outside the station on arrival.", 'creators': ['destinationwel', 'easytravel4u', 'mashtagbrady']},
 ],
 'caution': [
  {'area': 'Alexanderplatz', 'when': 'Evenings and night', 'note': "Berlin's busiest square and transport hub, with the TV Tower and a big Christmas market. It is on the police hotspot list because of group violence, and has a police station on the square; a research group reading police data says most recorded cases there are shoplifting. Creators found it fine by day, loud and uneasy late at night. Keep phones and bags close, and step away from groups that are arguing.", 'creators': ['dwtravel', 'dutchtravelman', 'mashtagbrady', 'traveltimedj0r']},
  {'area': 'Görlitzer Park & Wrangelkiez (Kreuzberg)', 'when': 'After dark', 'note': "Known for open drug dealing; creators were offered drugs at the entrances. The Senate's night closure was stopped by the courts (final appeal rejected on 1 October 2026), so the park is open all night for now. Knives are banned there. Families use the playgrounds by day - just don't use it as a night shortcut.", 'creators': ['destinationwel', 'dutchtravelman']},
  {'area': 'Kottbusser Tor (Kreuzberg)', 'when': 'Evenings and night', 'note': "A busy U-Bahn junction with drug dealing and violence linked to it, on the hotspot list and in a knife ban zone. Destination Well Known advises families not to stay right here. Fine to pass through by day.", 'creators': ['destinationwel', 'kailentitadven']},
  {'area': 'Warschauer Brücke & RAW (Friedrichshain)', 'when': 'Late night at weekends', 'note': "The bridge between the S-Bahn and the clubs is on the hotspot list. It is packed with people going out at night; keep valuables zipped away and avoid arguments.", 'creators': []},
  {'area': 'Hermannplatz & Hermannstraße (Neukölln) and Leopoldplatz (Wedding)', 'when': 'Evenings', 'note': "Busy, scruffy shopping streets. Hermannplatz and Hermannstraße are on the hotspot list; Leopoldplatz is a knife ban zone, where Dutch Travel Maniac saw open drug use after dark (January 2026). Not places visitors usually need at night.", 'creators': ['dutchtravelman', 'davidg']},
  {'area': 'Brandenburg Gate & Checkpoint Charlie', 'when': 'Daytime crowds', 'note': "The two places creators most often warn about: pickpockets in the crowd at the Gate, pushy street performers and sellers asking for tips, and at Checkpoint Charlie actors in uniform charging for photos, fake Wall pieces and a street shell game. Go early or after dark when the Gate is lit and quiet.", 'creators': ['rokgoesaround', 'exoticvacation', 'joshvlog', 'africantigress', 'destinationwel']},
  {'area': 'Bike lanes on the pavement', 'when': 'Always', 'note': "Berlin's cycle lanes often run along the pavement in a slightly different colour. Step into one and cyclists will shout - or hit you. Keep children on the footpath side and wait for the green man (crossing on red can be fined).", 'creators': ['cartersullivan', 'dwtravel', 'worldwidewu', 'ultimatebucket']},
 ],
 'scams': [
  {'title': 'Plain-clothes ticket inspectors - and fake ones', 'text': "There are no barriers, and real BVG inspectors ride in normal clothes. A missing or unstamped paper ticket costs €60. Creators heard of fakes demanding cash on the spot: real inspectors carry official ID, so ask to see it.", 'creators': ['ultimatebucket', 'dwtravel', 'nahana', 'cartersullivan']},
  {'title': 'Used tickets sold at stations', 'text': "Strangers at S-Bahn and U-Bahn stations sometimes sell old or already-used paper tickets. Buy only from machines or the BVG app.", 'creators': ['americansinger']},
  {'title': 'The shell game', 'text': "A street guessing game with a crowd of 'winners' - all part of the team. Seen near Checkpoint Charlie and in tourist areas. Walk past, and keep a hand on your bag while you watch anything.", 'creators': ['joshvlog', 'africantigress']},
  {'title': 'Checkpoint Charlie photos and fake Wall pieces', 'text': "The 'soldiers' are actors who pose for photos and then demand money; Wall fragments sold nearby are almost certainly fake. The free Black Box exhibition across the road explains the real history.", 'creators': ['rokgoesaround', 'exoticvacation', 'robonholiday']},
  {'title': 'Airport taxis', 'text': "A taxi from BER to Mitte is about €50-60. Creators who live in Germany say some drivers don't switch on the meter; insist on it and check they take cards before you get in. The train is €5 and often quicker.", 'creators': ['americansinger', 'thewonderingen']},
  {'title': 'ATM fees and drinks', 'text': "Use a bank's ATM rather than Euronet machines, which charge high fees. In bars, keep your drink with you; DW Travel notes drink spiking happens in Germany and drugstores sell test strips.", 'creators': ['destinationwel', 'caracelestewes', 'dwtravel']},
 ],
 'transport': [
  {'title': 'From the airport (BER)', 'text': "Trains leave from the station under Terminal 1 (Terminal 2 is a 200 m walk). The FEX airport express takes about 23 minutes to the Hauptbahnhof, about three times an hour; RE trains are similar and the S9 takes about 50 minutes but runs every 20. All need a Berlin ABC single, €5.00 (2026). A taxi is about €50-60.", 'creators': ['thewonderingen', 'robonholiday', 'ultimatebucket']},
  {'title': 'Tickets and fines', 'text': "An AB single is €4.00 and lasts two hours with changes; a 24-hour AB ticket is €11.20, and a 24-hour small-group ticket for up to five is €35.30 (2026). Under 6s are free, and up to three children aged 6-14 travel free with an adult's 24-hour ticket. Stamp paper tickets before your first ride - there are no barriers and the fine is €60. The BVG app is easiest.", 'creators': ['robonholiday', 'rokgoesaround', 'experienceberl', 'dwtravel', 'sethinberlin']},
  {'title': 'Getting round the sights', 'text': "The U5 links the Brandenburg Gate, Museum Island and Alexanderplatz. Bus 100 is a cheap double-decker sightseeing ride from Alexanderplatz past Unter den Linden and the Tiergarten to the Zoo. The U8 goes to the Wall Memorial at Bernauer Straße and the S-Bahn to Warschauer Straße for the East Side Gallery. Allow extra time: platforms are deep and the city is spread out.", 'creators': ['robonholiday', 'rokgoesaround', 'radicalliving', 'dwtravel']},
  {'title': 'Night travel', 'text': "U-Bahn and S-Bahn run roughly 4:30am to 1am on weekdays, with night buses and trams in between, and all night on Friday and Saturday nights. Trams and buses run less often on Sundays.", 'creators': ['experienceberl', 'mountaintrekke', 'davidg']},
  {'title': 'Day trips', 'text': "Potsdam's palaces are about 40 minutes on the S7 and covered by an ABC ticket. Leipzig is about an hour and Dresden two hours by train. The Brandenburg-Berlin-Ticket (€36.50 for up to five people) covers regional trains for a day.", 'creators': ['rokgoesaround', 'travelnavigato', 'davidg']},
 ],
 'costs': costs,
 'top_intro': "Ranked by how often creators recommend them. Most are along the U5 between the Brandenburg Gate and Alexanderplatz; in December do the outdoor Wall sites by daylight and save the markets for after dark.",
 'top': [
  {'name': 'Brandenburg Gate & Unter den Linden', 'area': 'Mitte', 'why': "Berlin's symbol, at the end of a 25-minute walk along Unter den Linden from Museum Island. Busy all day and a pickpocket spot - come early or after dark when it's lit and quiet. The Reichstag and the Holocaust Memorial are both within a few minutes.", 'family': True, 'price': 'Free', 'url': maps('Brandenburger Tor'), 'creators': ['rokgoesaround', 'bradballtravel', 'exoticvacation', 'destinationwel', 'dwtravel', 'israelplata']},
  {'name': 'Reichstag dome', 'area': 'Tiergarten', 'why': "Walk up the spiral ramp inside the Bundestag's glass dome for views over the city, with a free audio guide. It's free but must be booked online in advance, often weeks ahead, and everyone 16 and over needs photo ID at airport-style security. Closed all day on 24 December, and from 16:00 on 31 December.", 'family': True, 'price': 'Free (book ahead)', 'url': 'https://www.bundestag.de/besuche/kuppel', 'creators': ['rokgoesaround', 'robonholiday', 'radicalliving', 'vishakhandelwa', 'stevemarsh', 'dwtravel', 'woltersworld', 'exoticvacation']},
  {'name': 'Berlin Wall Memorial (Bernauer Straße)', 'area': 'Mitte / Prenzlauer Berg', 'why': "The best place to understand the Wall: 1.5 km of preserved border strip, watchtower, escape-tunnel markings and a free documentation centre with a viewing platform. Calmer than the East Side Gallery. U8 to Bernauer Straße or tram M10.", 'family': True, 'price': 'Free', 'url': maps('Gedenkstätte Berliner Mauer'), 'creators': ['rokgoesaround', 'experienceberl', 'dwtravel', 'destinationwel', 'stevemarsh', 'worldwidewu']},
  {'name': 'East Side Gallery', 'area': 'Friedrichshain', 'why': "The longest surviving stretch of the Wall, 1.3 km of murals by more than 100 artists along the Spree. Free and open all the time. Crowded at the famous murals, quieter further along; don't touch the paintings.", 'family': True, 'price': 'Free', 'url': maps('East Side Gallery'), 'creators': ['rokgoesaround', 'radicalliving', 'alextravels', 'dwtravel', 'ann', 'woltersworld', 'indiantravelvl']},
  {'name': 'Museum Island & the Neues Museum', 'area': 'Mitte', 'why': "Five museums on one island; the Neues Museum's Egyptian collection and Nefertiti bust are the favourite, about two hours (book a timed slot). The Pergamon Museum is closed until 4 July 2027. The free first-Sunday scheme ended in December 2024. Bring a coin for lockers.", 'family': True, 'price': 'Museumsinsel-Ticket €24 · under 18 free (2026)', 'url': 'https://www.smb.museum', 'creators': ['rokgoesaround', 'caracelestewes', 'destinationwel', 'dwtravel', 'exoticvacation']},
  {'name': 'Memorial to the Murdered Jews of Europe', 'area': 'Mitte', 'why': "A field of 2,711 concrete slabs by the Brandenburg Gate, open day and night. Most visitors miss the free underground information centre - see the outdoor field first, as the queue grows by noon. Please don't climb or play on the slabs.", 'family': True, 'price': 'Free', 'url': maps('Denkmal für die ermordeten Juden Europas'), 'creators': ['radicalliving', 'alextravels', 'exoticvacation', 'ann', 'woltersworld', 'travelforphoeb']},
  {'name': 'TV Tower (Fernsehturm)', 'area': 'Alexanderplatz', 'why': "A 40-second lift to the viewing floor at 203 m. Pricey, and some creators say free viewpoints are nearly as good, but children love it. Book a time slot online in December and go on a clear day - an hour before sunset is best but busiest.", 'family': True, 'price': 'From €20 online (2026)', 'url': 'https://tv-turm.de', 'creators': ['dwtravel', 'destinationwel', 'rokgoesaround', 'ultimatebucket', 'islandhoppertv', 'mashtagbrady']},
  {'name': 'Berliner Dom', 'area': 'Museum Island', 'why': "The cathedral's dome walk - about 270 steps, no lift - gives views over Museum Island. Fully reopened in March 2026. Bags go in coin lockers.", 'family': True, 'price': '€15 · concession €12 (2026)', 'url': 'https://www.berlinerdom.de', 'creators': ['destinationwel', 'robonholiday', 'rokgoesaround', 'bradballtravel', 'noahanderson']},
  {'name': 'Humboldt Forum', 'area': 'Mitte', 'why': "The rebuilt palace opposite the cathedral: free entry to the building and many exhibitions, a roof terrace with views of all the central sights (a few euros), and a winter market outside. A good first-day overview and a free wet-day option.", 'family': True, 'price': 'Free entry · roof terrace a few euros', 'url': 'https://www.humboldtforum.org', 'creators': ['rokgoesaround', 'dwtravel', 'destinationwel', 'experienceberl', 'radicalliving']},
  {'name': 'Topography of Terror', 'area': 'Kreuzberg', 'why': "A free documentation centre on the site of the Gestapo and SS headquarters, beside a surviving stretch of the Wall. Sobering, with graphic images inside; about an hour. Ten minutes' walk from Checkpoint Charlie.", 'family': False, 'price': 'Free', 'url': 'https://www.topographie.de', 'creators': ['experienceberl', 'destinationwel', 'exoticvacation', 'ultimatebucket', 'dwtravel']},
  {'name': 'Charlottenburg Palace', 'area': 'Charlottenburg', 'why': "Berlin's largest palace, with baroque rooms and big free gardens - and one of the prettiest Christmas markets in front of it. Closed on Mondays and on 24 December. Bring a €2 coin for lockers.", 'family': True, 'price': 'Old Palace €12 · reduced €8 · gardens free (2026)', 'url': 'https://www.spsg.de', 'creators': ['rokgoesaround', 'cartersullivan', 'ultimatebucket', 'travelnavigato', 'noahanderson']},
  {'name': 'Tiergarten & Berlin Zoo', 'area': 'Tiergarten', 'why': "The huge central park, with the Victory Column (285 steps, no lift) and one of the world's oldest zoos at its western end, famous for its pandas and next to the aquarium. Zoo prices change by date, so book online for cheaper slots.", 'family': True, 'price': 'Zoo €16-25 · child €7.50-12.50 (2026)', 'url': 'https://www.zoo-berlin.de', 'creators': ['islandhoppertv', 'traveltipsgrou', 'ultimatebucket', 'sethinberlin', 'destinationwel', 'alextravels']},
 ],
 'eat_label': 'Currywurst, döner and a market hall',
 'eat_intro': "Berlin eats on the street: currywurst, döner and a hundred cuisines, with Kreuzberg the food capital. Every place is credited to the creator who recommended it, and prices carry the year.",
 'eat': [
  {'name': "Mustafa's Gemüse Kebap", 'area': 'Mehringdamm, Kreuzberg', 'type': 'Döner stand', 'price': '€', 'family': True, 'why': "The famous chicken döner with roast vegetables, €7.90 in 2026. The queue can be 45 minutes to an hour - creators say it's part of the experience.", 'creators': ['maxnomad', 'abroadandhungr', 'leckertour', 'dwtravel', 'exoticvacation'], 'url': maps("Mustafa's Gemüse Kebap Mehringdamm")},
  {'name': 'Curry 36', 'area': 'Mehringdamm, Kreuzberg', 'type': 'Currywurst stand', 'price': '€', 'family': True, 'why': "Classic Berlin currywurst, open 365 days a year, a few doors from Mustafa's; branches at Zoo, Hauptbahnhof and Warschauer Straße.", 'creators': ['leckertour', 'maxnomad'], 'url': maps('Curry 36 Mehringdamm')},
  {'name': 'Curry 61', 'area': 'Oranienburger Straße, Mitte', 'type': 'Currywurst', 'price': '€', 'family': True, 'why': "Near Hackescher Markt, with a vegan option: currywurst €3.20 and fries €3 in 2025.", 'creators': ['stufrtravelfoo', 'experienceberl', 'radicalliving'], 'url': maps('Curry 61 Oranienburger Straße')},
  {'name': "Konnopke's Imbiss", 'area': 'Under the U2, Prenzlauer Berg', 'type': 'Currywurst stand', 'price': '€', 'family': True, 'why': "East Berlin's famous stand under the elevated railway, serving currywurst without skin and fries 'Rot-Weiss'. Usually a queue.", 'creators': ['wherearewe'], 'url': maps("Konnopke's Imbiss")},
  {'name': 'Burgermeister', 'area': 'Schlesisches Tor, Kreuzberg', 'type': 'Burgers', 'price': '€', 'family': True, 'why': "Burgers from a former public toilet under the U-Bahn tracks since 2006; the chilli cheeseburger is the one to get.", 'creators': ['leckertour', 'maxnomad', 'evanedinger'], 'url': maps('Burgermeister Schlesisches Tor')},
  {'name': 'Markthalle Neun (Street Food Thursday)', 'area': 'Kreuzberg', 'type': 'Market hall', 'price': '€€', 'family': True, 'why': "An old market hall with food stalls all week and a huge street-food night on Thursdays - ribs €14, manti, dumplings, Käsespätzle (2026). Seats go fast: come early or after 8:30pm.", 'creators': ['mikechenclipsb', 'strictlydumpli', 'naomijon', 'stufrtravelfoo', 'jimmykim', 'zoeandsimon'], 'url': maps('Markthalle Neun')},
  {'name': 'Zur letzten Instanz', 'area': 'Mitte', 'type': 'Old Berlin restaurant', 'price': '€€', 'family': True, 'why': "Described as one of Berlin's oldest restaurants: Königsberger Klopse (meatballs in caper sauce) and crispy pork knuckle.", 'creators': ['greatbigstory'], 'url': maps('Zur letzten Instanz')},
  {'name': 'Dicke Wirtin', 'area': 'Charlottenburg', 'type': 'Berlin pub', 'price': '€€', 'family': True, 'why': "A classic pub-restaurant open since 1933, with schnitzel, currywurst and a warm atmosphere. Book ahead.", 'creators': ['abroadandhungr'], 'url': maps('Dicke Wirtin')},
  {'name': 'Hatay', 'area': 'Near Checkpoint Charlie', 'type': 'Turkish', 'price': '€€', 'family': True, 'why': "Cara Celeste West's family rated the hummus and grilled chicken 10 out of 10 - but it was fully booked, so reserve.", 'creators': ['caracelestewes'], 'url': maps('Hatay Restaurant Berlin')},
  {'name': 'Madame Ngo', 'area': 'Charlottenburg', 'type': 'Vietnamese', 'price': '€€', 'family': True, 'why': "Picked by a Berlin chef as one of four ways to taste the city; he sends people to Charlottenburg for Asian food.", 'creators': ['condnasttravel'], 'url': maps('Madame Ngo')},
  {'name': "Brammibal's Donuts", 'area': 'Several branches', 'type': 'Vegan doughnuts', 'price': '€', 'family': True, 'why': "Vegan doughnuts that won over Cara Celeste West's daughter.", 'creators': ['caracelestewes'], 'url': maps("Brammibal's Donuts")},
  {'name': 'Prater Garten', 'area': 'Prenzlauer Berg', 'type': 'Beer garden', 'price': '€€', 'family': True, 'why': "Berlin's oldest beer garden (1837), open all year - wrap up in winter.", 'creators': ['destinationwel'], 'url': maps('Prater Garten')},
 ],
 'grown_ups': "For a grown-ups' night: a Glühwein at Gendarmenmarkt or a flaming Feuerzangenbowle at the Rotes Rathaus, then Kreuzberg or Friedrichshain, where locals buy a beer at a Späti (late shop) and drink it on the street. Famous clubs like Berghain have brutal door policies and are often cash only - you can queue for hours and be turned away, so have a plan B. Keep your drink with you. The drinking age is 16 for beer and wine and 18 for spirits.",
 'hotels': [
  {'name': 'Hotel Adlon Kempinski', 'area': 'Pariser Platz, Mitte', 'for': 'Luxury', 'band': '€€€€', 'why': 'The grand hotel beside the Brandenburg Gate. Not creator-reviewed: a Wiley Fox pick for location.', 'url': book('Hotel Adlon Kempinski'), 'source': ''},
  {'name': 'Classic Hotel Alexander Plaza', 'area': 'Near Hackescher Markt, Mitte', 'for': 'Couples', 'band': '€€€', 'why': "Four-star with a spa and sauna, close to Museum Island; TripHunter's pick for couples (2022).", 'url': book('Classic Hotel Alexander Plaza'), 'source': 'triphunter'},
  {'name': 'Circus Hostel', 'area': 'Rosenthaler Platz, Mitte', 'for': 'Solo & budget', 'band': '€', 'why': "Social hostel by the tram and U-Bahn with buffet breakfast and nightly events; women-only dorm beds from about €20 (2026).", 'url': book('Circus Hostel'), 'source': 'travelforphoeb'},
  {'name': 'Premier Inn Charlottenburg', 'area': 'Charlottenburg', 'for': 'Families on a budget', 'band': '€€', 'why': "About €60 a night in winter for a good room in a residential area, 20 minutes from the centre (2026).", 'url': book('Premier Inn Charlottenburg'), 'source': 'nahana'},
  {'name': 'Motel One Alexanderplatz', 'area': 'Alexanderplatz', 'for': 'Good value, central', 'band': '€€', 'why': "Two minutes' walk from Alexanderplatz station (2025). Handy for the markets, but pick a room away from the square for quiet nights.", 'url': book('Motel One Alexanderplatz'), 'source': 'robonholiday'},
 ],
 'itinerary': {
  '1day': [
   ['09:00', 'Brandenburg Gate before the crowds', 'Then the Holocaust Memorial and (if you booked) the Reichstag dome.'],
   ['11:00', 'Unter den Linden to Museum Island', 'Walk east past Bebelplatz; Neues Museum or the free Humboldt Forum and its roof terrace.'],
   ['13:00', 'Lunch', 'Currywurst at Curry 61 near Hackescher Markt.'],
   ['14:00', 'Gendarmenmarkt', 'The most elegant market - free entry on weekdays until 14:00, then €2.'],
   ['15:30', 'Rotes Rathaus & Alexanderplatz', 'Skating, the Ferris wheel and the flying Santa as the lights come on (dark by about 4pm).'],
   ['18:30', 'Dinner', 'Old Berlin food at Zur letzten Instanz, or a döner in Kreuzberg.'],
  ],
  '3day': [
   ['Day 1 · Historic centre', 'Brandenburg Gate, Holocaust Memorial and the Reichstag dome.', 'Museum Island and the Berliner Dom.', 'Gendarmenmarkt and the Rotes Rathaus market after dark.'],
   ['Day 2 · The Wall', 'Wall Memorial at Bernauer Straße.', 'Checkpoint Charlie (briefly) and the Topography of Terror.', 'East Side Gallery at dusk and dinner in Kreuzberg - Markthalle Neun if it is Thursday.'],
   ['Day 3 · The west', 'Zoo and aquarium, or Charlottenburg Palace (closed Mondays).', "Ku'damm and the Kaiser Wilhelm Memorial Church.", 'Breitscheidplatz market, then Charlottenburg Palace market under the lights - or a day in Potsdam instead.'],
  ],
 },
 'tips': [
  {'title': 'Plan by area', 'text': "Berlin has no single centre and a walk that looks like five minutes can take twenty. Group your days by area and buy a 24-hour or small-group ticket."},
  {'title': 'Book the Reichstag and TV Tower', 'text': "The Reichstag dome is free but books up weeks ahead and needs photo ID. TV Tower slots sell out in December - book online."},
  {'title': 'Carry cash', 'text': "Many market stalls, döner shops, bakeries and toilets are cash only. Use a bank ATM, not Euronet. Mug deposits were €5 at the big markets in 2025."},
  {'title': 'Sundays and holidays', 'text': "Shops close on Sundays (except 6 and 20 December 2026, 13:00-20:00) and on 25, 26 December and 1 January; on 24 December they close at 14:00. Most museums close on Mondays."},
  {'title': 'Stamp your ticket', 'text': "No barriers, plain-clothes inspectors, €60 fine. Stamp paper tickets before your first ride, or use the BVG app."},
  {'title': 'Mind the bike lanes', 'text': "Cycle lanes often run on the pavement. Keep children on the footpath side and wait for the green man."},
 ],
 'tips_intro': "Every tip here was checked against an official or trusted source (BVG, VBB, Berlin police, berlin.de, visitBerlin, the Bundestag, gov.uk and others) on the date shown. Rules and prices change, so tap the link to double-check before you travel.",
 'christmas': {
  'intro': "Berlin has more Christmas markets than any other German city - creators count 60 to 90 - from the elegant Gendarmenmarkt to fairground markets with skating and a flying Santa. Most of the big central ones open on 23 November 2026 and several run past Christmas into the New Year. Markets are packed on evenings and weekends. After the 2016 attack at Breitscheidplatz, remembered by a memorial on the square, the big markets are protected by bollards, police patrols and, at Breitscheidplatz, a knife ban.",
  'markets': [
   {'name': 'WeihnachtsZauber Gendarmenmarkt', 'area': 'Gendarmenmarkt, Mitte', 'when': '23 Nov - 31 Dec 2026 · daily from 11:00 or 12:00 to 22:00, Fri/Sat to 23:00 (sources differ) · 24 Dec 12:00-18:00', 'why': "Berlin's most elegant market, back on its own square between the two cathedrals and the Konzerthaus: quality crafts, stage shows, costumed characters and sit-down food booths (some need booking). The only big market with an entry fee, which goes partly to charity. Half a roast chicken was €12.50 in 2025.", 'family': True, 'price': '€2 entry · free weekdays at midday, on 24-26 Dec and for under 12s · NYE €9', 'crowds': "Crowded on evenings and weekends, and even on 24 December. Bags over 15 litres, weapons and dogs aren't allowed, and there's no left luggage.", 'creators': ['traveltimedj0r', 'adventurousale', 'travelsofsarah', 'globaldiscover', 'somewherewego', 'easyjetholiday', 'probablylost', 'zcrexpy'], 'url': 'https://www.weihnachtsmarkt-berlin.de'},
   {'name': 'Berliner Weihnachtszeit (Rotes Rathaus)', 'area': 'Neptune Fountain, Mitte', 'when': '23 Nov 2026 - 3 Jan 2027 · Mon-Fri 12:00-22:00, Sat-Sun 11:00-22:00 · closed 24 Dec', 'why': "The big family market under the TV Tower: an ice rink round the Neptune Fountain, a 50 m Ferris wheel, carousels and a Santa sleigh that flies over the stalls. The best food choice of the big markets - cheese soup in a bread bowl, Handbrot, half-metre bratwurst, and the only blood-sausage stand creators found. In 2025 Glühwein was €5 plus a €5 mug deposit and a bratwurst €7.50.", 'family': True, 'price': 'Free entry · ice rink €5, skate hire €3 · Ferris wheel €7.50 adult, €21 family (2024)', 'crowds': "Usually crowded but wide; long waits for skating. No indoor space to warm up.", 'creators': ['ann', 'heresgood', 'ilaydaen', 'moodifoodiberl', 'traveltimedj0r', 'easyjetholiday', 'streetfoodhub', 'globaldiscover'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Alexanderplatz Christmas market', 'area': 'Alexanderplatz', 'when': '23 Nov - 26 Dec 2026 · 11:00-22:00 daily · 24 Dec hours not yet published', 'why': "Big, loud and lively, beside the TV Tower and World Clock: rides, a children's skating rink, Santa's house, a giant Christmas pyramid and good indoor bars to warm up. Split by a tram line, so it feels less cosy.", 'family': True, 'price': 'Free entry · mug deposit €5 (2025)', 'crowds': "Crowded almost all the time and too much in the evening for some creators. It is on the police hotspot list, so keep phones and bags close.", 'creators': ['traveltimedj0r', 'adventurousale', 'ann', 'shubhravlogz', 'globaldiscover', 'mashtagbrady', 'georgewalkingt'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Breitscheidplatz (Kaiser Wilhelm Memorial Church)', 'area': "Ku'damm, Charlottenburg", 'when': '23 Nov 2026 - 3 Jan 2027 · 2025 hours: 11:00-21:00, Fri/Sat to 22:00, 24 Dec 11:00-14:00', 'why': "The big west-side market round the ruined church, mostly food and hot drinks with good desserts. A memorial set into the ground, 'Der Riss', marks the 2016 attack. In 2025 police added bollards, a mobile police station and a knife ban, and the organisers about 20 security staff.", 'family': True, 'price': 'Free entry', 'crowds': "Busy but flowing; best at 2-3pm, packed after 6pm.", 'creators': ['somewherewego', 'traveltimedj0r', 'ilaydaen'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Charlottenburg Palace Christmas market', 'area': 'Schloss Charlottenburg', 'when': '23 Nov - 27 Dec 2026 · Mon-Thu 13:00-22:00, Fri-Sun 12:00-22:00 · closed 24 Dec', 'why': "Creators' favourite for atmosphere: about 250 well-spaced stalls in front of the lit palace, away from traffic, with raclette, langos, grilled salmon and an excellent bratwurst. Calmer and slower than the centre. A 15-minute walk from the U-Bahn.", 'family': True, 'price': 'Free entry · sausage €7 (2024)', 'crowds': 'Relaxed and less crowded; best after dark for the lights.', 'creators': ['traveltimedj0r', 'probablylost', 'adventurousale', 'foodtour', 'globaldiscover', 'travelsofsarah'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Humboldt Forum winter market', 'area': 'Schlossplatz, Mitte', 'when': '18 Nov 2026 - 3 Jan 2027 · hours not yet published', 'why': "A newer market between the Humboldt Forum and the cathedral, with light projections, wooden stalls, a fairy-tale village inside and international food (langos about €9 in 2024). Adventurous Alex and Olena's favourite.", 'family': True, 'price': 'Free entry', 'crowds': 'The calmest of the central markets; after-work crowds in the evening. One stop or eight minutes on foot from the Rotes Rathaus.', 'creators': ['adventurousale', 'heresgood', 'traveltimedj0r', 'easyjetholiday', 'inandaround'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Lucia Christmas market (Kulturbrauerei)', 'area': 'Prenzlauer Berg', 'when': '23 Nov - 22 Dec 2026 · Mon-Fri 15:00-22:00, Sat-Sun 13:00-22:00', 'why': "A Scandinavian-themed market in the courtyards of an old brewery, with Swedish glögg, Finnish Glühwein and heated yurts. Handy if you're staying in Prenzlauer Berg.", 'family': True, 'price': 'Free entry', 'crowds': 'Local and cosy.', 'creators': ['probablylost', 'easygerman'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Winterwelt Potsdamer Platz', 'area': 'Potsdamer Platz', 'when': 'From 31 Oct 2026 (slide) to late Dec · 11:00-22:00 · 24 Dec to 16:00', 'why': "Small market with a winter slide where you ride down on rubber rings, plus sledging and a teacup ride for little ones. Children love it; adults found it less festive.", 'family': True, 'price': 'Free entry · slide paid', 'crowds': 'Not usually crowded. Cash-only stalls reported in earlier years.', 'creators': ['colinandmeg', 'ann', 'adventurousale', 'globaldiscover'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Spandau old-town market', 'area': 'Spandau', 'when': '23 Nov - 22 Dec 2026 · Sun-Thu 11:00-20:00, Fri/Sat 11:00-22:00', 'why': "One of the largest and most traditional, filling the medieval old town with up to 400 stalls at weekends, a stage and a live-animal nativity. About 25-30 minutes from the centre.", 'family': True, 'price': 'Free entry', 'crowds': 'Quiet on weekdays early in the season; busy at weekends.', 'creators': ['globaldiscover', 'probablylost'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'All-you-can-eat Christmas market', 'area': 'Near the Oberbaumbrücke, Friedrichshain', 'when': '2026 dates and prices not checked', 'why': "A ticketed market where a timed slot buys unlimited food and drink - Käsespätzle, Flammkuchen, waffles, goulash and Glühwein. Creators paid about €35-50 depending on slot length in 2024-25; slots sold out, so they booked a week ahead.", 'family': True, 'price': 'About €35-50 per adult (2024-25)', 'crowds': "Capacity is capped, but popular stalls had 20-30 minute queues. Some creators thought it worth it, others not for a special trip.", 'creators': ['nevermeetyouri', 'faroooyt', 'betelsfoodfeas', 'extradasmagazi'], 'url': maps('All you can eat Weihnachtsmarkt Friedrichshain')},
   {'name': 'Christmas Avenue (Nollendorfplatz)', 'area': 'Schöneberg', 'when': '2026 dates not checked', 'why': "A queer-community Christmas market at Nollendorfplatz station since 2019. Adults and over-16s only.", 'family': False, 'price': 'Check before you go', 'crowds': 'Evening crowd.', 'creators': ['dwtravel'], 'url': maps('Christmas Avenue Nollendorfplatz')},
  ],
  'sights': [
   {'name': 'Christmas Garden (Botanic Garden)', 'area': 'Steglitz', 'when': '18 Nov 2026 - 10 Jan 2027 · from 16:20 · closed on some days incl. 24 and 31 Dec', 'why': "An illuminated evening trail through the Botanic Garden with timed entry. Book online - it's €2 dearer at the gate.", 'family': True, 'price': '€16.90-27.90 · child 6-14 €12.90-23.90 · under 6 free (2026, varies by date)', 'crowds': 'Timed slots keep it manageable.', 'creators': ['radicalliving'], 'url': 'https://www.christmas-garden.de/berlin'},
   {'name': 'Tierpark Christmas lights', 'area': 'Friedrichsfelde (east Berlin)', 'when': '20 Nov 2026 - 9 Jan 2027 · hours not yet published', 'why': "A lights trail in Europe's largest landscape zoo. Prices not yet published.", 'family': True, 'price': 'Price not published', 'crowds': 'Evenings.', 'creators': [], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'The flying Santa at the Rotes Rathaus', 'area': 'Neptune Fountain, Mitte', 'when': 'Several times each evening (Lou\'s Home saw one at about 8:30pm in 2025)', 'why': "Santa and his sleigh fly on a wire over the market - the moment children talk about afterwards.", 'family': True, 'price': 'Free', 'crowds': 'The market is busiest around the shows.', 'creators': ['easyjetholiday', 'loushome', 'ann'], 'url': 'https://www.visitberlin.de/en/christmas-markets-berlin'},
   {'name': 'Reichstag dome after dark', 'area': 'Tiergarten', 'when': 'Book ahead · closed 24 Dec', 'why': "Wolters World recommends the dome at night, with the city lit up below. Free, but book and bring photo ID.", 'family': True, 'price': 'Free', 'crowds': 'Timed entry.', 'creators': ['woltersworld', 'stevemarsh'], 'url': 'https://www.bundestag.de/besuche/kuppel'},
   {'name': 'Midnight Christmas Eve service at the Berliner Dom', 'area': 'Museum Island', 'when': '24 Dec · 2026 times not yet published', 'why': "Indian Travel Vlogger went to the midnight service and found it peaceful even without understanding German (2025).", 'family': False, 'price': 'Check the Dom website', 'crowds': 'Arrive early.', 'creators': ['indiantravelvl'], 'url': 'https://www.berlinerdom.de'},
  ],
  'safety': [
   {'title': 'Crowds and timing', 'text': "The big central markets are packed on evenings and weekends. Go in the early afternoon on a weekday - Breitscheidplatz is best at 2-3pm - and come back after dark for the lights. The Humboldt Forum and Charlottenburg Palace markets are the calmest.", 'creators': ['somewherewego', 'happytowandert', 'mytravelbf', 'adventurousale']},
   {'title': 'Pickpockets: fewer, but still the main risk', 'text': "Pickpocketing fell 14.6% in 2025, but police still warn about crowds, stations and supermarkets, and ran a pickpocket prevention week in October 2026. At Breitscheidplatz they advised leaving large amounts of cash at home and carrying wallets under clothing. Keep phones in front pockets at markets and on the U-Bahn.", 'creators': ['americansinger', 'islandhoppertv']},
   {'title': 'Security and knife bans', 'text': "In 2025 Breitscheidplatz had bollards, a mobile police station, plain-clothes patrols, a knife ban and private security; police said they had no indications of a concrete threat. Gendarmenmarkt bans weapons and bags over 15 litres. Knives are also banned on all public transport. 2026 security plans had not been published by early October; FCDO advises being vigilant in crowded places.", 'creators': []},
   {'title': 'Cash, cards and deposits', 'text': "Many stalls are cash only - Potsdamer Platz and the RAW medieval market were in earlier years - while Gendarmenmarkt takes cards in its food areas. Mug deposits were €5 at Alexanderplatz and the Rotes Rathaus in 2025; keep the token and return the mug, or keep it as a souvenir. A normal visit with two dishes and two drinks is about €30 a person.", 'creators': ['adventurousale', 'colinandmeg', 'ilaydaen', 'nevermeetyouri', 'happytowandert']},
   {'title': 'Cold and dark', 'text': "It's dark by about 4pm in December. Creators saw freezing days and snow, but rain is more likely. Most markets are standing only, so wear layers, gloves and waterproof shoes, and look for markets with indoor bars - Alexanderplatz has good ones.", 'creators': ['easygerman', 'mytravelbf', 'ann', 'loushome']},
   {'title': 'Have a lost-child plan', 'text': "Before you go in, agree a meeting point everyone can find - at the Rotes Rathaus market the main door of the town hall works well. A Wiley Fox QR wristband on each child means anyone who finds them can reach you straight away.", 'creators': []},
   {'title': "New Year's Eve", 'text': "Berlin's New Year is loud. In 2025/26 fireworks were banned in four zones (Alexanderplatz, Steinmetzkiez, Sonnenallee and Admiralbrücke), about 3,200 extra police were on duty and 35 officers were hurt; about 20,000 people at the Brandenburg Gate party had no special incidents. The 2026/27 rules are not out yet. With children, watch from a distance and stay out of the side streets after midnight.", 'creators': []},
  ],
  'plan': "In 2026 most big markets open on 23 November. Gendarmenmarkt runs to 31 December and the Rotes Rathaus and Breitscheidplatz to 3 January; Lucia and Spandau end on 22 December. On 24 December the Rotes Rathaus and Charlottenburg markets are closed, Breitscheidplatz closes early and Gendarmenmarkt is free; shops close at 14:00 and the Reichstag dome is closed. Shops open on Sundays 6 and 20 December. Book hotels and the Reichstag dome early.",
 },
 'map_intro': "Germany doesn't publish street-level crime data, so this map shows the markets and sights in this guide and the places Berlin police have named as high-crime areas or knife ban zones.",
 'map_pins': [
  {'n': 'Gendarmenmarkt', 'lat': 52.5138, 'lng': 13.3927, 'kind': 'market', 'note': '23 Nov - 31 Dec; €2 entry.'},
  {'n': 'Berliner Weihnachtszeit (Rotes Rathaus)', 'lat': 52.5194, 'lng': 13.4072, 'kind': 'market', 'note': 'Ice rink, Ferris wheel, flying Santa. Closed 24 Dec.'},
  {'n': 'Alexanderplatz market', 'lat': 52.5217, 'lng': 13.4130, 'kind': 'market', 'note': '23 Nov - 26 Dec. Police hotspot - watch your bags.'},
  {'n': 'Breitscheidplatz market', 'lat': 52.5049, 'lng': 13.3355, 'kind': 'market', 'note': '23 Nov - 3 Jan. Best at 2-3pm.'},
  {'n': 'Charlottenburg Palace market', 'lat': 52.5203, 'lng': 13.2958, 'kind': 'market', 'note': 'Calmer; closed 24 Dec.'},
  {'n': 'Humboldt Forum winter market', 'lat': 52.5175, 'lng': 13.4020, 'kind': 'market', 'note': 'The calmest central market.'},
  {'n': 'Lucia market (Kulturbrauerei)', 'lat': 52.5389, 'lng': 13.4127, 'kind': 'market', 'note': 'Scandinavian; to 22 Dec.'},
  {'n': 'Winterwelt Potsdamer Platz', 'lat': 52.5093, 'lng': 13.3753, 'kind': 'market', 'note': 'Winter slide for kids.'},
  {'n': 'Brandenburg Gate', 'lat': 52.5163, 'lng': 13.3777, 'kind': 'sight', 'note': 'Go early or after dark; pickpockets in crowds.'},
  {'n': 'Reichstag dome', 'lat': 52.5186, 'lng': 13.3762, 'kind': 'sight', 'note': 'Free; book ahead with ID.'},
  {'n': 'Museum Island', 'lat': 52.5200, 'lng': 13.3980, 'kind': 'sight', 'note': 'Museumsinsel ticket €24; under 18 free.'},
  {'n': 'TV Tower', 'lat': 52.5208, 'lng': 13.4094, 'kind': 'sight', 'note': 'From €20 online.'},
  {'n': 'Berlin Wall Memorial', 'lat': 52.5352, 'lng': 13.3903, 'kind': 'sight', 'note': 'Free; best place to understand the Wall.'},
  {'n': 'East Side Gallery', 'lat': 52.5050, 'lng': 13.4397, 'kind': 'sight', 'note': 'Free, open all the time.'},
  {'n': 'Görlitzer Park', 'lat': 52.4964, 'lng': 13.4376, 'kind': 'caution', 'note': 'Police hotspot and knife ban zone; open at night again.'},
  {'n': 'Kottbusser Tor', 'lat': 52.4991, 'lng': 13.4181, 'kind': 'caution', 'note': 'Police hotspot and knife ban zone.'},
  {'n': 'Warschauer Brücke', 'lat': 52.5057, 'lng': 13.4488, 'kind': 'caution', 'note': 'Police hotspot; busiest late at weekends.'},
  {'n': 'Hermannplatz', 'lat': 52.4868, 'lng': 13.4245, 'kind': 'caution', 'note': 'Police hotspot (with Hermannstraße).'},
  {'n': 'Leopoldplatz', 'lat': 52.5464, 'lng': 13.3594, 'kind': 'caution', 'note': 'Knife ban zone.'},
 ],
 'map': {'center': [13.385, 52.513], 'zoom': 12.4},
 'creators': creators,
 'sources': sources,
}
# sanity: every creator key referenced exists
refs = set()
def walk(x):
    if isinstance(x, dict):
        for k, v in x.items():
            if k == 'creators' and isinstance(v, list): refs.update(v)
            elif k == 'source' and isinstance(v, str) and v.islower(): refs.add(v)
            else: walk(v)
    elif isinstance(x, list): [walk(i) for i in x]
walk({k: v for k, v in G.items() if k != 'creators'})
missing = sorted(r for r in refs if r not in creators)
print('creators', NC, 'videos', NV, 'missing keys:', missing)
json.dump(G, open(f'{D}/guide.json', 'w'), ensure_ascii=False, indent=1)
json.dump({'tips': tips}, open(f'{D}/tips.json', 'w'), ensure_ascii=False, indent=1)
