# Builds chi/guide.json for the Chicago Christmas 2026 guide from researched content + creator DB export.
import json, re, collections, urllib.parse
D = '/home/claude/cityguide/chi'
api = json.load(open(f'{D}/api.json'))
tips = json.load(open(f'{D}/tips.json'))['tips']
costs = json.load(open(f'{D}/costs.json'))
key = lambda n: re.sub(r'[^a-z0-9]', '', n.lower())[:14]
maps = lambda q: 'https://www.google.com/maps/search/?api=1&query=' + urllib.parse.quote(q + ' Chicago')
book = lambda q: 'https://www.booking.com/searchresults.html?ss=' + urllib.parse.quote(q + ' Chicago') + '&aid=YOUR_AID_HERE'

# creators + sources from the DB export (only videos that yielded facts)
# No channels excluded for Chicago.
EXCLUDE = set()
for k in list(api['facts']):
    api['facts'][k] = [f for f in api['facts'][k] if key(f['creator']) not in EXCLUDE]
srcs = {s['id']: s for s in api['sources']}
used, cnt = {}, collections.Counter()
for v in api['facts'].values():
    for f in v:
        used.setdefault(f['source_id'], f['creator']); cnt[f['creator']] += 1
creators = {}
for sid, name in used.items():
    creators.setdefault(key(name), {'name': name, 'url': srcs.get(sid, {}).get('url') or f'https://www.youtube.com/watch?v={sid[3:]}'})
sources = sorted([{'creator': used[sid], 'creator_url': creators[key(used[sid])]['url'], 'title': s['title'], 'url': s['url'], 'date': (s.get('published_at') or '')[:7]}
                  for sid, s in srcs.items() if sid in used], key=lambda x: x['creator'].lower())
NC, NV = len(creators), len(sources)
CT = json.load(open(f'{D}/chi_crime.json'))['areas']
G = {
 'city': 'Chicago', 'slug': 'chicago', 'country': 'USA', 'edition': 'Christmas 2026 edition', 'updated': '2026-10-05',
 'status': "Draft for Barry's approval", 'audience': 'Families and solo travellers',
 'tagline': 'The Wiley Fox guide to Chicago for families and solo travellers',
 'cover_blurb': f'What {NC} travel creators actually say about Chicago, checked against the city\'s own street-level crime data - a German Christmas market under the skyscrapers, free skating, the zoo lights, where to stay, what to eat, and where to take care.',
 'banner_text': 'Official travel advice for 200+ countries, community reports, one-tap SOS, and QR wristbands so lost children and lost bags find their way back.',
 'safety': {
  'wf_rating': 3, 'wf_label': 'Moderate',
  'wf_summary': "Chicago's reputation comes from gun violence, and that violence is real - 416 homicides in 2025 - but it is heavily concentrated in residential neighbourhoods on the South and West Sides, miles from where visitors stay. It is also falling fast: homicides fell 29% in 2025 to the lowest level since 1965, shooting victims fell 34% and robbery 36% (Chicago Police). In 2026 so far, recorded crime is down a further 9% in the downtown Central district and 7% in the Near North district that covers the Magnificent Mile. Downtown, the main risks for visitors are theft, pickpocketing and street scams, which cluster where the crowds are. Two things to plan for at Christmas: the Loop empties after office hours, and large unsupervised teen gatherings after big evening events have turned violent - on the night of the 2025 tree lighting, seven teenagers were shot near State Street and a 14-year-old was killed a few blocks away. This rating is for the city as a whole; check the area figures below for where you stay.",
  'creator_feeling': 4, 'creator_feeling_label': 'Comfortable downtown - quiet after dark',
  'creator_summary': "Most creators found downtown Chicago clean, walkable and safer than its reputation; several compared it favourably with New York, and solo women (LifeWithDayy, NK Medani, Izzy Bisges) felt comfortable by day and on the L. Locals keep repeating the same advice: the Loop is a ghost town after about 6-7pm, avoid empty train carriages late at night (the bus is safer because the driver can see you), and ignore anyone on the street asking for money for a ticket or a 'donation'. Pickpockets work Michigan Avenue, Navy Pier and L platforms. Creators who explored the South Side by day (CityNerd, Luis Gusto, Peter Santenello) found it calmer than the headlines, but advise staying alert and knowing where you are.",
  'data_note': "Area figures are the monthly average of crimes recorded by Chicago Police from June to August 2026 within about one mile of each area centre (City of Chicago Data Portal, the latest three complete months). Locations are published to block level. Summer months are busier than December, and busy downtown areas record more crime partly because so many people pass through them - River North, the Loop, Millennium Park and the Magnificent Mile circles overlap, so read them as one zone. Chicago counts incidents differently from New York, so do not compare these numbers with our New York guide. Citywide trends come from the Chicago Police 2025 year-end review and the Data Portal (January to 27 September 2026 against the same period in 2025).",
  'data_months': ['2026-08', '2026-07', '2026-06'],
 },
 'official_crime': [
  {'number': '-29%', 'label': 'Homicides in 2025 (416)', 'desc': 'The lowest since 1965. Shooting victims fell 34% and robbery 36% (Chicago Police, 2025 in review).'},
  {'number': '-9%', 'label': 'Recorded crime downtown, 2026 so far', 'desc': 'Central police district (the Loop, Millennium Park), January to September 2026 against 2025. Theft down 13%. The Near North district fell 7%.'},
  {'number': '6pm', 'label': 'Millennium Park under-18 rule', 'desc': 'From 6pm, Friday to Sunday, under-18s must be with an adult aged 21 or over (City of Chicago).'},
 ],
 'crime_table': CT,
 'crime_source': {'name': 'Chicago Police Department, Crimes data (City of Chicago Data Portal)', 'citation': "Crimes recorded by Chicago Police from June to August 2026, counted within about one mile of each area centre, plus the Police 2025 year-end review and Data Portal trends to 27 September 2026. These are reports, not convictions; they include indoor and domestic incidents, and are not adjusted for the visitors and commuters who pass through busy areas."},
 'app_ctas': [
  {'where': 'before_booking', 'text': "Chicago publishes street-level crime data, and the Wiley Fox map shows it hex by hex. Before you book, check your hotel's block - the difference between the Magnificent Mile and a quiet street a mile west can be large.", 'url': 'https://www.thewileyfox.com'},
  {'where': 'families', 'text': 'Clip a Wiley Fox QR wristband on each child. If you get separated in the Christkindlmarket queue or at the tree, anyone who scans it can contact you straight away - no app needed on their side.', 'url': 'https://www.thewileyfox.com'},
  {'where': 'night', 'text': "The Loop goes quiet after dark. Save your hotel on Wiley Fox, stick to lit, busy streets or take the bus, and keep SOS one tap away.", 'url': 'https://www.thewileyfox.com'},
  {'where': 'community', 'text': 'Spotted a "donation" scam, a closed rink or a street that felt wrong? Drop a community report on the map - it helps the next family.', 'url': 'https://www.thewileyfox.com'},
 ],
 'stats': [
  {'number': '20 Nov', 'label': 'Christkindlmarket and tree lighting 2026', 'desc': 'The Daley Plaza market runs 20 November to 24 December; the city tree is lit in Millennium Park at 6pm the same Friday.'},
  {'number': '$5', 'label': 'A 1-day CTA pass', 'desc': 'Unlimited L trains and buses for 24 hours. A 3-day pass is $15 and a 7-day pass $20 (CTA, Oct 2026). Tap a contactless card to ride.'},
  {'number': str(NC), 'label': f'Creators · {NV} videos', 'desc': 'Paraphrased and credited, cross-checked with police data.'},
 ],
 'overview': [
  "Chicago is a big, flat grid on the shore of Lake Michigan. Visitors spend most of their time in a compact area: the Loop (the business district inside the elevated L tracks, with Millennium Park and the Art Institute), River North and the Magnificent Mile just across the river, Streeterville and Navy Pier by the lake, and the Museum Campus to the south. The L trains, buses and the lakefront make it easy to reach neighbourhoods like Lincoln Park, Wicker Park, Chinatown and Pilsen. Creators suggest three or four days.",
  "At Christmas the city puts on a big show: the German-style Christkindlmarket on Daley Plaza (in its 30th year in 2026), a 60-foot tree and free skating in Millennium Park, a skating ribbon in Maggie Daley Park, the Magnificent Mile Lights Festival parade, ZooLights at the free Lincoln Park Zoo, Macy's Walnut Room and Christmas Around the World at the Museum of Science and Industry. Families get huge, hands-on museums for cold days.",
  "For solo travellers downtown is easy, friendly and walkable, and creators - women included - mostly felt safe. Plan for the cold (wind off the lake makes freezing days feel far colder), early darkness (sunset about 4:20pm), a Loop that empties in the evening, late-night trains, and a sales tax that is never on the price tag.",
 ],
 'facts': {
  'Currency': 'US dollar (USD) - cards and phone pay work almost everywhere, but many Christkindlmarket food stalls have been cash only; tax is added at the till',
  'Language': 'English',
  'Time zone': 'Central Time (UTC-6) - six hours behind the UK in December',
  'Plug': 'Type A and B, 120V - UK plugs need an adaptor; check chargers are dual voltage',
  'Emergency': '911 police, fire and ambulance · 311 police non-emergency and city services (24 hours)',
  'Entry': "UK passport plus an approved ESTA before you fly - the official fee is $40.27 on esta.cbp.dhs.gov; other sites charge more (CBP, Oct 2026)",
  'Tipping': 'About 18-20% in restaurants is usual (staff earn a lower base wage); check the bill for service charges first',
  'Best time': 'Late November to 23 December for the Christmas events (weekday mornings are calmest); May-June and September for the lakefront',
 },
 'stay': [
  {'area': 'River North', 'for': ['First-timers', 'Families', 'Nightlife'], 'why': "The most recommended base: just north of the river, walkable to the Loop, the Magnificent Mile and the Riverwalk, with big hotels, deep-dish pizza and bars. Pricey and busy near Michigan Avenue, and the area records some of the city's highest theft counts because of the crowds - keep phones close. The Red Line stops at Grand and Chicago.", 'crime': CT['River North'], 'creators': ['traveltipsgrou', 'samuelciochony', 'camdendavid', 'cairabutton', 'misstourist', 'trovexgo']},
  {'area': 'The Loop', 'for': ['Christmas markets', 'Museums', 'Short stays'], 'why': "About 80% of the main sights are here - the Christkindlmarket, Millennium Park, the Art Institute - and every L line except the Yellow stops here. Hotels are fewer and pricier, and creators warn it empties after 6-7pm and at weekends, so it can feel deserted at night. Through My Lens found a Cambria hotel a block from the market for under $100 a night in early December 2023.", 'crime': CT['The Loop (Daley Plaza)'], 'creators': ['traveltipsgrou', 'camdendavid', 'woltersworld', 'misstourist', 'throughmylens']},
  {'area': 'Magnificent Mile & Streeterville', 'for': ['Shopping', 'Families', 'Hotel choice'], 'why': "Michigan Avenue north of the river, with the most hotel choice, the Christmas lights, Water Tower Place and Navy Pier ten minutes east. Hotels here are often cheaper than the Loop. Camden David says Streeterville is far from the L and not special for a first visit, and the street scams creators warn about cluster around Michigan Avenue.", 'crime': CT['Magnificent Mile'], 'creators': ['traveltipsgrou', 'misstourist', 'tripxtreme', 'camdendavid', 'ashlynneeaton']},
  {'area': 'South Loop', 'for': ['Families', 'Budget', 'Museums'], 'why': "South of the Loop beside Grant Park and the Museum Campus (Field Museum, Shedd Aquarium, Adler Planetarium). Hotels on South Michigan Avenue can be cheaper, Printers Row has good food, and the HI Chicago hostel is here. Further from the Magnificent Mile and quieter at night.", 'crime': CT['South Loop'], 'creators': ['misstourist', 'roamingroutes', 'cairabutton', 'traveltipsgrou']},
  {'area': 'Lincoln Park & Old Town', 'for': ['Families', 'Quiet nights', 'Zoo'], 'why': "Leafy, residential and described by every creator as safe, with the free zoo, ZooLights, the conservatory and the lakefront on the doorstep; Old Town has Second City comedy. A little far from the downtown action - 15-20 minutes on the Brown or Red Line or bus 151.", 'crime': CT['Lincoln Park'], 'creators': ['toursbyfootchi', 'chismprism', 'misstourist', 'camdendavid', 'samuelciochony']},
  {'area': 'West Loop & Fulton Market', 'for': ['Food', 'Solo travellers', 'Couples'], 'why': "Chicago's restaurant row on Randolph Street and Fulton Market, with design hotels like the Hoxton. Safe and busy by day, but the bridge walks from the Loop can feel isolated at night - Tours by Foot suggests a taxi when alone. The Pink and Green Lines serve it.", 'crime': CT['West Loop / Fulton Market'], 'creators': ['camdendavid', 'toursbyfootchi', 'zanderspringer', 'cairabutton', 'misstourist']},
 ],
 'caution': [
  {'area': 'The Loop after dark and after big events', 'when': 'Evenings, especially after the tree lighting and other big events', 'note': "The Loop is a business district that empties after 6-7pm, so stick to lit, busy streets. On 21 November 2025, after the Millennium Park tree lighting, a large 'teen takeover' gathering near State Street ended with seven teenagers shot near the Chicago Theatre and a 14-year-old killed on Dearborn Street. Millennium Park now requires under-18s to be with an adult aged 21+ after 6pm, Friday to Sunday, with bag checks at the Michigan Avenue gates. With children, enjoy the early evening and head back as crowds of teenagers build.", 'crime': CT['The Loop (Daley Plaza)'], 'creators': ['woltersworld', 'curio', 'thedcshorts', 'camdendavid']},
  {'area': 'Magnificent Mile, Streeterville and Navy Pier', 'when': 'Busy afternoons and evenings', 'note': "Pickpockets work the crowds around Michigan Avenue, street performers, Navy Pier and L platforms. A shell game runs off the Mile in Streeterville, and the 'tap-to-pay donation' scam has been reported on East Ohio Street (June 2026). Keep bags zipped and wallets in front pockets, and never hand your phone or card to a stranger.", 'crime': CT['Magnificent Mile'], 'creators': ['woltersworld', 'toursbyfootchi', 'cbschicago', 'nbcchicago']},
  {'area': 'L trains late at night', 'when': 'Late evening and night', 'note': "The CTA says crime on trains fell sharply in 2026 after a security surge, but police data showed serious assaults on the system at a 24-year high in 2025, and creators still describe smoking, drug use and the odd attack on Red and Blue Line trains. At night, pick a busy carriage near the driver (the first car), avoid empty ones, or take the bus, where the driver can see you.", 'creators': ['toursbyfootchi', 'chicagolikealo', 'chismprism', 'adultingwithan', 'abc7chicago']},
  {'area': 'Union Station and transport hubs', 'when': 'Any time', 'note': "Wolters World says that on nearly every visit someone has approached with a story about needing money for a train ticket to Milwaukee or a bus. Say no and keep walking, or offer to go to the ticket office with them.", 'crime': CT['Union Station'], 'creators': ['woltersworld']},
  {'area': 'Bridges into the West Loop at night', 'when': 'Late night', 'note': "The West Loop is busy and well used, but the walk over the river bridges from the Loop or River North can be isolated after dark. Take a taxi or rideshare when alone. In 2025 the Fulton Market business association warned of fake parking attendants in hi-vis vests charging drivers $20.", 'crime': CT['West Loop / Fulton Market'], 'creators': ['toursbyfootchi', 'cbschicago']},
  {'area': 'Unfamiliar South and West Side neighbourhoods', 'when': 'After dark', 'note': "Most of Chicago's violence happens in residential neighbourhoods on the South and West Sides, well away from the visitor areas. Places visitors go - Hyde Park and the Museum of Science and Industry, Chinatown, Pilsen, Bridgeport - are fine by day, and creators who explored further found them calmer than the headlines. Don't wander blocks you don't know after dark, and keep nothing on show in a parked car.", 'creators': ['luisgusto', 'citynerd', 'petersantenell', 'viptripdeals', 'woltersworld']},
  {'area': 'Winter streets and the lakefront', 'when': 'December to March', 'note': "Snow and ice can slide off tall buildings downtown - don't stand underneath for photos. Wind off the lake makes it feel far colder than the thermometer says, and ice on the lake and harbours is never safe. Drivers are aggressive at crossings, and fast e-bikes use the lakefront path.", 'creators': ['woltersworld', 'lukegeetravels', 'luisgusto', 'cbschicago']},
 ],
 'scams': [
  {'title': "The 'tap-to-pay donation'", 'text': "Strangers ask for a small donation, often for a funeral, refuse cash and ask to tap your phone or card - then charge thousands. Reported in Streeterville, the West Loop, Lincoln Park, Wicker Park and Lakeview in 2025-26; banks can refuse refunds because you authorised the payment. The Better Business Bureau says refusing cash is a red flag.", 'creators': ['cbschicago', 'nbcchicago']},
  {'title': 'Shell games and street pitches', 'text': "Card and ball-and-cup games off the Magnificent Mile are rigged, and pickpockets work the crowd that gathers to watch. Downtown you may also be pushed to sign up for dubious subscriptions - keep walking.", 'creators': ['woltersworld', 'cbschicago', 'chismprism']},
  {'title': "Money for a train ticket", 'text': "Sob stories at Union Station and other hubs about needing money for a ticket home. Offer to buy the ticket at the counter with them, or say no.", 'creators': ['woltersworld']},
  {'title': 'Taxis', 'text': "Some drivers claim the card machine is broken and ask for cash - check before you get in. After games at the United Center, unlicensed cabs and flat-rate fares ($40-45 against about $20 on the meter) were reported. Genuine cabs show a roof number that matches the plate; the Curb and Arro apps book licensed taxis.", 'creators': ['woltersworld', 'abc7chicago']},
  {'title': 'Fake parking attendants', 'text': "People in hi-vis vests have waved drivers into private lots in Fulton Market and around Sox games, charging $20-40. Park only in official garages, or use the SpotHero app.", 'creators': ['cbschicago']},
  {'title': 'Bills, fees and upsells', 'text': "The 10.25% sales tax is never on the price tag, restaurants add a 0.5% tax, and some add a service fee or about 3% surcharge - check before tipping. Deep-dish pizzerias push starters you won't need: even a small pizza is very filling.", 'creators': ['traveltipsgrou', 'bradballtravel', 'rithmicasmr', 'woltersworld']},
 ],
 'transport': [
  {'title': 'From the airports', 'text': "From O'Hare, the Blue Line runs 24 hours and takes 40-45 minutes to downtown; boarding at O'Hare costs $5 (free with a pass). From Midway, the Orange Line takes 20-25 minutes for $2.50. A taxi from O'Hare averages about $50, and the city's shared-ride flat fare is $30 a person (Chicago airports, Oct 2026).", 'creators': ['roamingroutes', 'chicagolikealo', 'camdendavid', 'everythingchic']},
  {'title': 'Tickets: just tap', 'text': "A train ride is $2.50 and a bus $2.25, with two free transfers within two hours. Tap a contactless card or phone at the gate - no ticket needed. Passes are $5 for a day, $15 for three days and $20 for seven days in the Ventra app or at airport machines; the 7-day pass covers the O'Hare charge.", 'creators': ['chicagolikealo', 'camdendavid', 'citynerd', 'travelingtaya']},
  {'title': 'Getting round the sights', 'text': "Every L line except the Yellow runs through the Loop; Clark/Lake connects to all of them. For ZooLights take the Brown Line to Sedgwick or bus 151. The Red Line goes to Wrigley Field, and the Metra Electric from Millennium Station to Hyde Park for the Museum of Science and Industry. In cold weather, the Pedway tunnels link some downtown buildings and stations.", 'creators': ['luisgusto', 'citynerd', 'lukegeetravels', 'ashlynneeaton', 'everythingchic', 'toursbyfootchi']},
  {'title': 'Night travel', 'text': "The Red and Blue Lines run 24 hours; other lines run roughly 4am to 1am. Locals prefer the bus late at night because the driver can see you, and say to pad journey times outside rush hour. Rideshares can be near impossible at rush hour - Caira Button gave up at ZooLights and took the bus.", 'creators': ['cairabutton', 'chicagolikealo', 'toursbyfootchi', 'chismprism']},
  {'title': 'Water taxi and bikes', 'text': "The Chicago Water Taxi to Chinatown ($6-10, 2025-26) is a cheap way onto the river, but check winter service. Divvy bikes are $1 to unlock plus 20 cents a minute, or $19.90 for a day (Divvy, Oct 2026) - not much fun in a Chicago December.", 'creators': ['roamingroutes', 'destinations2s', 'camdendavid']},
 ],
 'costs': costs,
 'top_intro': "Ranked by how often creators recommend them. Most are in or near the Loop; in December do the outdoor sights by day (sunset is about 4:20pm) and save the lights for the evening. The famous architecture river cruise runs March to November only.",
 'top': [
  {'name': 'Millennium Park & Cloud Gate', 'area': 'The Loop', 'why': "The Bean, the Crown Fountain and, from 20 November 2026, the city Christmas tree and a free ice rink. Go at 8-9am for the Bean without the crowds - a December weekend afternoon drew about a thousand people. Under-18s need an adult 21+ after 6pm Friday to Sunday.", 'family': True, 'price': 'Free', 'url': maps('Millennium Park'), 'creators': ['epicfamilyesca', 'luisgusto', 'projectgaia', 'curio', 'towntraveltips', 'annika', 'triply']},
  {'name': 'Art Institute of Chicago', 'area': 'The Loop', 'why': "A world-class museum: American Gothic, the Impressionists and the Thorne miniature rooms (decorated at Christmas), with wreaths on the lions outside. Allow at least half a day. Closed on Tuesdays; buy online.", 'family': True, 'price': '$32 adult · children free (2026)', 'url': 'https://www.artic.edu', 'creators': ['woltersworld', 'ashleyalondra', 'ashlynneeaton', 'izzybisges', 'lialavon', 'cbschicago']},
  {'name': 'Willis Tower Skydeck', 'area': 'The Loop', 'why': "103 floors up, with the Ledge glass boxes 1,353 feet above the street - about a minute each. Pricey, and pointless on a cloudy day, so book late or check the forecast. Open every day of the year; early weekday mornings are quietest.", 'family': True, 'price': 'From $32 · child 3-11 from $24 (2026)', 'url': 'https://theskydeck.com', 'creators': ['outsidewithdad', 'curio', 'throughmylens', 'haveclotheswil', 'nkmedani', 'destinations2s', 'woltersworld']},
  {'name': 'Field Museum', 'area': 'Museum Campus', 'why': "Home of Sue, the most complete T. rex found, and the Tsavo lions; families spent most of a day here. Closed on Christmas Day.", 'family': True, 'price': '$30 adult (2026)', 'url': 'https://www.fieldmuseum.org', 'creators': ['outsidewithdad', 'woltersworld', 'dailydroppro', 'annakarltravel', 'towntraveltips']},
  {'name': 'Museum of Science and Industry', 'area': 'Hyde Park', 'why': "Huge and hands-on: a coal mine, a WWII U-boat, a tornado - and from 7 November 2026, Christmas Around the World, with a four-storey tree and dozens of trees decorated by Chicago's communities. Very busy the week before Christmas, so go early.", 'family': True, 'price': '$25.95 adult · child 3-11 $14.95 (2026)', 'url': 'https://www.griffinmsi.org', 'creators': ['woltersworld', 'meanstotravel', 'throughmylens', 'cbschicago', 'united']},
  {'name': 'Lincoln Park Zoo & Conservatory', 'area': 'Lincoln Park', 'why': "One of the few free zoos in the US, open every day, with indoor animal houses for cold days and the free Lincoln Park Conservatory next door (a big poinsettia show in December). In the evening it becomes ZooLights.", 'family': True, 'price': 'Free', 'url': 'https://www.lpzoo.org', 'creators': ['luisgusto', 'travelnavigato', 'crosbygracetra', 'epicfamilyesca', 'cairabutton', 'towntraveltips']},
  {'name': 'Shedd Aquarium', 'area': 'Museum Campus', 'why': "Beluga whales, a Polar Play Zone and the Wild Reef, next to the Field Museum. Prices for non-residents change by date, so check online.", 'family': True, 'price': 'Varies by date - check online', 'url': 'https://www.sheddaquarium.org', 'creators': ['epicfamilyesca', 'meanstotravel', 'samuelciochony']},
  {'name': '360 Chicago', 'area': 'Magnificent Mile', 'why': "The 94th-floor deck of the former John Hancock Center, with lake views and the TILT ride (extra). Curio suggests a drink in the Signature Lounge upstairs for similar views at a similar price.", 'family': True, 'price': 'From $30 · child 3-11 from $20 (2026)', 'url': 'https://360chicago.com', 'creators': ['way2go', 'destinations2s', 'curio', 'haveclotheswil']},
  {'name': 'Navy Pier & the Children\'s Museum', 'area': 'Streeterville', 'why': "Touristy and expensive, but children love the Centennial Wheel and the three-floor Chicago Children's Museum. In winter the indoor Winter WonderFest runs from 27 November 2026, with rides and skating. Watch your belongings.", 'family': True, 'price': 'Free to walk · WonderFest $27 online (2026)', 'url': 'https://navypier.org', 'creators': ['woltersworld', 'epicfamilyesca', 'travelthetop', 'toursbyfootchi', 'trovexgo']},
  {'name': 'The Magnificent Mile', 'area': 'Near North Side', 'why': "A mile of Michigan Avenue from the river to Oak Street: the Wrigley Building and Tribune Tower, the 1869 Water Tower that survived the Great Fire, the huge Starbucks Reserve Roastery and, at Christmas, every tree wrapped in lights. Busy - mind your bag.", 'family': True, 'price': 'Free', 'url': maps('Magnificent Mile'), 'creators': ['ashlynneeaton', 'architecturald', 'samuelciochony', 'lukegeetravels', 'backttalk']},
  {'name': 'Chicago Cultural Center', 'area': 'The Loop', 'why': "The world's largest Tiffany glass dome, free to see, opposite Millennium Park - and clean public toilets on several floors.", 'family': True, 'price': 'Free', 'url': maps('Chicago Cultural Center'), 'creators': ['curio']},
  {'name': 'Maggie Daley Park', 'area': 'The Loop', 'why': "A huge play garden for ages 2-12 by Millennium Park, and in winter a skating ribbon that winds through the trees with skyline views - much less crowded than the Millennium Park rink.", 'family': True, 'price': 'Free to visit · skating ticketed', 'url': 'https://www.maggiedaleypark.com', 'creators': ['epicfamilyesca', 'curio', 'adempseystory', 'travelthetop', 'chadandclaire']},
 ],
 'eat_label': 'Deep dish, Italian beef and a Chicago dog',
 'eat_intro': "Chicago eats big: deep-dish pizza (allow 45 minutes), thin tavern-style squares that locals actually eat, dripping Italian beef and the hot dog 'dragged through the garden' - never with ketchup. Every place is credited to the creator who recommended it, and prices carry the year.",
 'eat': [
  {'name': "Lou Malnati's", 'area': 'River North (Wells & Hubbard) and elsewhere', 'type': 'Deep dish', 'price': '$$', 'family': True, 'why': "The deep dish locals most often recommend, with booth seating and quick service for families; about $20-30 a person (2025).", 'creators': ['toursbyfootchi', 'crosbygracetra', 'traveltipsgrou', 'travelthetop', 'dailydroppro', 'jackxjo'], 'url': maps("Lou Malnati's River North")},
  {'name': "Pequod's Pizza", 'area': 'Lincoln Park', 'type': 'Deep dish', 'price': '$$', 'family': True, 'why': "A dark, caramelised cheese crust that several creators rate the best in the city. It takes 45-60 minutes and is a 17-minute walk from the train.", 'creators': ['johnnytrekkie', 'jeremyjacobowi', 'brianlindo', 'attach', 'arielleyasmine'], 'url': maps("Pequod's Pizza")},
  {'name': "Giordano's", 'area': 'Several downtown', 'type': 'Deep dish', 'price': '$$', 'family': True, 'why': "Stuffed deep dish since 1974; a 10-inch feeds two. Dinner waits can be 1-2 hours, but the lunch special of a ready-made pizza arrives in 10-15 minutes ($13 combo, 2024).", 'creators': ['camdendavid', 'adultingwithan', 'johnnytrekkie', 'chadandclaire'], 'url': maps("Giordano's")},
  {'name': "Pat's Pizza", 'area': 'Lincoln Park', 'type': 'Tavern-style pizza', 'price': '$$', 'family': True, 'why': "The thin, crisp, square-cut pizza Luis Gusto says most Chicagoans actually eat. Order the Pat special.", 'creators': ['luisgusto', 'adamandmadalyn'], 'url': maps("Pat's Pizza Chicago")},
  {'name': "Portillo's", 'area': 'River North and the Loop', 'type': 'Hot dogs & Italian beef', 'price': '$', 'family': True, 'why': "The classic: a Chicago dog, an Italian beef dipped with peppers and a chocolate cake shake. Two dogs, two fries and a shake were $19 in 2024. Check the kiosk total before you pay.", 'creators': ['dailydroppro', 'adultingwithan', 'chadandclaire', 'camdendavid', 'nicolelaeno', 'rithmicasmr'], 'url': maps("Portillo's River North")},
  {'name': 'Mr. Beef', 'area': 'River North', 'type': 'Italian beef', 'price': '$', 'family': False, 'why': "The Italian beef stand made famous by The Bear; order it dipped. Still cash only (2025), with a queue out of the door - two sandwiches were $26 in 2024.", 'creators': ['united', 'thehivedrive', 'dailydroppro', 'ashlynneeaton'], 'url': maps('Mr. Beef on Orleans')},
  {'name': 'Garrett Popcorn', 'area': 'Michigan Avenue and the Loop', 'type': 'Popcorn', 'price': '$', 'family': True, 'why': "Since 1949. The Chicago Mix is caramel and cheese together; a small bag is about $5 (2025), with free samples and a seasonal hot cocoa caramel crisp.", 'creators': ['roselandlashay', 'meanstotravel', 'joeparyseats', 'cbschicago'], 'url': maps('Garrett Popcorn Michigan Avenue')},
  {'name': 'Wildberry Pancakes and Cafe', 'area': 'Randolph Street, opposite Millennium Park', 'type': 'Breakfast', 'price': '$$', 'family': True, 'why': "Fluffy pancakes in many flavours with window seats over the park; about $16 for pancakes and coffee (2025). Expect a wait at weekends.", 'creators': ['roamingroutes', 'lialavon', 'trovexgo', 'traveltipsgrou'], 'url': maps('Wildberry Pancakes and Cafe Randolph')},
  {'name': 'The Berghoff', 'area': 'The Loop', 'type': 'German-American', 'price': '$$', 'family': True, 'why': "Open since 1898, decorated for the holidays, with hearty German food and its own root beer - a warm stop near the Christkindlmarket.", 'creators': ['chadandclaire', 'cbschicago'], 'url': maps('The Berghoff')},
  {'name': "Lou Mitchell's", 'area': 'West Loop, near Union Station', 'type': 'Diner breakfast', 'price': '$$', 'family': True, 'why': "A classic diner breakfast near Union Station; a large breakfast for a group was about $50 (2024).", 'creators': ['dailydroppro'], 'url': maps("Lou Mitchell's")},
  {'name': "Manny's Cafeteria and Deli", 'area': 'South Loop', 'type': 'Jewish deli', 'price': '$', 'family': True, 'why': "A cafeteria-style deli since 1942: huge pastrami on rye at reasonable prices, and cherry pie.", 'creators': ['attach', 'johnnytrekkie'], 'url': maps("Manny's Deli")},
  {'name': 'Chiu Quon Bakery', 'area': 'Chinatown', 'type': 'Chinese bakery', 'price': '$', 'family': True, 'why': "Since 1986: BBQ pork buns and egg tarts for breakfast. Chinatown is cheap, open late and reached by the Red Line or the water taxi.", 'creators': ['luisgusto'], 'url': maps('Chiu Quon Bakery')},
 ],
 'grown_ups': "For a grown-ups' night: a Glühwein at the Christkindlmarket, then Cindy's rooftop above the Millennium Park rink, London House's rooftop by the river (igloos in winter), or the tiki cocktails at Three Dots and a Dash in River North. Wrigleyville's themed Christmas pop-up bars are cheesy fun but busy and pricey, and not for children - book ahead. Second City in Old Town has nightly improv. You must be 21 to drink, and bars ask for photo ID - take your passport or photocard licence.",
 'hotels': [
  {'name': 'The Peninsula Chicago', 'area': 'Magnificent Mile', 'for': 'Luxury', 'band': '$$$$', 'why': "Five-star on the Mile with a rooftop spa and pool and afternoon tea.", 'url': book('The Peninsula Chicago'), 'source': 'toursinminutes'},
  {'name': 'Loews Chicago Hotel', 'area': 'Streeterville', 'for': 'Families', 'band': '$$$', 'why': "A 75-foot pool, free loans of games and pool toys, free cribs, and cookies and cocoa on arrival for families (2022).", 'url': book('Loews Chicago Hotel'), 'source': 'detailsinluxur'},
  {'name': 'DoubleTree by Hilton Magnificent Mile', 'area': 'Streeterville', 'for': 'Families on a budget', 'band': '$$', 'why': "Typically $150-200 a night (2026), near Navy Pier, with a welcome cookie and a pool.", 'url': book('DoubleTree by Hilton Magnificent Mile'), 'source': 'besthotelsandr'},
  {'name': 'Royal Sonesta Chicago River North', 'area': 'River North', 'for': 'Good value, central', 'band': '$$', 'why': "A minute from the Red Line, with an indoor pool; about $170 a night (2024).", 'url': book('Royal Sonesta Chicago River North'), 'source': 'hoteltips'},
  {'name': 'citizenM Chicago Downtown', 'area': 'The Loop', 'for': 'Solo travellers', 'band': '$$', 'why': "Compact, iPad-controlled rooms between the Riverwalk and Millennium Park, good value for one or two - not for families (2025).", 'url': book('citizenM Chicago Downtown'), 'source': 'lialavon'},
  {'name': 'Hotel Versey', 'area': 'Lakeview / Lincoln Park', 'for': 'Quiet & budget', 'band': '$$', 'why': "Quiet, artistic hotel near the zoo and the lake, about $120-170 a night (2026).", 'url': book('Hotel Versey'), 'source': 'besthotelsandr'},
 ],
 'itinerary': {
  '1day': [
   ['08:30', 'Breakfast and the Bean', 'Pancakes at Wildberry, then Cloud Gate before the crowds.'],
   ['10:00', 'Art Institute (not Tuesdays)', 'Two hours with the Impressionists and the festive Thorne rooms.'],
   ['12:00', 'Christkindlmarket at Daley Plaza', 'Arrive near opening on a weekday: bratwurst, pretzels and a mug of hot chocolate.'],
   ['14:00', 'Skydeck or Macy\'s', 'Up the Willis Tower on a clear day, or the Macy\'s windows and Walnut Room tree.'],
   ['16:00', 'Skating as the lights come on', 'Maggie Daley ribbon or the free Millennium Park rink - book a slot.'],
   ['18:00', 'Deep dish and the Mile', "Lou Malnati's (allow 45 minutes), then the lights on Michigan Avenue."],
  ],
  '3day': [
   ['Day 1 · The Loop at Christmas', 'The Bean and the Art Institute.', 'Christkindlmarket and Macy\'s on State Street.', 'Skating and the city tree, then deep dish in River North.'],
   ['Day 2 · Museums', 'Field Museum and Shedd Aquarium on the Museum Campus.', 'Or the Museum of Science and Industry for Christmas Around the World.', 'Lights on the Magnificent Mile, dinner in Chinatown.'],
   ['Day 3 · Neighbourhoods', 'Skydeck on a clear morning.', 'Lincoln Park Zoo and Conservatory (free).', 'ZooLights after dark, or the Wrigleyville Christkindlmarket.'],
  ],
 },
 'tips': [
  {'title': 'Book the timed things', 'text': "Skating slots, the Walnut Room, Skydeck and ZooLights all sell out at Christmas. One creator could only get an 8am skating slot over the 2025 holiday weekend."},
  {'title': 'Dress for the wind', 'text': "Lake wind makes 25°F feel like 10°F. Layers, a hat, gloves, warm boots and hand warmers (from any Walgreens)."},
  {'title': 'Carry some cash', 'text': "Cards and phone pay work almost everywhere, but creators found most Christkindlmarket food stalls cash only - there are ATMs on site, with queues."},
  {'title': 'Tax and tip on top', 'text': "Prices never include the 10.25% sales tax. Tip 18-20% in restaurants, but check for a service charge first."},
  {'title': 'Weekday mornings win', 'text': "The Christkindlmarket, the Bean and the Walnut Room are calm on weekday mornings and packed on Saturday afternoons."},
  {'title': 'Christmas Day', 'text': "The Christkindlmarket ends at 4pm on 24 December. On 25 December many museums, ZooLights and Navy Pier's WonderFest are closed - but the Skydeck is open every day and the Maggie Daley ribbon has morning sessions."},
 ],
 'tips_intro': "Every tip here was checked against an official or trusted source (CTA, the City of Chicago, Chicago Police, the venues, CBP and others) on the date shown. Rules and prices change, so tap the link to double-check before you travel.",
 'christmas': {
  'intro': "Chicago does Christmas on a big scale. The Christkindlmarket on Daley Plaza, modelled on Nuremberg's and in its 30th year in 2026, opens on 20 November - the same evening the city lights its Christmas tree in Millennium Park - and the Magnificent Mile Lights Festival parade follows the next day. Add free skating, ZooLights, the Walnut Room and Christmas Around the World, and there is plenty for families. The flip side is crowds: in 2025 the city capped numbers at the market and queues formed outside.",
  'markets': [
   {'name': 'Christkindlmarket Chicago (Daley Plaza)', 'area': 'The Loop', 'when': '20 Nov - 24 Dec 2026 · Sun-Thu 11am-8pm, Fri-Sat 11am-9pm · Thanksgiving (26 Nov) and 24 Dec 11am-4pm', 'why': "A German-style market of wooden huts under the skyscrapers since 1996, with 50+ vendors (many from Germany): glass ornaments (including Chicago Bean ones), nutcrackers, gingerbread, bratwurst, pretzels, the famous raclette sandwich (about $17-18 in 2023-24) and Glühwein or hot chocolate in the collectable annual mug. Children get a free Kinder Club riddle passport, and there is a heated hall to warm up. A Krampus tent may frighten little ones.", 'family': True, 'price': 'Free entry · mug $10 empty, Glühwein about $12 with mug (2023-25)', 'crowds': "Very busy - queues of 20-40 people at food stalls and up to two hours for raclette at lunch. In 2025 the city capped the plaza at about 1,500 then 2,500 people, with queues outside. Weekday mornings are calmest. Creators found most food stalls cash only; ATMs are on site.", 'creators': ['aworldjotravel', 'legglife', 'natashaventure', 'lukegeetravels', 'throughmylens', 'wgnnews', 'cbschicago', 'backttalk', 'eatlocal', 'creativesenrou', 'fixology'], 'url': 'https://www.christkindlmarket.com'},
   {'name': 'Christkindlmarket Wrigleyville & Winterland', 'area': 'Gallagher Way, Wrigley Field', 'when': '20 Nov - 31 Dec 2026 · Mon-Thu 3-9pm, Fri-Sat 11am-9pm, Sun 11am-7pm · 24 Dec 11am-4pm · closed 25 Dec', 'why': "Back in 2026 after two years away. Creators preferred it to downtown for families: shorter queues, a carousel, skating, s'mores, a kids' train and a heated beer hall, with entry to the ballpark area about $5-10 in 2022-23.", 'family': True, 'price': 'Check 2026 prices', 'crowds': 'Less crowded than downtown; a younger crowd in the evenings.', 'creators': ['backttalk', 'eatlocal', 'michaelintheci'], 'url': 'https://www.christkindlmarket.com'},
   {'name': 'Millennium Park tree lighting & holiday market', 'area': 'Millennium Park', 'when': 'Fri 20 Nov 2026, lighting at 6pm · market 20-22 Nov only · tree up to 10 Jan 2027', 'why': "The 113th city tree lighting, with music from 5pm and Santa in 2025; a free weekend market of about 40 vendors runs beside it. The tree then stands by the Bean all season.", 'family': True, 'price': 'Free', 'crowds': "Packed on lighting night. After the 2025 lighting, a large teen gathering nearby turned violent - with children, leave as the event ends.", 'creators': ['cbschicago', 'lukegeetravels', 'toursbyfootchi'], 'url': 'https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park_visit.html'},
   {'name': 'Christkindlmarket Aurora', 'area': 'RiverEdge Park, Aurora (about 40 miles west)', 'when': '20 Nov - 24 Dec 2026 · Thu-Sun (hours vary)', 'why': "A smaller sister market in the suburbs, with its own collectable mug. Only worth it if you have a car or are staying west.", 'family': True, 'price': 'Free entry', 'crowds': 'Calmer than downtown.', 'creators': ['thejourneybegi', 'fixology', 'escapadeswithe'], 'url': 'https://www.christkindlmarket.com'},
  ],
  'sights': [
   {'name': 'ZooLights, Lincoln Park Zoo', 'area': 'Lincoln Park', 'when': '20 Nov 2026 - 3 Jan 2027 · 4:30-9pm · closed 26 Nov, 1, 8, 15, 24 and 25 Dec', 'why': "Lights across the free zoo, with skyline views, hot chocolate and s'mores, and Santa photos. Everyone needs a ticket, including babies; free Mondays (booking needed) on 23 and 30 Nov and 7 and 14 Dec.", 'family': True, 'price': '$7-12 in advance · $20 on the day (2026)', 'crowds': "Busy on weekends. Toilets are hard to find, and rideshares near impossible at rush hour - take the 151 bus or Brown Line.", 'creators': ['lukegeetravels', 'cairabutton', 'backttalk', 'allisonanderso'], 'url': 'https://www.lpzoo.org/event/zoolights/'},
   {'name': 'Magnificent Mile Lights Festival', 'area': 'Michigan Avenue', 'when': 'Sat 21 Nov 2026 · parade 5:30pm from Oak Street, heading south', 'why': "The 35th parade of floats, characters and Santa, lighting the trees along Michigan Avenue block by block. The lights then stay up all season.", 'family': True, 'price': 'Free', 'crowds': "Several blocks get dangerously packed - one creator had to turn back in 2025. Arrive early and agree a meeting point.", 'creators': ['samuelciochony', 'toursbyfootchi', 'annika'], 'url': 'https://themagnificentmile.com'},
   {'name': 'McCormick Tribune Ice Rink', 'area': 'Millennium Park', 'when': '20 Nov 2026 - Feb 2027 · daily 11am-10:30pm', 'why': "Skate under the Bean and the city tree. The city says admission is free; creators needed an online time slot.", 'family': True, 'price': 'Free · skate hire extra', 'crowds': "Slots sell out over the holidays - one creator only got 8am.", 'creators': ['toursbyfootchi', 'aworldjotravel', 'sydneialicia', 'cairabutton'], 'url': 'https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park_visit.html'},
   {'name': 'Maggie Daley Park Skating Ribbon', 'area': 'The Loop', 'when': '13 Nov 2026 - 7 Mar 2027 · two-hour sessions · 24 and 25 Dec mornings only', 'why': "A quarter-mile ribbon of ice winding uphill and down through the trees with skyline views. Skates run big, so size down.", 'family': True, 'price': 'Ticket for every session · skate hire $17-23', 'crowds': 'Much quieter than the Millennium Park rink.', 'creators': ['throughmylens', 'curio', 'luisgusto', 'chadandclaire'], 'url': 'https://www.maggiedaleypark.com'},
   {'name': "Macy's on State Street & the Walnut Room", 'area': 'The Loop', 'when': 'Great Tree 7 Nov - 10 Jan', 'why': "The old Marshall Field's store: themed windows, Frango mints and the Walnut Room's giant tree, where families eat chicken pot pie under the branches. Book on OpenTable early - one creator found it sold out a month ahead - but you can glimpse the tree from outside the restaurant.", 'family': True, 'price': 'Free to look', 'crowds': 'Busy at weekends.', 'creators': ['throughmylens', 'cbschicago', 'luisgusto', 'backttalk', 'toursbyfootchi'], 'url': maps("Macy's State Street")},
   {'name': 'Christmas Around the World, MSI', 'area': 'Hyde Park', 'when': 'From 7 Nov 2026', 'why': "A tradition since 1942: a four-storey Grand Tree and around 50 trees decorated by Chicago's communities, included with museum entry.", 'family': True, 'price': 'Museum admission', 'crowds': 'Very busy the week before Christmas - go early.', 'creators': ['throughmylens', 'cbschicago'], 'url': 'https://www.griffinmsi.org'},
   {'name': 'Winter WonderFest, Navy Pier', 'area': 'Streeterville', 'when': '27 Nov 2026 - 3 Jan 2027 · closed 25 Dec', 'why': "An indoor winter fair with rides, slides and skating, out of the cold.", 'family': True, 'price': '$27 online · $32 at the door · under 3 free (2026)', 'crowds': 'Busiest at weekends.', 'creators': ['aworldjotravel'], 'url': 'https://navypier.org'},
   {'name': 'Lightscape, Chicago Botanic Garden', 'area': 'Glencoe (about 25 miles north)', 'when': 'From 13 Nov · 4:30pm onwards (check 2026 dates)', 'why': "An illuminated evening trail with music, snacks and hot drinks. Best by car or Metra.", 'family': True, 'price': 'Varies by date', 'crowds': 'Timed entry.', 'creators': ['toursbyfootchi', 'travelthetop'], 'url': 'https://www.chicagobotanic.org'},
   {'name': 'The CTA Holiday Train', 'area': 'Changes line daily', 'when': 'December', 'why': "A train covered in lights with Santa in an open flatcar sleigh, running in normal service on a different line each day - check the CTA website.", 'family': True, 'price': 'Normal fare', 'crowds': "Can be packed - on 18 December 2024 riders at Washington were told to wait for the next one.", 'creators': ['cairabutton', 'throughmylens', 'thisgemini'], 'url': 'https://www.transitchicago.com'},
  ],
  'safety': [
   {'title': 'Crowds and timing', 'text': "The Christkindlmarket is packed on Friday and Saturday evenings and calm on weekday mornings. The tree lighting (Fri 20 Nov) and the Lights Festival parade (Sat 21 Nov) fill whole blocks - arrive early, agree a meeting point and leave before the very end.", 'creators': ['aworldjotravel', 'eatlocal', 'annika', 'backttalk']},
   {'title': 'Teen gatherings after big events', 'text': "After the 2025 tree lighting, a large unsupervised teen gathering near State Street ended in shootings. Millennium Park now requires under-18s to be with an adult aged 21+ after 6pm Friday to Sunday, with bag checks at the Michigan Avenue gates. With children, enjoy the early evening and head back to your hotel as crowds of teenagers build. 2026 security plans had not been published by early October.", 'creators': ['thedcshorts', 'lukegeetravels']},
   {'title': 'Pickpockets and card skimming', 'text': "The Better Business Bureau warns of 'bump and skim' card thieves in holiday crowds. Keep wallets in front pockets, bags zipped and phones in hand, and never let a stranger tap your phone or card for a 'donation'.", 'creators': ['cbschicago', 'woltersworld']},
   {'title': 'Cash, mugs and prices', 'text': "Creators found most market food stalls cash only, with ATM queues. Expect $10-12 for food and drinks and $10 for the annual mug (2023-25); $20 bought just a coffee, a bratwurst and a pretzel in 2025.", 'creators': ['legglife', 'lukegeetravels', 'aworldjotravel', 'creativesenrou']},
   {'title': 'Cold and dark', 'text': "Sunset is about 4:20pm in December, and creators saw anything from 50°F with a -10°F wind chill to -13°C and snow. Most of the market is outdoors and standing - layers, hat, gloves, warm boots and hand warmers.", 'creators': ['lukegeetravels', 'annika', 'arbaazvlogs', 'jiyabhatia']},
   {'title': 'Have a lost-child plan', 'text': "Before you go in, agree a meeting point everyone can find - the Picasso sculpture on Daley Plaza works for the market, the Bean for Millennium Park. A Wiley Fox QR wristband on each child means anyone who finds them can reach you straight away.", 'creators': []},
   {'title': "New Year's Eve", 'text': "Navy Pier fireworks over the lake are the classic New Year's Eve view, but 2026 details were not published by early October. Expect big crowds downtown and plan your route back.", 'creators': ['lostinthepond', 'goplaceswithta']},
  ],
  'plan': "In 2026 the Christkindlmarket and the city tree both start on Friday 20 November, and the Lights Festival parade is on Saturday 21 November. The Daley Plaza market closes at 4pm on 24 December; Wrigleyville runs to 31 December (closed on Christmas Day). ZooLights is closed on 24 and 25 December, and Navy Pier's WonderFest on the 25th. Thanksgiving is Thursday 26 November - expect closures and busy travel that weekend. Book skating, the Walnut Room and hotels early.",
 },
 'map': {'center': [-87.64, 41.89], 'zoom': 11.6},
 'creators': creators,
 'sources': sources,
}
# sanity: every creator key referenced exists
refs = set()
def walk(x):
    if isinstance(x, dict):
        for k, v in x.items():
            if k == 'creators' and isinstance(v, list): refs.update(v)
            elif k == 'source' and isinstance(v, str) and v.islower(): refs.add(v)
            else: walk(v)
    elif isinstance(x, list): [walk(i) for i in x]
walk({k: v for k, v in G.items() if k != 'creators'})
missing = sorted(r for r in refs if r not in creators)
print('creators', NC, 'videos', NV, 'missing keys:', missing)
json.dump(G, open(f'{D}/guide.json', 'w'), ensure_ascii=False, indent=1)
json.dump({'tips': tips}, open(f'{D}/tips.json', 'w'), ensure_ascii=False, indent=1)
